gaia::base::VectorImpl Class Reference
gaia::base::VectorImpl Class Reference
Implements vector data structure equipped with copy-on-write mechanism.
#include <VectorImpl.h>
Private Types
enum { HAS_TRIVIAL_CTOR = 0x00000001, HAS_TRIVIAL_DTOR = 0x00000002, HAS_TRIVIAL_COPY = 0x00000004 }
Flags passed to the ctor.
Private Member Functions
VectorImpl (size_t itemSize, uint32_t flags)
Constructor for VectorImpl.
VectorImpl (const VectorImpl &rhs)
Copy constructor of VectorImpl.
virtual ~VectorImpl ()
Destructor of VectorImpl.
void finish_vector ()
Destories datum and releases datum storage.
VectorImpl & operator= (const VectorImpl &rhs)
This VectorImpl release its datum and acquire for use rhs datum.
const void * arrayImpl () const
Acquires for direct use of inner datum.
void * editArrayImpl ()
Check datum before editing inner data.
size_t size () const
Gets the number of datum it possessed.
bool isEmpty () const
Checks if possessed vector is empty.
size_t capacity () const
Gets storage capacity.
ssize_t setCapacity (size_t size)
Sets storage capacity.
ssize_t insertVectorAt (const VectorImpl &vector, size_t index)
Inserts the other vector into this vector at specified location.
ssize_t appendVector (const VectorImpl &vector)
Appends the other vector at the end of this vector.
ssize_t insertArrayAt (const void *array, size_t index, size_t length)
Insert a C-style array into this vector.
ssize_t appendArray (const void *array, size_t length)
Appends a C-style array at the end of this vector.
void copyIntoArray (void *array, size_t length) const
Copies datum into the given C-style array.
ssize_t insertAt (const void *item, size_t where, size_t numItems=1)
Inserts numbers of items into this vector at specified location.
void pop ()
Pops the top of the stack (removes the last element).
void push ()
Pushes an blank item on the top of the stack.
void push (const void *item)
Pushes an item on the top of the stack.
void append (const void *item, size_t numItems)
Appends numbers of items at the end of vector.
ssize_t replaceAt (const void *item, size_t index)
Replaces an item at the specified index.
ssize_t removeItemsAt (size_t index, size_t count=1)
Removes numbers of items start from the specified index.
void clear ()
Removes all items in this vector.
const void * itemLocation (size_t index) const
Acquires the data at the specified index.
void * editItemLocation (size_t index)
Acquires the data at the specified index.
size_t itemSize () const
Acquires size of stored data type.
void release_storage ()
Release storage.
virtual void do_construct (void *storage, size_t num) const =0
Used to construct datum stored in the vector.
virtual void do_destroy (void *storage, size_t num) const =0
Used to destory datum stored in the list.
virtual void do_copy (void *dest, const void *from, size_t num) const =0
Used to copy datum stored in the list.
virtual void do_splat (void *dest, const void *item, size_t num) const =0
Used to copy numbers of the same item to specified location.
virtual void do_move_forward (void *dest, const void *from, size_t num) const =0
Used to backward copies numbers of datum to specified location.
virtual void do_move_backward (void *dest, const void *from, size_t num) const =0
Used to forward copies numbers of datum to specified location.
virtual void reservedVectorImpl1 ()
Used to compares two datum if there are the same.
virtual void reservedVectorImpl2 ()
take care of FBC.
virtual void reservedVectorImpl3 ()
take care of FBC.
virtual void reservedVectorImpl4 ()
take care of FBC.
virtual void reservedVectorImpl5 ()
take care of FBC.
virtual void reservedVectorImpl6 ()
take care of FBC.
virtual void reservedVectorImpl7 ()
take care of FBC.
virtual void reservedVectorImpl8 ()
take care of FBC.
void * _grow (size_t where, size_t amount)
Increase the specified amount of space from location specified by parameter where.
void _shrink (size_t where, size_t amount)
Decrease the specified amount of space to location specified by parameter where.
void _do_construct (void *storage, size_t num) const
Construct data by calling the constructor of that data type.
void _do_destroy (void *storage, size_t num) const
Destory data by calling the destructor of that data type.
void _do_copy (void *dest, const void *from, size_t num) const
Copy data by calling the copy constructor of that data tpye.
void _do_splat (void *dest, const void *item, size_t num) const
Copy data by calling do_splat()
void _do_move_forward (void *dest, const void *from, size_t num) const
Copy data by calling do_move_forward()
void _do_move_backward (void *dest, const void *from, size_t num) const
Copy data by calling do_move_backward()
Private Attributes
void * mStorage
Base address of the vector.
size_t mCount
Number of items.
const uint32_t mFlags
Characteristics of the stored data.
const size_t mItemSize
Size of the type of stored data.
Detailed Description
Implements vector data structure equipped with copy-on-write mechanism.
Implementation of the guts of the vector<> class this ensures backward binary compatibility and reduces code size. For performance reasons, we expose mStorage and mCount so these fields are set in stone.
Warning:
This class is not used directly. Vector should use instead.
 // Creates a VectorImpl
 VectorImpl vec_impl(sizeof(int), HAS_TRIVIAL_CTOR);
 // Appends five integers
 int32_t testItem = 2011;
 vec_impl.insertAt(testItem, size(), 5);
 // Replace the 3rd items (index is 2)
 int32_t testRep = 2012;
 vec_impl.replaceAt(testRep, 2);
 // Clear all items
 vec_impl.clear();
Definition at line 63 of file VectorImpl.h.
Member Enumeration Documentation
anonymous enum [private]
Flags passed to the ctor.
Enumerator:
HAS_TRIVIAL_CTOR
HAS_TRIVIAL_DTOR
HAS_TRIVIAL_COPY
Definition at line 69 of file VectorImpl.h.
Constructor & Destructor Documentation
gaia::base::VectorImpl::VectorImpl (size_t itemSize, uint32_t flags) [private]
Constructor for VectorImpl.
Parameters:
itemSize Data size of those datum which will be stored.
flags Characteristics of stored data type.
See also:
TypeHelpers.h
gaia::base::VectorImpl::VectorImpl (const VectorImpl & rhs) [private]
Copy constructor of VectorImpl.
Acquire right of rhs data usage.
Parameters:
rhs The other VectorImpl entity provided for copy.
virtual gaia::base::VectorImpl::~VectorImpl () [private, virtual]
Destructor of VectorImpl.
Member Function Documentation
void gaia::base::VectorImpl::_do_construct (void * storage, size_t num) const [inline, private]
Construct data by calling the constructor of that data type.
Parameters:
storage The memory address where data is stored into.
num The number of datum counted in the unit of specified data type.
void gaia::base::VectorImpl::_do_copy (void * dest, const void * from, size_t num) const [inline, private]
Copy data by calling the copy constructor of that data tpye.
Parameters:
dest The memory address that datum is copied to.
from The memory address that datum is copied from.
num The number of datum counted in the unit of specified data type.
void gaia::base::VectorImpl::_do_destroy (void * storage, size_t num) const [inline, private]
Destory data by calling the destructor of that data type.
Parameters:
storage The memory address where data is stored into.
num The number of datum counted in the unit of specified data type.
void gaia::base::VectorImpl::_do_move_backward (void * dest, const void * from, size_t num) const [inline, private]
Copy data by calling do_move_backward()
Parameters:
dest The memory address that datum is copied to.
from The memory address that datum is copied from.
num The number of datum counted in the unit of specified data type.
void gaia::base::VectorImpl::_do_move_forward (void * dest, const void * from, size_t num) const [inline, private]
Copy data by calling do_move_forward()
Parameters:
dest The memory address that datum is copied to.
from The memory address that datum is copied from.
num The number of datum counted in the unit of specified data type.
void gaia::base::VectorImpl::_do_splat (void * dest, const void * item, size_t num) const [inline, private]
Copy data by calling do_splat()
Parameters:
dest The memory address that datum is copied to.
item The memory address that datum is copied from.
num The number of datum counted in the unit of specified data type.
void* gaia::base::VectorImpl::_grow (size_t where, size_t amount) [private]
Increase the specified amount of space from location specified by parameter where.
Parameters:
where Location to grow vector size from.
amount Amount of memory required.
Returns:
The location pointed by parameter where.
void gaia::base::VectorImpl::_shrink (size_t where, size_t amount) [private]
Decrease the specified amount of space to location specified by parameter where.
Parameters:
where Location to shrink vector size to.
amount Amount of memory to be removed.
void gaia::base::VectorImpl::append (const void * item, size_t numItems) [private]
Appends numbers of items at the end of vector.
Parameters:
item The item to append.
numItems Number of datum to be appended.
Referenced by gaia::base::Vector< TYPE >::append().
ssize_t gaia::base::VectorImpl::appendArray (const void * array, size_t length) [private]
Appends a C-style array at the end of this vector.
Parameters:
array The C-style array to be inserted.
length Number of datum to be inserted.
Returns:
The copied datum in list vector if copy is successful. NO_MEMORY if operation failed. BAD_INDEX if index is out of boundary.
See also:
gerrcode.h for error code.
ssize_t gaia::base::VectorImpl::appendVector (const VectorImpl & vector) [private]
Appends the other vector at the end of this vector.
Parameters:
vector The other vector to be inserted.
Returns:
The copied datum in list vector if copy is successful. NO_MEMORY if operation failed. BAD_INDEX if index is out of boundary.
See also:
gerrcode.h for error code.
Referenced by gaia::base::Vector< TYPE >::appendVector().
const void* gaia::base::VectorImpl::arrayImpl () const [inline, private]
Acquires for direct use of inner datum.
Warning:
C-style array access!
Returns:
Memory address of the first itme. Operates as C-style array.
Definition at line 126 of file VectorImpl.h.
References mStorage.
Referenced by gaia::base::Vector< TYPE >::innerDatum().
size_t gaia::base::VectorImpl::capacity () const [private]
Gets storage capacity.
Capacity is the actual memory vector possesses. Size is the number of stored data.
See also:
VectorImpl::size()
Returns:
Capacity of its storage.
Reimplemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
Referenced by gaia::base::Vector< TYPE >::capacity().
void gaia::base::VectorImpl::clear () [private]
Removes all items in this vector.
Reimplemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
Referenced by gaia::base::Vector< TYPE >::clear().
void gaia::base::VectorImpl::copyIntoArray (void * array, size_t length) const [private]
Copies datum into the given C-style array.
Datum in array is destoried.
Parameters:
array Space to store copied datum.
length Number of datum to be copied.
Referenced by gaia::base::Vector< TYPE >::toArray().
virtual void gaia::base::VectorImpl::do_construct (void * storage, size_t num) const [private, pure virtual]
Used to construct datum stored in the vector.
This virtual function should be implemented by sub-classes.
Parameters:
storage The memory address of stored datum.
num Number of datum in the unit of data type.
Implemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
virtual void gaia::base::VectorImpl::do_copy (void * dest, const void * from, size_t num) const [private, pure virtual]
Used to copy datum stored in the list.
This virtual function should be implemented by sub-classes.
Parameters:
dest The memory address of space that datum is copied to.
from The memory address of datum, which is to be copied.
num Number of datum in the unit of data type.
Implemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
virtual void gaia::base::VectorImpl::do_destroy (void * storage, size_t num) const [private, pure virtual]
Used to destory datum stored in the list.
This virtual function should be implemented by sub-classes.
Parameters:
storage The memory address of stored datum.
num Number of datum in the unit of data type.
Implemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
virtual void gaia::base::VectorImpl::do_move_backward (void * dest, const void * from, size_t num) const [private, pure virtual]
Used to forward copies numbers of datum to specified location.
This virtual function should be implemented by sub-classes.
Parameters:
dest The memory address of space that datum is copied to.
from The memory address of datum, which is to be copied.
num Number of datum in the unit of data type.
Implemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
virtual void gaia::base::VectorImpl::do_move_forward (void * dest, const void * from, size_t num) const [private, pure virtual]
Used to backward copies numbers of datum to specified location.
This virtual function should be implemented by sub-classes.
Parameters:
dest The memory address of space that datum is copied to.
from The memory address of datum, which is to be copied.
num Number of datum in the unit of data type.
Implemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
virtual void gaia::base::VectorImpl::do_splat (void * dest, const void * item, size_t num) const [private, pure virtual]
Used to copy numbers of the same item to specified location.
This virtual function should be implemented by sub-classes.
Parameters:
dest The memory address of space that datum is copied to.
item The memory address of datum, which is to be copied.
num Number of datum in the unit of data type.
Implemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
void* gaia::base::VectorImpl::editArrayImpl () [private]
Check datum before editing inner data.
If datum is not own by itslef, copy-on-write mechanism is activated.
Warning:
C-style array access!
Returns:
Memory address of the first itme. Operates as C-style array.
Referenced by gaia::base::Vector< TYPE >::innerDatum().
void* gaia::base::VectorImpl::editItemLocation (size_t index) [private]
Acquires the data at the specified index.
This function answers editing needs.
Parameters:
index Index of the data.
Returns:
Non-const data pointer if data is acquired, 0 otherwise.
void gaia::base::VectorImpl::finish_vector () [private]
Destories datum and releases datum storage.
Warning:
Must be called by subclasses destructor.
ssize_t gaia::base::VectorImpl::insertArrayAt (const void * array, size_t index, size_t length) [private]
Insert a C-style array into this vector.
Parameters:
array The C-style array to be inserted.
index The location that data insertion start from.
length Number of datum to be inserted.
Returns:
The copied datum in list vector if copy is successful. NO_MEMORY if operation failed. BAD_INDEX if index is out of boundary.
See also:
gerrcode.h for error code.
ssize_t gaia::base::VectorImpl::insertAt (const void * item, size_t where, size_t numItems = 1) [private]
Inserts numbers of items into this vector at specified location.
Parameters:
item The item to be inserted.
where The location start to insert from.
numItems Nubmer of item to be inserted.
Returns:
Index of the inserted item if insertion is successful. NO_MEMORY if operation failed. BAD_INDEX if the parameter where is out of boundary.
See also:
gerrcode.h for error code.
Referenced by gaia::base::Vector< TYPE >::insertAt().
ssize_t gaia::base::VectorImpl::insertVectorAt (const VectorImpl & vector, size_t index) [private]
Inserts the other vector into this vector at specified location.
Parameters:
vector The other vector to be inserted.
index The location that data insertion start from.
Returns:
The copied datum in list vector if copy is successful. NO_MEMORY if operation failed. BAD_INDEX if index is out of boundary.
See also:
gerrcode.h for error code.
Referenced by gaia::base::Vector< TYPE >::insertVectorAt().
bool gaia::base::VectorImpl::isEmpty () const [inline, private]
Checks if possessed vector is empty.
Returns:
True if it is empty, false otherwise.
Reimplemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
Definition at line 152 of file VectorImpl.h.
References mCount.
Referenced by gaia::base::Vector< TYPE >::isEmpty().
const void* gaia::base::VectorImpl::itemLocation (size_t index) const [private]
Acquires the data at the specified index.
Parameters:
index Index of the data.
Returns:
Const data pointer if data is acquired, 0 otherwise.
size_t gaia::base::VectorImpl::itemSize () const [private]
Acquires size of stored data type.
Returns:
Size of stored data type.
VectorImpl& gaia::base::VectorImpl::operator= (const VectorImpl & rhs) [private]
This VectorImpl release its datum and acquire for use rhs datum.
Parameters:
rhs The other VectorImpl entity provided for assignment.
Returns:
Address of this VectorImpl.
Referenced by gaia::base::Vector< TYPE >::operator=().
void gaia::base::VectorImpl::pop () [private]
Pops the top of the stack (removes the last element).
No-op if the stack is empty.
Reimplemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
Referenced by gaia::base::Vector< TYPE >::pop().
void gaia::base::VectorImpl::push () [private]
Pushes an blank item on the top of the stack.
Referenced by gaia::base::Vector< TYPE >::push().
void gaia::base::VectorImpl::push (const void * item) [private]
Pushes an item on the top of the stack.
Parameters:
item The item to be pushed into this vector.
void gaia::base::VectorImpl::release_storage () [private]
Release storage.
Destory all datum if this vector is the only owner. Otherwise, release its right of use.
ssize_t gaia::base::VectorImpl::removeItemsAt (size_t index, size_t count = 1) [private]
Removes numbers of items start from the specified index.
Parameters:
index Remove starts from here.
count Nubmer of items to be removed.
Returns:
The parameter index if remove is successful. BAD_VALUE if the given range is out of boundary.
Referenced by gaia::base::Vector< TYPE >::removeAt().
ssize_t gaia::base::VectorImpl::replaceAt (const void * item, size_t index) [private]
Replaces an item at the specified index.
Parameters:
item The item to replace.
index Location of data to be replaced.
Returns:
Index of the new item.
Referenced by gaia::base::Vector< TYPE >::replaceAt().
virtual void gaia::base::VectorImpl::reservedVectorImpl1 () [private, virtual]
Used to compares two datum if there are the same.
This virtual function should be implemented by sub-classes.
Parameters:
lhs One data.
rhs The other data.
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl2 () [private, virtual]
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl3 () [private, virtual]
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl4 () [private, virtual]
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl5 () [private, virtual]
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl6 () [private, virtual]
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl7 () [private, virtual]
take care of FBC.
virtual void gaia::base::VectorImpl::reservedVectorImpl8 () [private, virtual]
take care of FBC.
ssize_t gaia::base::VectorImpl::setCapacity (size_t size) [private]
Sets storage capacity.
Warning:
Capacity should always more than number of inner datum.
Returns:
New capacity if memory allocation is successful, NO_MEMORY otherwise.
See also:
gerrcode.h for error code.
Reimplemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
Referenced by gaia::base::Vector< TYPE >::setCapacity().
size_t gaia::base::VectorImpl::size () const [inline, private]
Gets the number of datum it possessed.
Returns:
The number of datum.
Reimplemented in gaia::base::Vector< TYPE >, gaia::base::Vector< gaia::ui::DialogBox * >, gaia::base::Vector< gaia::graphics::Rect * >, gaia::base::Vector< PluginMetaDataInfo * >, gaia::base::Vector< int32_t >, gaia::base::Vector< MediaCodecInfo::CodecProfileLevel * >, gaia::base::Vector< Vector< TYPE > >, gaia::base::Vector< RemovedObject * >, and gaia::base::Vector< EmptyTestEventListener * >.
Definition at line 144 of file VectorImpl.h.
References mCount.
Referenced by gaia::base::Vector< TYPE >::size().
Member Data Documentation
size_t gaia::base::VectorImpl::mCount [private]
Number of items.
Definition at line 628 of file VectorImpl.h.
Referenced by isEmpty(), and size().
const uint32_t gaia::base::VectorImpl::mFlags [private]
Characteristics of the stored data.
Definition at line 633 of file VectorImpl.h.
const size_t gaia::base::VectorImpl::mItemSize [private]
Size of the type of stored data.
Definition at line 638 of file VectorImpl.h.
void* gaia::base::VectorImpl::mStorage [private]
Base address of the vector.
Definition at line 623 of file VectorImpl.h.
Referenced by arrayImpl().
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/base/VectorImpl.h