gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 > Class Template Reference
gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 > Class Template Reference
#include <ListItem.h>
Public Member Functions
ListItem (gaia::core::Page *pPage)
ListItem (gaia::core::Context *pContext)
virtual ~ListItem ()
void getHandler (typename Panel1::Handler **pHandler)
void getHandler (typename Panel2::Handler **pHandler)
void getHandler (typename Panel3::Handler **pHandler)
void getHandler (typename Panel4::Handler **pHandler)
void getHandler (typename Panel5::Handler **pHandler)
USING_OVERLOADING_FUNC (gaia::core::WidgetController::addWidget)
template<class PanelType >
CLASS_TEMPLATE PanelType::Handler * addWidget (PanelTraits< PanelType > UNUSED(traits), gaia::core::Page *pPage)
template<class PanelType >
CLASS_TEMPLATE PanelType::Handler * addWidget (PanelTraits< PanelType > UNUSED(traits), gaia::core::Context *pContext)
Protected Member Functions
template<class PanelType >
PanelType::Handler * addWidget (PanelTraits< PanelType > traits, gaia::core::Page *pPage)
NullPanel::Handler * addWidget (PanelTraits< NullPanel > traits, gaia::core::Page *pPage)
NullPanel::Handler * addWidget (PanelTraits< NullPanel > traits, gaia::core::Context *pContext)
template<class PanelType >
PanelType::Handler * addWidget (PanelTraits< PanelType > traits, gaia::core::Context *pContext)
DISALLOW_COPY_AND_ASSIGN (ListItem)
Protected Attributes
Panel1::Handler * mpPanel1Handler
Panel2::Handler * mpPanel2Handler
Panel3::Handler * mpPanel3Handler
Panel4::Handler * mpPanel4Handler
Panel5::Handler * mpPanel5Handler
Detailed Description
template<class Panel1, class Panel2, class Panel3, class Panel4, class Panel5>
class gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >
Definition at line 45 of file ListItem.h.
Constructor & Destructor Documentation
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem (gaia::core::Page * pPage) [explicit]
Definition at line 95 of file ListItem.h.
References gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget(), gaia::ui::LinearController::HORIZONTAL, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel1Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel2Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel3Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel4Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel5Handler, and gaia::ui::LinearController::setOrientation().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem (gaia::core::Context * pContext) [explicit]
Definition at line 106 of file ListItem.h.
References gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget(), gaia::ui::LinearController::HORIZONTAL, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel1Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel2Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel3Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel4Handler, gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel5Handler, and gaia::ui::LinearController::setOrientation().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::~ListItem () [virtual]
Definition at line 117 of file ListItem.h.
Member Function Documentation
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > template<class PanelType > PanelType::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget (PanelTraits< PanelType > traits, gaia::core::Page * pPage) [protected]
Referenced by gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > NullPanel::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget (PanelTraits< NullPanel > traits, gaia::core::Page * pPage) [protected]
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > NullPanel::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget (PanelTraits< NullPanel > traits, gaia::core::Context * pContext) [protected]
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > template<class PanelType > PanelType::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget (PanelTraits< PanelType > traits, gaia::core::Context * pContext) [protected]
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > template<class PanelType > CLASS_TEMPLATE PanelType::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget (PanelTraits< PanelType > UNUSEDtraits, gaia::core::Page * pPage)
Definition at line 134 of file ListItem.h.
References gaia::core::WidgetController::addWidget().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > template<class PanelType > CLASS_TEMPLATE PanelType::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::addWidget (PanelTraits< PanelType > UNUSEDtraits, gaia::core::Context * pContext)
Definition at line 146 of file ListItem.h.
References gaia::core::WidgetController::addWidget().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::DISALLOW_COPY_AND_ASSIGN (ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >) [protected]
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE void gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::getHandler (typename Panel1::Handler ** pHandler)
Definition at line 170 of file ListItem.h.
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE void gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::getHandler (typename Panel2::Handler ** pHandler)
Definition at line 175 of file ListItem.h.
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE void gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::getHandler (typename Panel3::Handler ** pHandler)
Definition at line 180 of file ListItem.h.
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE void gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::getHandler (typename Panel4::Handler ** pHandler)
Definition at line 185 of file ListItem.h.
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > CLASS_TEMPLATE void gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::getHandler (typename Panel5::Handler ** pHandler)
Definition at line 190 of file ListItem.h.
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::USING_OVERLOADING_FUNC (gaia::core::WidgetController::addWidget)
Member Data Documentation
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > Panel1::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel1Handler [protected]
Definition at line 80 of file ListItem.h.
Referenced by gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > Panel2::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel2Handler [protected]
Definition at line 81 of file ListItem.h.
Referenced by gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > Panel3::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel3Handler [protected]
Definition at line 82 of file ListItem.h.
Referenced by gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > Panel4::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel4Handler [protected]
Definition at line 83 of file ListItem.h.
Referenced by gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem().
template<class Panel1 , class Panel2 , class Panel3 , class Panel4 , class Panel5 > Panel5::Handler* gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::mpPanel5Handler [protected]
Definition at line 84 of file ListItem.h.
Referenced by gaia::ui::ListItem< Panel1, Panel2, Panel3, Panel4, Panel5 >::ListItem().
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/ui/ListItem.h