gaia::core::Export< CLASS, gaia::content::ContentProvider > Class Template Reference
gaia::core::Export< CLASS, gaia::content::ContentProvider > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static
gaia::content::ContentProvider * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, gaia::content::ContentProvider >
Definition at line 394 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, gaia::content::ContentProvider >::Export () [private]
Definition at line 417 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, gaia::content::ContentProvider >::constructor () [static, private]
Definition at line 421 of file Export.h.
References gaia::core::COMPONENT_CONTENTPROVIDER, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, gaia::content::ContentProvider >::destructor () [static, private]
Definition at line 428 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > gaia::content::ContentProvider * gaia::core::Export< CLASS, gaia::content::ContentProvider >::maker () [static, private]
Definition at line 435 of file Export.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/Export.h