gaia::core::Export< CLASS, gaia::core::MultiWindow > Class Template Reference
gaia::core::Export< CLASS, gaia::core::MultiWindow > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static gaia::core::MultiWindow * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, gaia::core::MultiWindow >
Definition at line 643 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, gaia::core::MultiWindow >::Export () [private]
Definition at line 666 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, gaia::core::MultiWindow >::constructor () [static, private]
Definition at line 670 of file Export.h.
References gaia::core::COMPONENT_MULTIWINDOW, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, gaia::core::MultiWindow >::destructor () [static, private]
Definition at line 678 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > gaia::core::MultiWindow * gaia::core::Export< CLASS, gaia::core::MultiWindow >::maker () [static, private]
Definition at line 685 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h