gaia::core::GL11Ext Class Reference
gaia::core::GL11Ext Class Reference
#include <GL11Ext.h>
Public Types
enum GL11ExtMacro {
GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES = 0x8B9E, GL_MATRIX_INDEX_ARRAY_OES = 0x8844, GL_MATRIX_INDEX_ARRAY_POINTER_OES = 0x8849, GL_MATRIX_INDEX_ARRAY_SIZE_OES = 0x8846,
GL_MATRIX_INDEX_ARRAY_STRIDE_OES = 0x8848, GL_MATRIX_INDEX_ARRAY_TYPE_OES = 0x8847, GL_MATRIX_PALETTE_OES = 0x8840, GL_MAX_PALETTE_MATRICES_OES = 0x8842,
GL_MAX_VERTEX_UNITS_OES = 0x86A4, GL_TEXTURE_CROP_RECT_OES = 0x8B9D, GL_WEIGHT_ARRAY_BUFFER_BINDING_OES = 0x889E, GL_WEIGHT_ARRAY_OES = 0x86AD,
GL_WEIGHT_ARRAY_POINTER_OES = 0x86AC, GL_WEIGHT_ARRAY_SIZE_OES = 0x86AB, GL_WEIGHT_ARRAY_STRIDE_OES = 0x86AA, GL_WEIGHT_ARRAY_TYPE_OES = 0x86A9
}
Public Member Functions
GL11Ext ()
GL11Ext (const GL11Ext &gl11Ext)
virtual ~GL11Ext ()
GL11Ext & operator= (const GL11Ext &other)
void glCurrentPaletteMatrixOES (int32_t matrixpaletteindex)
void glDrawTexfOES (float x, float y, float z, float width, float height)
void glDrawTexfvOES (const gaia::base::Array< float > &coords, int32_t offset)
void glDrawTexfvOES (const gaia::base::Array< float > &coords)
void glDrawTexiOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)
void glDrawTexivOES (const gaia::base::Array< int32_t > &coords, int32_t offset)
void glDrawTexivOES (const gaia::base::Array< int32_t > &coords)
void glDrawTexsOES (int16_t x, int16_t y, int16_t z, int16_t width, int16_t height)
void glDrawTexsvOES (const gaia::base::Array< int16_t > &coords)
void glDrawTexsvOES (const gaia::base::Array< int16_t > &coords, int32_t offset)
void glDrawTexxOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)
void glDrawTexxvOES (const gaia::base::Array< int32_t > &coords, int32_t offset)
void glDrawTexxvOES (const gaia::base::Array< int32_t > &coords)
void glEnable (int32_t cap)
void glEnableClientState (int32_t array)
void glLoadPaletteFromModelViewMatrixOES ()
template<typename T >
void glMatrixIndexPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
void glMatrixIndexPointerOES (int32_t size, int32_t type, int32_t stride, int32_t offset)
void glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > &param, int32_t offset)
void glWeightPointerOES (int32_t size, int32_t type, int32_t stride, int32_t offset)
template<typename T >
void glWeightPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
Detailed Description
Definition at line 15 of file GL11Ext.h.
Member Enumeration Documentation
enum gaia::core::GL11Ext::GL11ExtMacro
Enumerator:
GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES
GL_MATRIX_INDEX_ARRAY_OES
GL_MATRIX_INDEX_ARRAY_POINTER_OES
GL_MATRIX_INDEX_ARRAY_SIZE_OES
GL_MATRIX_INDEX_ARRAY_STRIDE_OES
GL_MATRIX_INDEX_ARRAY_TYPE_OES
GL_MATRIX_PALETTE_OES
GL_MAX_PALETTE_MATRICES_OES
GL_MAX_VERTEX_UNITS_OES
GL_TEXTURE_CROP_RECT_OES
GL_WEIGHT_ARRAY_BUFFER_BINDING_OES
GL_WEIGHT_ARRAY_OES
GL_WEIGHT_ARRAY_POINTER_OES
GL_WEIGHT_ARRAY_SIZE_OES
GL_WEIGHT_ARRAY_STRIDE_OES
GL_WEIGHT_ARRAY_TYPE_OES
Definition at line 17 of file GL11Ext.h.
Constructor & Destructor Documentation
gaia::core::GL11Ext::GL11Ext ()
gaia::core::GL11Ext::GL11Ext (const GL11Ext & gl11Ext)
virtual gaia::core::GL11Ext::~GL11Ext () [virtual]
Member Function Documentation
void gaia::core::GL11Ext::glCurrentPaletteMatrixOES (int32_t matrixpaletteindex)
void gaia::core::GL11Ext::glDrawTexfOES (float x, float y, float z, float width, float height)
void gaia::core::GL11Ext::glDrawTexfvOES (const gaia::base::Array< float > & coords, int32_t offset)
void gaia::core::GL11Ext::glDrawTexfvOES (const gaia::base::Array< float > & coords)
void gaia::core::GL11Ext::glDrawTexiOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)
void gaia::core::GL11Ext::glDrawTexivOES (const gaia::base::Array< int32_t > & coords, int32_t offset)
void gaia::core::GL11Ext::glDrawTexivOES (const gaia::base::Array< int32_t > & coords)
void gaia::core::GL11Ext::glDrawTexsOES (int16_t x, int16_t y, int16_t z, int16_t width, int16_t height)
void gaia::core::GL11Ext::glDrawTexsvOES (const gaia::base::Array< int16_t > & coords)
void gaia::core::GL11Ext::glDrawTexsvOES (const gaia::base::Array< int16_t > & coords, int32_t offset)
void gaia::core::GL11Ext::glDrawTexxOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)
void gaia::core::GL11Ext::glDrawTexxvOES (const gaia::base::Array< int32_t > & coords, int32_t offset)
void gaia::core::GL11Ext::glDrawTexxvOES (const gaia::base::Array< int32_t > & coords)
void gaia::core::GL11Ext::glEnable (int32_t cap)
void gaia::core::GL11Ext::glEnableClientState (int32_t array)
void gaia::core::GL11Ext::glLoadPaletteFromModelViewMatrixOES ()
template<typename T > void gaia::core::GL11Ext::glMatrixIndexPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 89 of file GL11Ext.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL11Ext::glMatrixIndexPointerOES (int32_t size, int32_t type, int32_t stride, int32_t offset)
void gaia::core::GL11Ext::glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > & param, int32_t offset)
void gaia::core::GL11Ext::glWeightPointerOES (int32_t size, int32_t type, int32_t stride, int32_t offset)
template<typename T > void gaia::core::GL11Ext::glWeightPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 104 of file GL11Ext.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
GL11Ext& gaia::core::GL11Ext::operator= (const GL11Ext & other)
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/GL11Ext.h