gaia::core::Parcel Class Reference
gaia::core::Parcel Class Reference
Container for a message (data and object references)
#include <Parcel.h>
Public Member Functions
Parcel ()
Create an empty Parcel.
~Parcel ()
Destructor.
size_t dataAvail () const
Returns the amount of data remaining to be read from the parcel.
size_t dataPosition () const
Returns the current position in the parcel data.
size_t dataSize () const
Returns the total amount of data contained in the parcel.
void setDataPosition (size_t pos) const
Move the current read/write position in the parcel.
void setDataSize (size_t size)
Change the amount of data in the parcel.
byte_t readByte () const
Read a byte value from the parcel at the current dataPosition().
int32_t readInt () const
Read an integer value from the parcel at the current dataPosition().
float readFloat () const
Read an Float value from the parcel at the current dataPosition(),.
double readDouble () const
Read an double value from the parcel at the current dataPosition(),.
int64_t readLong () const
Read a long integer value from the parcel at the current dataPosition(),.
gaia::base::String readString () const
Read an String from the parcel at the current dataPosition(),.
void writeByte (byte_t val)
Write a byte value into the parcel at current dataPosition().
void writeInt (int32_t val)
Write an integer value into the parcel at the current dataPosition().
void writeLong (int64_t val)
Write a long integer value into the parcel at the current dataPosition().
void writeFloat (float val)
Write an float value into the parcel at the current dataPosition().
void writeDouble (double val)
Write an double value into the parcel at the current dataPosition().
void writeString (const gaia::base::String &str)
Write an String into the parcel at the current dataPosition().
void read (void *outData, size_t len) const
read raw data from the parcel to outData at the current dataPosition().
void write (const void *data, size_t len)
Write raw data into the parcel at the current dataPosition(), growing dataCapacity() if needed.
gaia::base::Array< bool > createBooleanArray () const
Read and return a bool array from the parcel.
gaia::base::Array< byte_t > createByteArray () const
Read and return a byte_t array from the parcel.
gaia::base::Array< int32_t > createIntArray () const
Read and return an int32_t array from the parcel.
gaia::base::Array< int64_t > createLongArray () const
Read and return an int64_t array from the parcel.
gaia::base::Array< float > createFloatArray () const
Read and return a float array from the parcel.
gaia::base::Array< double > createDoubleArray () const
Read and return a double array from the parcel.
gaia::base::Array
< gaia::base::String > createStringArray () const
Read and return a String array from the parcel.
void readBooleanArray (gaia::base::Array< bool > *val)
Read a bool array from the parcel and copy it into the given array.
void readByteArray (gaia::base::Array< byte_t > *val)
Read a byte_t array from the parcel and copy it into the given array.
void readIntArray (gaia::base::Array< int32_t > *val)
Read an int32_t array from the parcel and copy it into the given array.
void readLongArray (gaia::base::Array< int64_t > *val)
Read an int64_t array from the parcel and copy it into the given array.
void readFloatArray (gaia::base::Array< float > *val)
Read a float array from the parcel and copy it into the given array.
void readDoubleArray (gaia::base::Array< double > *val)
Read a double array from the parcel and copy it into the given array.
void readStringArray (gaia::base::Array< gaia::base::String > *val)
Read a String array from the parcel and copy it into the given array.
void writeBooleanArray (const gaia::base::Array< bool > &val)
Write a bool array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void writeByteArray (const gaia::base::Array< byte_t > &val)
Write a byte_t array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void writeIntArray (const gaia::base::Array< int32_t > &val)
Write an int32_t array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void writeLongArray (const gaia::base::Array< int64_t > &val)
Write an int64_t array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void writeFloatArray (const gaia::base::Array< float > &val)
Write a float array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void writeDoubleArray (const gaia::base::Array< double > &val)
Write a double array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void writeStringArray (const gaia::base::Array< gaia::base::String > &val)
Write a String array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
gaia::base::Vector
< gaia::base::String > createStringVector () const
Read and return a Vector containing String objects from the parcel that was written with writeStringVector() at the current dataPosition().
void readStringVector (gaia::base::Vector< gaia::base::String > *vec) const
Read into the given Vector items String objects that were written with writeStringVector() at the current dataPosition().
void writeStringVector (const gaia::base::Vector< gaia::base::String > &vec)
Flatten a Vector containing String objects into the parcel, at the current dataPosition() and growing dataCapacity() if needed.
template<typename T >
gaia::base::Vector< T * > * createTypedVectorN () const
Read and return a Vector containing a particular object type from the parcel that was written with writeTypedVector() at the current dataPosition().
template<typename T >
void readTypedVector (gaia::base::Vector< T * > *vec) const
Read into the given Vector items containing a particular object type that were written with writeTypedVector() at the current dataPosition().
template<typename T >
void writeTypedVector (const gaia::base::Vector< T * > *vec)
Flatten a Vector containing a particular object type into the parcel, at the current dataPosition() and growing dataCapacity() if needed.
bool enforceInterface (const gaia::base::String &interfaceName) const
Read and check an IBinder interface token in the parcel at the current dataPosition().
void writeInterfaceToken (const gaia::base::String &interfaceName)
Store an IBinder interface token in the parcel at the current dataPosition().
gaia::core::IBinder * readStrongBinderN () const
Read an object from the parcel at the current dataPosition().
gaia::core::IBinder * readStrongBinder () const
void writeStrongBinder (gaia::core::IBinder *val)
Write an object into the parcel at the current dataPosition().
void writeFileDescriptor (const gaia::storage::FileDescriptor &fd)
Write a FileDescriptor into the parcel at the current dataPosition(), growing dataCapacity() if needed.
gaia::storage::ParcelFileDescriptor * readFileDescriptorN () const
Read a FileDescriptor from the parcel at the current dataPosition().
Private Member Functions
Parcel (const Parcel &o)
Parcel & operator= (const Parcel &o)
Private Attributes
Data * mpData
Detailed Description
Container for a message (data and object references)
A Parcel can contain both flattened data that will be unflattened on the other side of the IPC (using the various methods here for writing specific types)
 //Getter and setter function
 Parcel *pParcel = new Parcel();
 int32_t i = 2, ri;
 bool b = true, rb;
 //write primitive data to Parcel
 pParcel->write(&i, sizeof(i));
 pParcel->write(&b, sizeof(b));
 //read primitive data from Parcel
 pParcel->setDataPosition(0);
 pParcel->read(&ri, sizeof(ri));
 pParcel->read(&rb sizeof(rb));
Definition at line 50 of file Parcel.h.
Constructor & Destructor Documentation
gaia::core::Parcel::Parcel ()
Create an empty Parcel.
gaia::core::Parcel::~Parcel ()
Destructor.
gaia::core::Parcel::Parcel (const Parcel & o) [private]
Member Function Documentation
gaia::base::Array<bool> gaia::core::Parcel::createBooleanArray () const
Read and return a bool array from the parcel.
gaia::base::Array<byte_t> gaia::core::Parcel::createByteArray () const
Read and return a byte_t array from the parcel.
gaia::base::Array<double> gaia::core::Parcel::createDoubleArray () const
Read and return a double array from the parcel.
gaia::base::Array<float> gaia::core::Parcel::createFloatArray () const
Read and return a float array from the parcel.
gaia::base::Array<int32_t> gaia::core::Parcel::createIntArray () const
Read and return an int32_t array from the parcel.
gaia::base::Array<int64_t> gaia::core::Parcel::createLongArray () const
Read and return an int64_t array from the parcel.
gaia::base::Array<gaia::base::String> gaia::core::Parcel::createStringArray () const
Read and return a String array from the parcel.
gaia::base::Vector<gaia::base::String> gaia::core::Parcel::createStringVector () const
Read and return a Vector containing String objects from the parcel that was written with writeStringVector() at the current dataPosition().
template<typename T > gaia::base::Vector< T * > * gaia::core::Parcel::createTypedVectorN () const
Read and return a Vector containing a particular object type from the parcel that was written with writeTypedVector() at the current dataPosition().
Returns NULL if the previously written object was NULL. The Vector must have previously been written via writeTypedVector() with the same object type.
Definition at line 380 of file Parcel.h.
References gaia::base::Vector< TYPE >::append(), and readInt().
size_t gaia::core::Parcel::dataAvail () const
Returns the amount of data remaining to be read from the parcel.
That is, dataSize()-dataPosition().
size_t gaia::core::Parcel::dataPosition () const
Returns the current position in the parcel data.
size_t gaia::core::Parcel::dataSize () const
Returns the total amount of data contained in the parcel.
bool gaia::core::Parcel::enforceInterface (const gaia::base::String & interfaceName) const
Read and check an IBinder interface token in the parcel at the current dataPosition().
This is used to validate that the marshalled transaction is intended for the target interface.
Parcel& gaia::core::Parcel::operator= (const Parcel & o) [private]
void gaia::core::Parcel::read (void * outData, size_t len) const
read raw data from the parcel to outData at the current dataPosition().
Parameters:
outData raw data pointer
len data's length
void gaia::core::Parcel::readBooleanArray (gaia::base::Array< bool > * val)
Read a bool array from the parcel and copy it into the given array.
byte_t gaia::core::Parcel::readByte () const
Read a byte value from the parcel at the current dataPosition().
void gaia::core::Parcel::readByteArray (gaia::base::Array< byte_t > * val)
Read a byte_t array from the parcel and copy it into the given array.
double gaia::core::Parcel::readDouble () const
Read an double value from the parcel at the current dataPosition(),.
void gaia::core::Parcel::readDoubleArray (gaia::base::Array< double > * val)
Read a double array from the parcel and copy it into the given array.
gaia::storage::ParcelFileDescriptor* gaia::core::Parcel::readFileDescriptorN () const
Read a FileDescriptor from the parcel at the current dataPosition().
float gaia::core::Parcel::readFloat () const
Read an Float value from the parcel at the current dataPosition(),.
void gaia::core::Parcel::readFloatArray (gaia::base::Array< float > * val)
Read a float array from the parcel and copy it into the given array.
int32_t gaia::core::Parcel::readInt () const
Read an integer value from the parcel at the current dataPosition().
Referenced by createTypedVectorN(), and readTypedVector().
void gaia::core::Parcel::readIntArray (gaia::base::Array< int32_t > * val)
Read an int32_t array from the parcel and copy it into the given array.
int64_t gaia::core::Parcel::readLong () const
Read a long integer value from the parcel at the current dataPosition(),.
void gaia::core::Parcel::readLongArray (gaia::base::Array< int64_t > * val)
Read an int64_t array from the parcel and copy it into the given array.
gaia::base::String gaia::core::Parcel::readString () const
Read an String from the parcel at the current dataPosition(),.
void gaia::core::Parcel::readStringArray (gaia::base::Array< gaia::base::String > * val)
Read a String array from the parcel and copy it into the given array.
void gaia::core::Parcel::readStringVector (gaia::base::Vector< gaia::base::String > * vec) const
Read into the given Vector items String objects that were written with writeStringVector() at the current dataPosition().
gaia::core::IBinder* gaia::core::Parcel::readStrongBinder () const
gaia::core::IBinder* gaia::core::Parcel::readStrongBinderN () const
Read an object from the parcel at the current dataPosition().
template<typename T > void gaia::core::Parcel::readTypedVector (gaia::base::Vector< T * > * vec) const
Read into the given Vector items containing a particular object type that were written with writeTypedVector() at the current dataPosition().
The Vector must have previously been written via writeTypedVector with the same object type.
Definition at line 399 of file Parcel.h.
References gaia::base::Vector< TYPE >::append(), readInt(), gaia::base::Vector< TYPE >::removeAt(), gaia::base::Vector< TYPE >::replaceAt(), and gaia::base::Vector< TYPE >::size().
void gaia::core::Parcel::setDataPosition (size_t pos) const
Move the current read/write position in the parcel.
Parameters:
pos New offset in the parcel; must be between 0 and dataSize.
void gaia::core::Parcel::setDataSize (size_t size)
Change the amount of data in the parcel.
Can be either smaller or larger than the current size. If larger than the current capacity, more memory will be allocated.
Parameters:
size The new number of bytes in the Parcel.
void gaia::core::Parcel::write (const void * data, size_t len)
Write raw data into the parcel at the current dataPosition(), growing dataCapacity() if needed.
Parameters:
data raw data pointer
len data's length
void gaia::core::Parcel::writeBooleanArray (const gaia::base::Array< bool > & val)
Write a bool array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeByte (byte_t val)
Write a byte value into the parcel at current dataPosition().
void gaia::core::Parcel::writeByteArray (const gaia::base::Array< byte_t > & val)
Write a byte_t array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeDouble (double val)
Write an double value into the parcel at the current dataPosition().
void gaia::core::Parcel::writeDoubleArray (const gaia::base::Array< double > & val)
Write a double array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeFileDescriptor (const gaia::storage::FileDescriptor & fd)
Write a FileDescriptor into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeFloat (float val)
Write an float value into the parcel at the current dataPosition().
void gaia::core::Parcel::writeFloatArray (const gaia::base::Array< float > & val)
Write a float array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeInt (int32_t val)
Write an integer value into the parcel at the current dataPosition().
Referenced by writeTypedVector().
void gaia::core::Parcel::writeIntArray (const gaia::base::Array< int32_t > & val)
Write an int32_t array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeInterfaceToken (const gaia::base::String & interfaceName)
Store an IBinder interface token in the parcel at the current dataPosition().
This is used to validate that the marshalled transaction is intended for the target interface.
void gaia::core::Parcel::writeLong (int64_t val)
Write a long integer value into the parcel at the current dataPosition().
void gaia::core::Parcel::writeLongArray (const gaia::base::Array< int64_t > & val)
Write an int64_t array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeString (const gaia::base::String & str)
Write an String into the parcel at the current dataPosition().
void gaia::core::Parcel::writeStringArray (const gaia::base::Array< gaia::base::String > & val)
Write a String array into the parcel at the current dataPosition(), growing dataCapacity() if needed.
void gaia::core::Parcel::writeStringVector (const gaia::base::Vector< gaia::base::String > & vec)
Flatten a Vector containing String objects into the parcel, at the current dataPosition() and growing dataCapacity() if needed.
They can later be retrieved with createStringVector() or readStringVector().
void gaia::core::Parcel::writeStrongBinder (gaia::core::IBinder * val)
Write an object into the parcel at the current dataPosition().
template<typename T > void gaia::core::Parcel::writeTypedVector (const gaia::base::Vector< T * > * vec)
Flatten a Vector containing a particular object type into the parcel, at the current dataPosition() and growing dataCapacity() if needed.
The type of the objects in the list must be one that implements Parcelable.
Definition at line 423 of file Parcel.h.
References gaia::base::Vector< TYPE >::size(), and writeInt().
Member Data Documentation
Data* gaia::core::Parcel::mpData [private]
Definition at line 375 of file Parcel.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Parcel.h