gaia::core::GLES20 Class Reference
gaia::core::GLES20 Class Reference
#include <GLES20.h>
Static Public Member Functions
static void glActiveTexture (int32_t texture)
static void glAttachShader (int32_t program, int32_t shader)
static void glBindAttribLocation (int32_t program, int32_t index, const gaia::base::String &name)
static void glBindBuffer (int32_t target, int32_t buffer)
static void glBindFramebuffer (int32_t target, int32_t framebuffer)
static void glBindRenderbuffer (int32_t target, int32_t renderbuffer)
static void glBindTexture (int32_t target, int32_t texture)
static void glBlendColor (float red, float green, float blue, float alpha)
static void glBlendEquation (int32_t mode)
static void glBlendEquationSeparate (int32_t modeRGB, int32_t modeAlpha)
static void glBlendFunc (int32_t sfactor, int32_t dfactor)
static void glBlendFuncSeparate (int32_t srcRGB, int32_t dstRGB, int32_t srcAlpha, int32_t dstAlpha)
static void glBufferData (int32_t target, int32_t size, void *data_buf, int32_t usage)
static void glBufferSubData (int32_t target, int32_t offset, int32_t size, const gaia::base::Array< int32_t > &data_buf)
static int32_t glCheckFramebufferStatus (int32_t target)
static void glClear (int32_t mask)
static void glClearColor (float red, float green, float blue, float alpha)
static void glClearDepthf (float depth)
static void glClearStencil (int32_t s)
static void glColorMask (bool red, bool green, bool blue, bool alpha)
static void glCompileShader (int32_t shader)
static void glCompressedTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const gaia::base::ByteArray &data)
static void glCompressedTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t imageSize, const gaia::base::ByteArray &data)
static void glCopyTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border)
static void glCopyTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height)
static int32_t glCreateProgram ()
static int32_t glCreateShader (int32_t type)
static void glCullFace (int32_t mode)
static void glDeleteBuffers (int32_t n, const gaia::base::Array< uint32_t > &buffers, int32_t offset)
static void glDeleteBuffers (int32_t n, const gaia::base::Array< uint32_t > &buffers)
static void glDeleteFramebuffers (int32_t n, const gaia::base::Array< uint32_t > &buffers, int32_t offset)
static void glDeleteFramebuffers (int32_t n, const gaia::base::Array< uint32_t > &buffers)
static void glDeleteProgram (int32_t program)
static void glDeleteRenderbuffers (int32_t n, const gaia::base::Array< uint32_t > &buffers, int32_t offset)
static void glDeleteRenderbuffers (int32_t n, const gaia::base::Array< uint32_t > &buffers)
static void glDeleteShader (int32_t shader)
static void glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > &buffers, int32_t offset)
static void glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > &buffers)
static void glDepthFunc (int32_t func)
static void glDepthMask (bool flag)
static void glDepthRangef (float zNear, float zFar)
static void glDetachShader (uint32_t program, uint32_t shader)
static void glDisable (int32_t cap)
static void glDisableVertexAttribArray (int32_t index)
static void glDrawArrays (int32_t mode, int32_t first, int32_t count)
template<typename TYPE >
static void glDrawElements (int32_t mode, int32_t count, int32_t type, const gaia::base::Array< TYPE > &indices)
static void glEnable (int32_t cap)
static void glEnableVertexAttribArray (uint32_t index)
static void glFinish ()
static void glFlush ()
static void glFramebufferRenderbuffer (int32_t target, int32_t attachment, int32_t renderbuffertarget, int32_t renderbuffer)
static void glFramebufferTexture2D (int32_t target, int32_t attachment, int32_t textarget, int32_t texture, int32_t level)
static void glFrontFace (int32_t mode)
static void glGenBuffers (int32_t n, gaia::base::Array< uint32_t > *buffers, int32_t offset)
static void glGenBuffers (int32_t n, gaia::base::Array< uint32_t > *buffers)
static void glGenerateMipmap (int32_t target)
static void glGenFramebuffers (int32_t n, gaia::base::Array< uint32_t > *buffers, int32_t offset)
static void glGenFramebuffers (int32_t n, gaia::base::Array< uint32_t > *buffers)
static void glGenRenderbuffers (int32_t n, gaia::base::Array< uint32_t > *buffers, int32_t offset)
static void glGenRenderbuffers (int32_t n, gaia::base::Array< uint32_t > *buffers)
static void glGenTextures (int32_t n, gaia::base::Array< uint32_t > *textures, int32_t offset)
static void glGenTextures (int32_t n, gaia::base::Array< uint32_t > *textures)
static void glGetActiveAttrib (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > *length, int32_t lengthOffset, gaia::base::Array< int32_t > *size, int32_t sizeOffset, gaia::base::Array< uint32_t > *type, int32_t typeOffset, gaia::base::ByteArray *name, int32_t nameOffset)
static void glGetActiveAttrib (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > *length, gaia::base::Array< int32_t > *size, gaia::base::Array< uint32_t > *type, byte_t name)
static void glGetActiveUniform (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > *length, int32_t lengthOffset, gaia::base::Array< int32_t > *size, int32_t sizeOffset, gaia::base::Array< uint32_t > *type, int32_t typeOffset, gaia::base::ByteArray *name, int32_t nameOffset)
static void glGetActiveUniform (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > *length, gaia::base::Array< int32_t > *size, gaia::base::Array< uint32_t > *type, byte_t name)
static void glGetAttachedShaders (uint32_t program, int32_t maxcount, gaia::base::Array< int32_t > *count, int32_t countOffset, gaia::base::Array< uint32_t > *shaders, int32_t shadersOffset)
static void glGetAttachedShaders (uint32_t program, int32_t maxcount, gaia::base::Array< int32_t > *count, gaia::base::Array< uint32_t > *shaders)
static int32_t glGetAttribLocation (int32_t program, const gaia::base::String &name)
static void glGetBooleanv (int32_t pname, gaia::base::ByteArray *params, int32_t offset)
static void glGetBooleanv (int32_t pname, gaia::base::ByteArray *params)
static void glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
static int32_t glGetError ()
static void glGetFloatv (int32_t pname, gaia::base::Array< float > *params, int32_t offset)
static void glGetFloatv (int32_t pname, gaia::base::Array< float > *params)
static void glGetFramebufferAttachmentParameteriv (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetFramebufferAttachmentParameteriv (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetProgramiv (uint32_t program, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetProgramiv (uint32_t program, int32_t pname, gaia::base::Array< int32_t > *params)
static gaia::base::String glGetProgramInfoLog (uint32_t program)
static void glGetRenderbufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetRenderbufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetShaderiv (int32_t shader, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetShaderiv (int32_t shader, int32_t pname, gaia::base::Array< int32_t > *params)
static gaia::base::String glGetShaderInfoLog (int32_t shader)
static void glGetShaderPrecisionFormat (int32_t shadertype, int32_t precisiontype, gaia::base::Array< int32_t > *range, int32_t rangeOffset, gaia::base::Array< int32_t > *precision, int32_t precisionOffset)
static void glGetShaderPrecisionFormat (int32_t shadertype, int32_t precisiontype, gaia::base::Array< int32_t > *range, gaia::base::Array< int32_t > *precision)
static void glGetShaderSource (int32_t shader, int32_t bufsize, gaia::base::Array< int32_t > *length, int32_t lengthOffset, gaia::base::ByteArray *source, int32_t sourceOffset)
static void glGetShaderSource (int32_t shader, int32_t bufsize, gaia::base::Array< int32_t > *length, byte_t source)
static gaia::base::String glGetString (int32_t name)
static void glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > *params, int32_t offset)
static void glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > *params)
static void glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetUniformfv (int32_t program, int32_t location, gaia::base::Array< float > *params, int32_t offset)
static void glGetUniformfv (int32_t program, int32_t location, gaia::base::Array< float > *params)
static void glGetUniformiv (int32_t program, int32_t location, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetUniformiv (int32_t program, int32_t location, gaia::base::Array< int32_t > *params)
static int32_t glGetUniformLocation (int32_t program, const gaia::base::String &name)
static void glGetVertexAttribfv (int32_t index, int32_t pname, gaia::base::Array< float > *params, int32_t offset)
static void glGetVertexAttribfv (int32_t index, int32_t pname, gaia::base::Array< float > *params)
static void glGetVertexAttribiv (int32_t index, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetVertexAttribiv (int32_t index, int32_t pname, gaia::base::Array< int32_t > *params)
static void glHint (int32_t target, int32_t mode)
static bool glIsBuffer (int32_t buffer)
static bool glIsEnabled (int32_t cap)
static bool glIsFramebuffer (int32_t framebuffer)
static bool glIsProgram (int32_t program)
static bool glIsRenderbuffer (int32_t renderbuffer)
static bool glIsShader (int32_t shader)
static bool glIsTexture (int32_t texture)
static void glLineWidth (float width)
static void glLinkProgram (int32_t program)
static void glPixelStorei (int32_t pname, int32_t param)
static void glPolygonOffset (float factor, float units)
static void glReadPixels (int32_t x, int32_t y, int32_t width, int32_t height, int32_t format, int32_t type, gaia::base::ByteArray *pixels)
static void glReleaseShaderCompiler ()
static void glRenderbufferStorage (int32_t target, int32_t internalformat, int32_t width, int32_t height)
static void glSampleCoverage (float value, bool invert)
static void glScissor (int32_t x, int32_t y, int32_t width, int32_t height)
static void glShaderBinary (int32_t n, uint32_t *shaders, int32_t offset, int32_t binaryformat, void *binary, int32_t length)
static void glShaderBinary (int32_t n, uint32_t *shaders, int32_t binaryformat, void *binary, int32_t length)
static void glShaderSource (int32_t shader, const gaia::base::String &string)
static void glStencilFunc (int32_t func, int32_t ref, int32_t mask)
static void glStencilFuncSeparate (int32_t face, int32_t func, int32_t ref, int32_t mask)
static void glStencilMask (int32_t mask)
static void glStencilMaskSeparate (int32_t face, int32_t mask)
static void glStencilOp (int32_t fail, int32_t zfail, int32_t zpass)
static void glStencilOpSeparate (int32_t face, int32_t fail, int32_t zfail, int32_t zpass)
template<typename TYPE >
static void glTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t format, int32_t type, const gaia::base::Array< TYPE > &pixels)
static void glTexParameterf (int32_t target, int32_t pname, float param)
static void glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params)
static void glTexParameteri (int32_t target, int32_t pname, int32_t param)
static void glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t type, const gaia::base::ByteArray &pixels)
static void glUniform1f (int32_t location, float x)
static void glUniform1fv (int32_t location, int32_t count, const gaia::base::Array< float > &v, int32_t offset)
static void glUniform1fv (int32_t location, int32_t count, const gaia::base::Array< float > &v)
static void glUniform1i (int32_t location, int32_t x)
static void glUniform1iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v, int32_t offset)
static void glUniform1iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v)
static void glUniform2f (int32_t location, float x, float y)
static void glUniform2fv (int32_t location, int32_t count, const gaia::base::Array< float > &v, int32_t offset)
static void glUniform2fv (int32_t location, int32_t count, const gaia::base::Array< float > &v)
static void glUniform2i (int32_t location, int32_t x, int32_t y)
static void glUniform2iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v, int32_t offset)
static void glUniform2iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v)
static void glUniform3f (int32_t location, float x, float y, float z)
static void glUniform3fv (int32_t location, int32_t count, const gaia::base::Array< float > &v, int32_t offset)
static void glUniform3fv (int32_t location, int32_t count, const gaia::base::Array< float > &v)
static void glUniform3i (int32_t location, int32_t x, int32_t y, int32_t z)
static void glUniform3iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v, int32_t offset)
static void glUniform3iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v)
static void glUniform4f (int32_t location, float x, float y, float z, float w)
static void glUniform4fv (int32_t location, int32_t count, const gaia::base::Array< float > &v, int32_t offset)
static void glUniform4fv (int32_t location, int32_t count, const gaia::base::Array< float > &v)
static void glUniform4i (int32_t location, int32_t x, int32_t y, int32_t z, int32_t w)
static void glUniform4iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v, int32_t offset)
static void glUniform4iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > &v)
static void glUniformMatrix2fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > &value, int32_t offset)
static void glUniformMatrix2fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > &value)
static void glUniformMatrix3fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > &value, int32_t offset)
static void glUniformMatrix3fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > &value)
static void glUniformMatrix4fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > &value, int32_t offset)
static void glUniformMatrix4fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > &value)
static void glUseProgram (int32_t program)
static void glValidateProgram (int32_t program)
static void glVertexAttrib1f (int32_t indx, float x)
static void glVertexAttrib1fv (int32_t indx, const gaia::base::Array< float > &value, int32_t offset)
static void glVertexAttrib1fv (int32_t indx, const gaia::base::Array< float > &value)
static void glVertexAttrib2f (int32_t indx, float x, float y)
static void glVertexAttrib2fv (int32_t indx, const gaia::base::Array< float > &value, int32_t offset)
static void glVertexAttrib2fv (int32_t indx, const gaia::base::Array< float > &value)
static void glVertexAttrib3f (int32_t indx, float x, float y, float z)
static void glVertexAttrib3fv (int32_t indx, const gaia::base::Array< float > &value, int32_t offset)
static void glVertexAttrib3fv (int32_t indx, const gaia::base::Array< float > &value)
static void glVertexAttrib4f (int32_t indx, float x, float y, float z, float w)
static void glVertexAttrib4fv (int32_t indx, const gaia::base::Array< float > &value, int32_t offset)
static void glVertexAttrib4fv (int32_t indx, const gaia::base::Array< float > &value)
template<typename TYPE >
static void glVertexAttribPointer (int indx, int size, int type, bool normalized, int stride, const gaia::base::Array< TYPE > &pointer, int offset)
static void glViewport (int x, int y, int width, int height)
static int getNumCompressedTextureFormats ()
Private Member Functions
DISALLOW_COPY_AND_ASSIGN (GLES20)
Detailed Description
Definition at line 16 of file GLES20.h.
Member Function Documentation
gaia::core::GLES20::DISALLOW_COPY_AND_ASSIGN (GLES20) [private]
static int gaia::core::GLES20::getNumCompressedTextureFormats () [static]
static void gaia::core::GLES20::glActiveTexture (int32_t texture) [static]
static void gaia::core::GLES20::glAttachShader (int32_t program, int32_t shader) [static]
static void gaia::core::GLES20::glBindAttribLocation (int32_t program, int32_t index, const gaia::base::String & name) [static]
static void gaia::core::GLES20::glBindBuffer (int32_t target, int32_t buffer) [static]
static void gaia::core::GLES20::glBindFramebuffer (int32_t target, int32_t framebuffer) [static]
static void gaia::core::GLES20::glBindRenderbuffer (int32_t target, int32_t renderbuffer) [static]
static void gaia::core::GLES20::glBindTexture (int32_t target, int32_t texture) [static]
static void gaia::core::GLES20::glBlendColor (float red, float green, float blue, float alpha) [static]
static void gaia::core::GLES20::glBlendEquation (int32_t mode) [static]
static void gaia::core::GLES20::glBlendEquationSeparate (int32_t modeRGB, int32_t modeAlpha) [static]
static void gaia::core::GLES20::glBlendFunc (int32_t sfactor, int32_t dfactor) [static]
static void gaia::core::GLES20::glBlendFuncSeparate (int32_t srcRGB, int32_t dstRGB, int32_t srcAlpha, int32_t dstAlpha) [static]
static void gaia::core::GLES20::glBufferData (int32_t target, int32_t size, void * data_buf, int32_t usage) [static]
static void gaia::core::GLES20::glBufferSubData (int32_t target, int32_t offset, int32_t size, const gaia::base::Array< int32_t > & data_buf) [static]
static int32_t gaia::core::GLES20::glCheckFramebufferStatus (int32_t target) [static]
static void gaia::core::GLES20::glClear (int32_t mask) [static]
static void gaia::core::GLES20::glClearColor (float red, float green, float blue, float alpha) [static]
static void gaia::core::GLES20::glClearDepthf (float depth) [static]
static void gaia::core::GLES20::glClearStencil (int32_t s) [static]
static void gaia::core::GLES20::glColorMask (bool red, bool green, bool blue, bool alpha) [static]
static void gaia::core::GLES20::glCompileShader (int32_t shader) [static]
static void gaia::core::GLES20::glCompressedTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const gaia::base::ByteArray & data) [static]
static void gaia::core::GLES20::glCompressedTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t imageSize, const gaia::base::ByteArray & data) [static]
static void gaia::core::GLES20::glCopyTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border) [static]
static void gaia::core::GLES20::glCopyTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height) [static]
static int32_t gaia::core::GLES20::glCreateProgram () [static]
static int32_t gaia::core::GLES20::glCreateShader (int32_t type) [static]
static void gaia::core::GLES20::glCullFace (int32_t mode) [static]
static void gaia::core::GLES20::glDeleteBuffers (int32_t n, const gaia::base::Array< uint32_t > & buffers, int32_t offset) [static]
static void gaia::core::GLES20::glDeleteBuffers (int32_t n, const gaia::base::Array< uint32_t > & buffers) [static]
static void gaia::core::GLES20::glDeleteFramebuffers (int32_t n, const gaia::base::Array< uint32_t > & buffers) [static]
static void gaia::core::GLES20::glDeleteFramebuffers (int32_t n, const gaia::base::Array< uint32_t > & buffers, int32_t offset) [static]
static void gaia::core::GLES20::glDeleteProgram (int32_t program) [static]
static void gaia::core::GLES20::glDeleteRenderbuffers (int32_t n, const gaia::base::Array< uint32_t > & buffers, int32_t offset) [static]
static void gaia::core::GLES20::glDeleteRenderbuffers (int32_t n, const gaia::base::Array< uint32_t > & buffers) [static]
static void gaia::core::GLES20::glDeleteShader (int32_t shader) [static]
static void gaia::core::GLES20::glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > & buffers, int32_t offset) [static]
static void gaia::core::GLES20::glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > & buffers) [static]
static void gaia::core::GLES20::glDepthFunc (int32_t func) [static]
static void gaia::core::GLES20::glDepthMask (bool flag) [static]
static void gaia::core::GLES20::glDepthRangef (float zNear, float zFar) [static]
static void gaia::core::GLES20::glDetachShader (uint32_t program, uint32_t shader) [static]
static void gaia::core::GLES20::glDisable (int32_t cap) [static]
static void gaia::core::GLES20::glDisableVertexAttribArray (int32_t index) [static]
static void gaia::core::GLES20::glDrawArrays (int32_t mode, int32_t first, int32_t count) [static]
template<typename TYPE > static void gaia::core::GLES20::glDrawElements (int32_t mode, int32_t count, int32_t type, const gaia::base::Array< TYPE > & indices) [inline, static]
Definition at line 119 of file GLES20.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES20::glEnable (int32_t cap) [static]
static void gaia::core::GLES20::glEnableVertexAttribArray (uint32_t index) [static]
static void gaia::core::GLES20::glFinish () [static]
static void gaia::core::GLES20::glFlush () [static]
static void gaia::core::GLES20::glFramebufferRenderbuffer (int32_t target, int32_t attachment, int32_t renderbuffertarget, int32_t renderbuffer) [static]
static void gaia::core::GLES20::glFramebufferTexture2D (int32_t target, int32_t attachment, int32_t textarget, int32_t texture, int32_t level) [static]
static void gaia::core::GLES20::glFrontFace (int32_t mode) [static]
static void gaia::core::GLES20::glGenBuffers (int32_t n, gaia::base::Array< uint32_t > * buffers, int32_t offset) [static]
static void gaia::core::GLES20::glGenBuffers (int32_t n, gaia::base::Array< uint32_t > * buffers) [static]
static void gaia::core::GLES20::glGenerateMipmap (int32_t target) [static]
static void gaia::core::GLES20::glGenFramebuffers (int32_t n, gaia::base::Array< uint32_t > * buffers, int32_t offset) [static]
static void gaia::core::GLES20::glGenFramebuffers (int32_t n, gaia::base::Array< uint32_t > * buffers) [static]
static void gaia::core::GLES20::glGenRenderbuffers (int32_t n, gaia::base::Array< uint32_t > * buffers, int32_t offset) [static]
static void gaia::core::GLES20::glGenRenderbuffers (int32_t n, gaia::base::Array< uint32_t > * buffers) [static]
static void gaia::core::GLES20::glGenTextures (int32_t n, gaia::base::Array< uint32_t > * textures, int32_t offset) [static]
static void gaia::core::GLES20::glGenTextures (int32_t n, gaia::base::Array< uint32_t > * textures) [static]
static void gaia::core::GLES20::glGetActiveAttrib (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > * length, gaia::base::Array< int32_t > * size, gaia::base::Array< uint32_t > * type, byte_t name) [static]
static void gaia::core::GLES20::glGetActiveAttrib (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > * length, int32_t lengthOffset, gaia::base::Array< int32_t > * size, int32_t sizeOffset, gaia::base::Array< uint32_t > * type, int32_t typeOffset, gaia::base::ByteArray * name, int32_t nameOffset) [static]
static void gaia::core::GLES20::glGetActiveUniform (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > * length, int32_t lengthOffset, gaia::base::Array< int32_t > * size, int32_t sizeOffset, gaia::base::Array< uint32_t > * type, int32_t typeOffset, gaia::base::ByteArray * name, int32_t nameOffset) [static]
static void gaia::core::GLES20::glGetActiveUniform (int32_t program, int32_t index, int32_t bufsize, gaia::base::Array< int32_t > * length, gaia::base::Array< int32_t > * size, gaia::base::Array< uint32_t > * type, byte_t name) [static]
static void gaia::core::GLES20::glGetAttachedShaders (uint32_t program, int32_t maxcount, gaia::base::Array< int32_t > * count, int32_t countOffset, gaia::base::Array< uint32_t > * shaders, int32_t shadersOffset) [static]
static void gaia::core::GLES20::glGetAttachedShaders (uint32_t program, int32_t maxcount, gaia::base::Array< int32_t > * count, gaia::base::Array< uint32_t > * shaders) [static]
static int32_t gaia::core::GLES20::glGetAttribLocation (int32_t program, const gaia::base::String & name) [static]
static void gaia::core::GLES20::glGetBooleanv (int32_t pname, gaia::base::ByteArray * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetBooleanv (int32_t pname, gaia::base::ByteArray * params) [static]
static void gaia::core::GLES20::glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static int32_t gaia::core::GLES20::glGetError () [static]
static void gaia::core::GLES20::glGetFloatv (int32_t pname, gaia::base::Array< float > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetFloatv (int32_t pname, gaia::base::Array< float > * params) [static]
static void gaia::core::GLES20::glGetFramebufferAttachmentParameteriv (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetFramebufferAttachmentParameteriv (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES20::glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > * params) [static]
static gaia::base::String gaia::core::GLES20::glGetProgramInfoLog (uint32_t program) [static]
static void gaia::core::GLES20::glGetProgramiv (uint32_t program, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetProgramiv (uint32_t program, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES20::glGetRenderbufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetRenderbufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static gaia::base::String gaia::core::GLES20::glGetShaderInfoLog (int32_t shader) [static]
static void gaia::core::GLES20::glGetShaderiv (int32_t shader, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetShaderiv (int32_t shader, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES20::glGetShaderPrecisionFormat (int32_t shadertype, int32_t precisiontype, gaia::base::Array< int32_t > * range, int32_t rangeOffset, gaia::base::Array< int32_t > * precision, int32_t precisionOffset) [static]
static void gaia::core::GLES20::glGetShaderPrecisionFormat (int32_t shadertype, int32_t precisiontype, gaia::base::Array< int32_t > * range, gaia::base::Array< int32_t > * precision) [static]
static void gaia::core::GLES20::glGetShaderSource (int32_t shader, int32_t bufsize, gaia::base::Array< int32_t > * length, int32_t lengthOffset, gaia::base::ByteArray * source, int32_t sourceOffset) [static]
static void gaia::core::GLES20::glGetShaderSource (int32_t shader, int32_t bufsize, gaia::base::Array< int32_t > * length, byte_t source) [static]
static gaia::base::String gaia::core::GLES20::glGetString (int32_t name) [static]
static void gaia::core::GLES20::glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > * params) [static]
static void gaia::core::GLES20::glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES20::glGetUniformfv (int32_t program, int32_t location, gaia::base::Array< float > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetUniformfv (int32_t program, int32_t location, gaia::base::Array< float > * params) [static]
static void gaia::core::GLES20::glGetUniformiv (int32_t program, int32_t location, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetUniformiv (int32_t program, int32_t location, gaia::base::Array< int32_t > * params) [static]
static int32_t gaia::core::GLES20::glGetUniformLocation (int32_t program, const gaia::base::String & name) [static]
static void gaia::core::GLES20::glGetVertexAttribfv (int32_t index, int32_t pname, gaia::base::Array< float > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetVertexAttribfv (int32_t index, int32_t pname, gaia::base::Array< float > * params) [static]
static void gaia::core::GLES20::glGetVertexAttribiv (int32_t index, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES20::glGetVertexAttribiv (int32_t index, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES20::glHint (int32_t target, int32_t mode) [static]
static bool gaia::core::GLES20::glIsBuffer (int32_t buffer) [static]
static bool gaia::core::GLES20::glIsEnabled (int32_t cap) [static]
static bool gaia::core::GLES20::glIsFramebuffer (int32_t framebuffer) [static]
static bool gaia::core::GLES20::glIsProgram (int32_t program) [static]
static bool gaia::core::GLES20::glIsRenderbuffer (int32_t renderbuffer) [static]
static bool gaia::core::GLES20::glIsShader (int32_t shader) [static]
static bool gaia::core::GLES20::glIsTexture (int32_t texture) [static]
static void gaia::core::GLES20::glLineWidth (float width) [static]
static void gaia::core::GLES20::glLinkProgram (int32_t program) [static]
static void gaia::core::GLES20::glPixelStorei (int32_t pname, int32_t param) [static]
static void gaia::core::GLES20::glPolygonOffset (float factor, float units) [static]
static void gaia::core::GLES20::glReadPixels (int32_t x, int32_t y, int32_t width, int32_t height, int32_t format, int32_t type, gaia::base::ByteArray * pixels) [static]
static void gaia::core::GLES20::glReleaseShaderCompiler () [static]
static void gaia::core::GLES20::glRenderbufferStorage (int32_t target, int32_t internalformat, int32_t width, int32_t height) [static]
static void gaia::core::GLES20::glSampleCoverage (float value, bool invert) [static]
static void gaia::core::GLES20::glScissor (int32_t x, int32_t y, int32_t width, int32_t height) [static]
static void gaia::core::GLES20::glShaderBinary (int32_t n, uint32_t * shaders, int32_t offset, int32_t binaryformat, void * binary, int32_t length) [static]
static void gaia::core::GLES20::glShaderBinary (int32_t n, uint32_t * shaders, int32_t binaryformat, void * binary, int32_t length) [static]
static void gaia::core::GLES20::glShaderSource (int32_t shader, const gaia::base::String & string) [static]
static void gaia::core::GLES20::glStencilFunc (int32_t func, int32_t ref, int32_t mask) [static]
static void gaia::core::GLES20::glStencilFuncSeparate (int32_t face, int32_t func, int32_t ref, int32_t mask) [static]
static void gaia::core::GLES20::glStencilMask (int32_t mask) [static]
static void gaia::core::GLES20::glStencilMaskSeparate (int32_t face, int32_t mask) [static]
static void gaia::core::GLES20::glStencilOp (int32_t fail, int32_t zfail, int32_t zpass) [static]
static void gaia::core::GLES20::glStencilOpSeparate (int32_t face, int32_t fail, int32_t zfail, int32_t zpass) [static]
template<typename TYPE > static void gaia::core::GLES20::glTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t format, int32_t type, const gaia::base::Array< TYPE > & pixels) [inline, static]
Definition at line 338 of file GLES20.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES20::glTexParameterf (int32_t target, int32_t pname, float param) [static]
static void gaia::core::GLES20::glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES20::glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES20::glTexParameteri (int32_t target, int32_t pname, int32_t param) [static]
static void gaia::core::GLES20::glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES20::glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES20::glTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t type, const gaia::base::ByteArray & pixels) [static]
static void gaia::core::GLES20::glUniform1f (int32_t location, float x) [static]
static void gaia::core::GLES20::glUniform1fv (int32_t location, int32_t count, const gaia::base::Array< float > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform1fv (int32_t location, int32_t count, const gaia::base::Array< float > & v) [static]
static void gaia::core::GLES20::glUniform1i (int32_t location, int32_t x) [static]
static void gaia::core::GLES20::glUniform1iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform1iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v) [static]
static void gaia::core::GLES20::glUniform2f (int32_t location, float x, float y) [static]
static void gaia::core::GLES20::glUniform2fv (int32_t location, int32_t count, const gaia::base::Array< float > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform2fv (int32_t location, int32_t count, const gaia::base::Array< float > & v) [static]
static void gaia::core::GLES20::glUniform2i (int32_t location, int32_t x, int32_t y) [static]
static void gaia::core::GLES20::glUniform2iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v) [static]
static void gaia::core::GLES20::glUniform2iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform3f (int32_t location, float x, float y, float z) [static]
static void gaia::core::GLES20::glUniform3fv (int32_t location, int32_t count, const gaia::base::Array< float > & v) [static]
static void gaia::core::GLES20::glUniform3fv (int32_t location, int32_t count, const gaia::base::Array< float > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform3i (int32_t location, int32_t x, int32_t y, int32_t z) [static]
static void gaia::core::GLES20::glUniform3iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform3iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v) [static]
static void gaia::core::GLES20::glUniform4f (int32_t location, float x, float y, float z, float w) [static]
static void gaia::core::GLES20::glUniform4fv (int32_t location, int32_t count, const gaia::base::Array< float > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform4fv (int32_t location, int32_t count, const gaia::base::Array< float > & v) [static]
static void gaia::core::GLES20::glUniform4i (int32_t location, int32_t x, int32_t y, int32_t z, int32_t w) [static]
static void gaia::core::GLES20::glUniform4iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v, int32_t offset) [static]
static void gaia::core::GLES20::glUniform4iv (int32_t location, int32_t count, const gaia::base::Array< int32_t > & v) [static]
static void gaia::core::GLES20::glUniformMatrix2fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glUniformMatrix2fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > & value) [static]
static void gaia::core::GLES20::glUniformMatrix3fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glUniformMatrix3fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > & value) [static]
static void gaia::core::GLES20::glUniformMatrix4fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > & value) [static]
static void gaia::core::GLES20::glUniformMatrix4fv (int32_t location, int32_t count, bool transpose, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glUseProgram (int32_t program) [static]
static void gaia::core::GLES20::glValidateProgram (int32_t program) [static]
static void gaia::core::GLES20::glVertexAttrib1f (int32_t indx, float x) [static]
static void gaia::core::GLES20::glVertexAttrib1fv (int32_t indx, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glVertexAttrib1fv (int32_t indx, const gaia::base::Array< float > & value) [static]
static void gaia::core::GLES20::glVertexAttrib2f (int32_t indx, float x, float y) [static]
static void gaia::core::GLES20::glVertexAttrib2fv (int32_t indx, const gaia::base::Array< float > & value) [static]
static void gaia::core::GLES20::glVertexAttrib2fv (int32_t indx, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glVertexAttrib3f (int32_t indx, float x, float y, float z) [static]
static void gaia::core::GLES20::glVertexAttrib3fv (int32_t indx, const gaia::base::Array< float > & value) [static]
static void gaia::core::GLES20::glVertexAttrib3fv (int32_t indx, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glVertexAttrib4f (int32_t indx, float x, float y, float z, float w) [static]
static void gaia::core::GLES20::glVertexAttrib4fv (int32_t indx, const gaia::base::Array< float > & value, int32_t offset) [static]
static void gaia::core::GLES20::glVertexAttrib4fv (int32_t indx, const gaia::base::Array< float > & value) [static]
template<typename TYPE > static void gaia::core::GLES20::glVertexAttribPointer (int indx, int size, int type, bool normalized, int stride, const gaia::base::Array< TYPE > & pointer, int offset) [inline, static]
Definition at line 459 of file GLES20.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES20::glViewport (int x, int y, int width, int height) [static]
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/GLES20.h