gaia::base::HashMapImpl Class Reference
gaia::base::HashMapImpl Class Reference
#include <HashMapImpl.h>
Public Types
enum { HAS_TRIVIAL_CTOR = 0x00000001, HAS_TRIVIAL_DTOR = 0x00000002, HAS_TRIVIAL_COPY = 0x00000004 }
Public Member Functions
HashMapImpl (size_t nodeSize)
HashMapImpl (size_t nodeSize, size_t capacity)
HashMapImpl (const HashMapImpl &rhs)
virtual ~HashMapImpl ()
void finish_hashmap ()
HashMapImpl & operator= (const HashMapImpl &rhs)
const void * arrayImpl () const
void * editArrayImpl ()
size_t size () const
bool isEmpty () const
size_t capacity () const
void * valueFor (const void *key, size_t hash) const
void add (const void *key, const void *value, size_t hash)
void addHashMap (const HashMapImpl &hashmap)
bool containsKey (const void *key, size_t hash) const
bool containsValue (const void *value) const
void remove (const void *key, size_t hash)
void clear ()
void * begin ()
const void * begin () const
void * end ()
const void * end () const
Protected Member Functions
void release_storage (void *storage, size_t count)
virtual void do_set_field (void *field, void *node) const =0
virtual void * do_get_field (const void *field) const =0
virtual void * do_new_node (const void *key, const void *value, size_t hash, void *next) const =0
virtual void do_del_node (void *node) const =0
virtual bool do_equals_key (const void *node, const void *key) const =0
virtual bool do_equals_value (const void *node, const void *value) const =0
virtual size_t do_get_hash_of_key (const void *key) const =0
virtual const void * do_get_key (const void *node) const =0
virtual const void * do_get_value (const void *node) const =0
virtual size_t do_get_hash (const void *node) const =0
virtual void * do_get_next (const void *node) const =0
virtual void do_set_value (void *node, const void *value) const =0
virtual void do_set_next (void *node, void *next) const =0
void * nextNode (const void *node) const
virtual void reservedHashMapImpl1 ()
virtual void reservedHashMapImpl2 ()
virtual void reservedHashMapImpl3 ()
virtual void reservedHashMapImpl4 ()
virtual void reservedHashMapImpl5 ()
virtual void reservedHashMapImpl6 ()
virtual void reservedHashMapImpl7 ()
virtual void reservedHashMapImpl8 ()
Private Member Functions
void * makeTable (size_t newCapacity)
Allocate a table of the given capacity and set the threshold accordingly.
void * doubleCapacity ()
Doubles the capacity of the hash table.
void ensureCapacity (size_t numMappings)
Ensures that the hash table has sufficient capacity to store the specified number of mappings, with room to grow.
void _do_destroy (void *storage, size_t num) const
void _do_copy (void *dest, const void *from, size_t num) const
Private Attributes
void * mpStorage
size_t mCount
size_t mThreshold
The table is rehashed when its size exceeds this threshold.
const size_t mNodeSize
Detailed Description
Definition at line 26 of file HashMapImpl.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
HAS_TRIVIAL_CTOR
HAS_TRIVIAL_DTOR
HAS_TRIVIAL_COPY
Definition at line 28 of file HashMapImpl.h.
Constructor & Destructor Documentation
gaia::base::HashMapImpl::HashMapImpl (size_t nodeSize) [explicit]
gaia::base::HashMapImpl::HashMapImpl (size_t nodeSize, size_t capacity)
gaia::base::HashMapImpl::HashMapImpl (const HashMapImpl & rhs)
virtual gaia::base::HashMapImpl::~HashMapImpl () [virtual]
Member Function Documentation
void gaia::base::HashMapImpl::_do_copy (void * dest, const void * from, size_t num) const [private]
void gaia::base::HashMapImpl::_do_destroy (void * storage, size_t num) const [private]
void gaia::base::HashMapImpl::add (const void * key, const void * value, size_t hash)
Referenced by gaia::base::HashMap< KEY, VAL >::add().
void gaia::base::HashMapImpl::addHashMap (const HashMapImpl & hashmap)
Referenced by gaia::base::HashMap< KEY, VAL >::addHashMap().
const void* gaia::base::HashMapImpl::arrayImpl () const [inline]
Definition at line 44 of file HashMapImpl.h.
References mpStorage.
const void* gaia::base::HashMapImpl::begin () const
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
void* gaia::base::HashMapImpl::begin ()
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
Referenced by gaia::base::HashMap< KEY, VAL >::begin().
size_t gaia::base::HashMapImpl::capacity () const
void gaia::base::HashMapImpl::clear ()
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
Referenced by gaia::base::HashMap< KEY, VAL >::clear().
bool gaia::base::HashMapImpl::containsKey (const void * key, size_t hash) const
Referenced by gaia::base::HashMap< KEY, VAL >::containsKey().
bool gaia::base::HashMapImpl::containsValue (const void * value) const
Referenced by gaia::base::HashMap< KEY, VAL >::containsValue().
virtual void gaia::base::HashMapImpl::do_del_node (void * node) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual bool gaia::base::HashMapImpl::do_equals_key (const void * node, const void * key) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual bool gaia::base::HashMapImpl::do_equals_value (const void * node, const void * value) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual void* gaia::base::HashMapImpl::do_get_field (const void * field) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual size_t gaia::base::HashMapImpl::do_get_hash (const void * node) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual size_t gaia::base::HashMapImpl::do_get_hash_of_key (const void * key) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual const void* gaia::base::HashMapImpl::do_get_key (const void * node) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual void* gaia::base::HashMapImpl::do_get_next (const void * node) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual const void* gaia::base::HashMapImpl::do_get_value (const void * node) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual void* gaia::base::HashMapImpl::do_new_node (const void * key, const void * value, size_t hash, void * next) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual void gaia::base::HashMapImpl::do_set_field (void * field, void * node) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual void gaia::base::HashMapImpl::do_set_next (void * node, void * next) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
virtual void gaia::base::HashMapImpl::do_set_value (void * node, const void * value) const [protected, pure virtual]
Implemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
void* gaia::base::HashMapImpl::doubleCapacity () [private]
Doubles the capacity of the hash table.
Existing entries are placed in the correct bucket on the enlarged table. If the current capacity is, MAXIMUM_CAPACITY, this method is a no-op. Returns the table, which will be new unless we were already at MAXIMUM_CAPACITY.
void* gaia::base::HashMapImpl::editArrayImpl ()
void* gaia::base::HashMapImpl::end ()
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
Referenced by gaia::base::HashMap< KEY, VAL >::end().
const void* gaia::base::HashMapImpl::end () const
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
void gaia::base::HashMapImpl::ensureCapacity (size_t numMappings) [private]
Ensures that the hash table has sufficient capacity to store the specified number of mappings, with room to grow.
If not, it increases the capacity as appropriate. Like doubleCapacity, this method moves existing entries to new buckets as appropriate. Unlike doubleCapacity, this method can grow the table by factors of 2^n for n > 1. Hopefully, a single call to this method will be faster than multiple calls to doubleCapacity.
This method is called only by putAll.
void gaia::base::HashMapImpl::finish_hashmap ()
must be called from subclasses destructor
bool gaia::base::HashMapImpl::isEmpty () const [inline]
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
Definition at line 48 of file HashMapImpl.h.
References mCount.
Referenced by gaia::base::HashMap< KEY, VAL >::isEmpty().
void* gaia::base::HashMapImpl::makeTable (size_t newCapacity) [private]
Allocate a table of the given capacity and set the threshold accordingly.
Parameters:
newCapacity must be a power of two
void* gaia::base::HashMapImpl::nextNode (const void * node) const [protected]
Referenced by gaia::base::HashMap< KEY, VAL >::nextNode().
HashMapImpl& gaia::base::HashMapImpl::operator= (const HashMapImpl & rhs)
Referenced by gaia::base::HashMap< KEY, VAL >::operator=().
void gaia::base::HashMapImpl::release_storage (void * storage, size_t count) [protected]
void gaia::base::HashMapImpl::remove (const void * key, size_t hash)
Referenced by gaia::base::HashMap< KEY, VAL >::remove().
virtual void gaia::base::HashMapImpl::reservedHashMapImpl1 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl2 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl3 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl4 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl5 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl6 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl7 () [protected, virtual]
virtual void gaia::base::HashMapImpl::reservedHashMapImpl8 () [protected, virtual]
size_t gaia::base::HashMapImpl::size () const [inline]
Reimplemented in gaia::base::HashMap< KEY, VAL >, gaia::base::HashMap< gaia::base::String, gaia::base::String >, gaia::base::HashMap< gaia::base::String, ByteBuffer * >, gaia::base::HashMap< gaia::base::String, ByteBuffer >, gaia::base::HashMap< gaia::base::String, PluginMetaDataInfo * >, and gaia::base::HashMap< T, HashSet< T > * >.
Definition at line 47 of file HashMapImpl.h.
References mCount.
Referenced by gaia::base::HashMap< KEY, VAL >::size().
void* gaia::base::HashMapImpl::valueFor (const void * key, size_t hash) const
Referenced by gaia::base::HashMap< KEY, VAL >::valueFor().
Member Data Documentation
size_t gaia::base::HashMapImpl::mCount [private]
Definition at line 141 of file HashMapImpl.h.
Referenced by isEmpty(), and size().
const size_t gaia::base::HashMapImpl::mNodeSize [private]
Definition at line 151 of file HashMapImpl.h.
void* gaia::base::HashMapImpl::mpStorage [private]
Definition at line 140 of file HashMapImpl.h.
Referenced by arrayImpl().
size_t gaia::base::HashMapImpl::mThreshold [private]
The table is rehashed when its size exceeds this threshold.
The value of this field is generally .75 * capacity, except when the capacity is zero, as described in the EMPTY_TABLE declaration above.
Definition at line 149 of file HashMapImpl.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/base/HashMapImpl.h