gaia::graphics::Color Class Reference
gaia::graphics::Color Class Reference
The Color class defines methods for creating and converting color ints.
#include <Color.h>
Public Member Functions
Color ()
Create a Color object.
Color (const Color &src)
The copy constructor.
virtual ~Color ()
Color & operator= (const Color &src)
The assignment operator.
Static Public Member Functions
static uint32_t alpha (uint32_t color)
Return the alpha component of a color int.
static uint32_t red (uint32_t color)
Return the red component of a color int.
static uint32_t green (uint32_t color)
Return the green component of a color int.
static uint32_t blue (uint32_t color)
Return the blue component of a color int.
static uint32_t rgb (uint red, uint green, uint blue)
Return a color-int from red, green, blue components.
static uint32_t argb (uint alpha, uint red, uint green, uint blue)
Return a color-int from alpha, red, green, blue components.
static uint32_t parseColor (const base::String &colorString)
Parse the color string, and return the corresponding color-int.
static void RGBToHSV (uint red, uint green, uint blue, gaia::base::Array< float > *hsv)
Convert RGB components to HSV.
static void colorToHSV (uint32_t color, gaia::base::Array< float > *hsv)
Convert the argb color to its HSV components.
static uint32_t HSVToColor (const gaia::base::Array< float > &hsv)
Convert HSV components to an ARGB color.
static uint32_t HSVToColor (uint alpha, const gaia::base::Array< float > &hsv)
Convert HSV components to an ARGB color.
Static Public Attributes
static const uint32_t BLACK = 0xFF000000
Black.
static const uint32_t DKGRAY = 0xFF444444
Dark gray.
static const uint32_t GRAY = 0xFF888888
Gray.
static const uint32_t LTGRAY = 0xFFCCCCCC
Light gray.
static const uint32_t WHITE = 0xFFFFFFFF
White.
static const uint32_t RED = 0xFFFF0000
Red.
static const uint32_t GREEN = 0xFF00FF00
Green.
static const uint32_t BLUE = 0xFF0000FF
Blue.
static const uint32_t YELLOW = 0xFFFFFF00
Yellow.
static const uint32_t CYAN = 0xFF00FFFF
Cyan.
static const uint32_t MAGENTA = 0xFFFF00FF
Magenta.
static const uint32_t TRANSPARENT = 0
Transparent.
Detailed Description
The Color class defines methods for creating and converting color ints.
Colors are represented as packed ints, made up of 4 bytes: alpha, red, green, blue. The values are unpremultiplied, meaning any transparency is stored solely in the alpha component, and not in the color components. The components are stored as follows (alpha << 24) | (red << 16) | (green << 8) | blue. Each component ranges between 0..255 with 0 meaning no contribution for that component, and 255 meaning 100% contribution. Thus opaque-black would be 0xFF000000 (100% opaque but no contributes from red, gree, blue, and opaque-white would be 0xFFFFFFFF
   //use static function of Color for domain transformation
   Color::RGBToHSV(173, 214, 247, hsv);
   //print out the result after trasnformation.
   for (int i=0; i<3; ++i)
        printf("Color: HSV[%d]: %f \n", i, hsv[i]);
   //hsv should be (207, 0.30, 0.97)
Definition at line 37 of file Color.h.
Constructor & Destructor Documentation
gaia::graphics::Color::Color ()
Create a Color object.
gaia::graphics::Color::Color (const Color & src)
The copy constructor.
virtual gaia::graphics::Color::~Color () [virtual]
Member Function Documentation
static uint32_t gaia::graphics::Color::alpha (uint32_t color) [inline, static]
Return the alpha component of a color int.
This is the same as saying color >>> 24
Definition at line 79 of file Color.h.
static uint32_t gaia::graphics::Color::argb (uint alpha, uint red, uint green, uint blue) [inline, static]
Return a color-int from alpha, red, green, blue components.
These component values should be [0..255], but there is no range check performed, so if they are out of range, the returned color is undefined.
Parameters:
alpha Alpha component [0..255] of the color
red Red component [0..255] of the color
green Green component [0..255] of the color
blue Blue component [0..255] of the color
Definition at line 131 of file Color.h.
References blue().
static uint32_t gaia::graphics::Color::blue (uint32_t color) [inline, static]
Return the blue component of a color int.
This is the same as saying color & 0xFF
Definition at line 103 of file Color.h.
Referenced by argb(), and rgb().
static void gaia::graphics::Color::colorToHSV (uint32_t color, gaia::base::Array< float > * hsv) [static]
Convert the argb color to its HSV components.
hsv[0] is Hue [0 .. 360) hsv[1] is Saturation [0...1] hsv[2] is Value [0...1]
Parameters:
color the argb color to convert. The alpha component is ignored.
hsv 3 element array which holds the resulting HSV components.
static uint32_t gaia::graphics::Color::green (uint32_t color) [inline, static]
Return the green component of a color int.
This is the same as saying (color >> 8) & 0xFF
Definition at line 95 of file Color.h.
static uint32_t gaia::graphics::Color::HSVToColor (const gaia::base::Array< float > & hsv) [inline, static]
Convert HSV components to an ARGB color.
Alpha set to 0xFF. hsv[0] is Hue [0 .. 360) hsv[1] is Saturation [0...1] hsv[2] is Value [0...1] If hsv values are out of range, they are pinned.
Parameters:
hsv 3 element array which holds the input HSV components.
Returns:
the resulting argb color
Definition at line 178 of file Color.h.
static uint32_t gaia::graphics::Color::HSVToColor (uint alpha, const gaia::base::Array< float > & hsv) [static]
Convert HSV components to an ARGB color.
The alpha component is passed through unchanged. hsv[0] is Hue [0 .. 360) hsv[1] is Saturation [0...1] hsv[2] is Value [0...1] If hsv values are out of range, they are pinned.
Parameters:
alpha the alpha component of the returned argb color.
hsv 3 element array which holds the input HSV components.
Returns:
the resulting argb color
Color& gaia::graphics::Color::operator= (const Color & src)
The assignment operator.
static uint32_t gaia::graphics::Color::parseColor (const base::String & colorString) [static]
Parse the color string, and return the corresponding color-int.
Supported formats are: RRGGBB AARRGGBB 'red', 'blue', 'green', 'black', 'white', 'gray', 'cyan', 'magenta', 'yellow', 'lightgray', 'darkgray'
static uint32_t gaia::graphics::Color::red (uint32_t color) [inline, static]
Return the red component of a color int.
This is the same as saying (color >> 16) & 0xFF
Definition at line 87 of file Color.h.
static uint32_t gaia::graphics::Color::rgb (uint red, uint green, uint blue) [inline, static]
Return a color-int from red, green, blue components.
The alpha component is implicity 255 (fully opaque). These component values should be [0..255], but there is no range check performed, so if they are out of range, the returned color is undefined.
Parameters:
red Red component [0..255] of the color
green Green component [0..255] of the color
blue Blue component [0..255] of the color
Definition at line 117 of file Color.h.
References blue().
static void gaia::graphics::Color::RGBToHSV (uint red, uint green, uint blue, gaia::base::Array< float > * hsv) [static]
Convert RGB components to HSV.
hsv[0] is Hue [0 .. 360) hsv[1] is Saturation [0...1] hsv[2] is Value [0...1]
Parameters:
red red component value [0..255]
green green component value [0..255]
blue blue component value [0..255]
hsv 3 element array which holds the resulting HSV components.
Member Data Documentation
const uint32_t gaia::graphics::Color::BLACK = 0xFF000000 [static]
Black.
Definition at line 40 of file Color.h.
const uint32_t gaia::graphics::Color::BLUE = 0xFF0000FF [static]
Blue.
Definition at line 54 of file Color.h.
const uint32_t gaia::graphics::Color::CYAN = 0xFF00FFFF [static]
Cyan.
Definition at line 58 of file Color.h.
const uint32_t gaia::graphics::Color::DKGRAY = 0xFF444444 [static]
Dark gray.
Definition at line 42 of file Color.h.
const uint32_t gaia::graphics::Color::GRAY = 0xFF888888 [static]
Gray.
Definition at line 44 of file Color.h.
const uint32_t gaia::graphics::Color::GREEN = 0xFF00FF00 [static]
Green.
Definition at line 52 of file Color.h.
const uint32_t gaia::graphics::Color::LTGRAY = 0xFFCCCCCC [static]
Light gray.
Definition at line 46 of file Color.h.
const uint32_t gaia::graphics::Color::MAGENTA = 0xFFFF00FF [static]
Magenta.
Definition at line 60 of file Color.h.
const uint32_t gaia::graphics::Color::RED = 0xFFFF0000 [static]
Red.
Definition at line 50 of file Color.h.
const uint32_t gaia::graphics::Color::TRANSPARENT = 0 [static]
Transparent.
Definition at line 62 of file Color.h.
const uint32_t gaia::graphics::Color::WHITE = 0xFFFFFFFF [static]
White.
Definition at line 48 of file Color.h.
const uint32_t gaia::graphics::Color::YELLOW = 0xFFFFFF00 [static]
Yellow.
Definition at line 56 of file Color.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/graphics/Color.h