gaia::base::HashMap< KEY, VAL > Class Template Reference
gaia::base::HashMap< KEY, VAL > Class Template Reference
Implements hashmap data structure and operation functions.
#include <HashMap.h>
Classes
class const_iterator
Implements the const iterator for hashmap.
struct HashNode
class iterator
Implements the (non-const) iterator for hashmap.
Public Member Functions
HashMap ()
Constructor of HashMap.
HashMap (size_t capacity)
Copy constructor of HashMap.
HashMap (const HashMap< KEY, VAL > &rhs)
Copy constructor of HashMap.
~HashMap ()
Destructor of hashmap.
const HashMap< KEY, VAL > & operator= (const HashMap< KEY, VAL > &rhs) const
Makes this hashmap the same as rhs.
HashMap< KEY, VAL > & operator= (const HashMap< KEY, VAL > &rhs)
Makes this hashmap the same as rhs.
size_t size () const
Returns the number of elements in this map.
bool isEmpty () const
Returns whether this map is empty.
VAL valueFor (const KEY &key) const
Returns the value of the mapping with the specified key.
void add (const KEY &key, const VAL &value)
Maps the specified key to the specified value.
void addHashMap (const HashMap< KEY, VAL > &hashmap)
Copies all the mappings in the specified map to this map.
bool containsKey (const KEY &key) const
Returns whether this map contains the specified key.
bool containsValue (const VAL &value) const
Returns whether this map contains the specified value.
void remove (const KEY &key)
Removes the mapping with the specified key from this map.
void clear ()
Removes all mappings from this hash map, leaving it empty.
Vector< KEY > keys () const
Acquires all keys in this hashmap.
Vector< VAL > values () const
Acquires all values in this hashmap.
iterator begin ()
Acquires (non-const) hashmap iterator pointed to the head of this hashmap.
const_iterator begin () const
Acquires const hashmap iterator pointed to the head of this hashmap.
iterator end ()
Acquires (non-const) hashmap iterator pointed to the tail of this hashmap.
const_iterator end () const
Acquires const hashmap iterator pointed to the tail of this hashmap.
Private Member Functions
virtual void do_set_field (void *field, void *node) const
virtual void * do_get_field (const void *field) const
virtual void * do_new_node (const void *key, const void *value, size_t hash, void *next) const
virtual void do_del_node (void *node) const
virtual bool do_equals_key (const void *node, const void *key) const
virtual bool do_equals_value (const void *node, const void *value) const
virtual size_t do_get_hash_of_key (const void *key) const
virtual const void * do_get_key (const void *node) const
virtual const void * do_get_value (const void *node) const
virtual size_t do_get_hash (const void *node) const
virtual void * do_get_next (const void *node) const
virtual void do_set_value (void *node, const void *value) const
virtual void do_set_next (void *node, void *next) const
HashNode * nextNode (const HashNode *node) const
Detailed Description
template<class KEY, class VAL>
class gaia::base::HashMap< KEY, VAL >
Implements hashmap data structure and operation functions.
 // Creates a new hashmap
 HashMap<int, String> hmIntStr;
 // Adds items
 if (hmIntStr.size() == 0) {
        for (size_t i = 0; i < 50; i++) {
            hmIntStr.add(i, String::valueOf(i));
        }
 }
 // Queries for specified key.
 if ( "30" == hmIntStr.valueFor(30)) {
        // Do something...
 }
 // Clear hashmap
 hmIntStr.clear();
Definition at line 56 of file HashMap.h.
Constructor & Destructor Documentation
template<class KEY , class VAL > gaia::base::HashMap< KEY, VAL >::HashMap () [inline]
Constructor of HashMap.
Definition at line 473 of file HashMap.h.
template<class KEY , class VAL > gaia::base::HashMap< KEY, VAL >::HashMap (size_t capacity) [inline, explicit]
Copy constructor of HashMap.
Constructs a new HashMap with the specified capacity.
Parameters:
capacity The initial capacity of this hash map.
Definition at line 478 of file HashMap.h.
template<class KEY, class VAL> gaia::base::HashMap< KEY, VAL >::HashMap (const HashMap< KEY, VAL > & rhs) [inline]
Copy constructor of HashMap.
Creates a new HashMap with the specified HashMap.
Parameters:
rhs The hashmap to be copied.
Definition at line 483 of file HashMap.h.
template<class KEY , class VAL > gaia::base::HashMap< KEY, VAL >::~HashMap () [inline]
Destructor of hashmap.
Definition at line 488 of file HashMap.h.
Member Function Documentation
template<class KEY, class VAL> void gaia::base::HashMap< KEY, VAL >::add (const KEY & key, const VAL & value) [inline]
Maps the specified key to the specified value.
Parameters:
key The key.
value The value.
Returns:
The value of any previous mapping with the specified key or null if there was no such mapping.
Definition at line 522 of file HashMap.h.
References gaia::base::HashMapImpl::add(), and gaia::base::hashCode().
template<class KEY, class VAL> void gaia::base::HashMap< KEY, VAL >::addHashMap (const HashMap< KEY, VAL > & hashmap) [inline]
Copies all the mappings in the specified map to this map.
These mappings will replace all mappings that this map had for any of the keys currently in the given map.
Parameters:
hashmap The hashmap to copy mappings from.
Definition at line 527 of file HashMap.h.
References gaia::base::HashMapImpl::addHashMap().
template<class KEY , class VAL > HashMap< KEY, VAL >::iterator gaia::base::HashMap< KEY, VAL >::begin () [inline]
Acquires (non-const) hashmap iterator pointed to the head of this hashmap.
Returns:
Non-const hashmap iterator pointed to the head of this hashmap.
Reimplemented from gaia::base::HashMapImpl.
Definition at line 572 of file HashMap.h.
References gaia::base::HashMapImpl::begin().
template<class KEY , class VAL > HashMap< KEY, VAL >::const_iterator gaia::base::HashMap< KEY, VAL >::begin () const [inline]
Acquires const hashmap iterator pointed to the head of this hashmap.
Returns:
Const hashmap iterator pointed to the head of this hashmap.
Reimplemented from gaia::base::HashMapImpl.
Definition at line 577 of file HashMap.h.
References gaia::base::HashMapImpl::begin().
template<class KEY , class VAL > void gaia::base::HashMap< KEY, VAL >::clear () [inline]
Removes all mappings from this hash map, leaving it empty.
See also:
isEmpty
size
Reimplemented from gaia::base::HashMapImpl.
Definition at line 547 of file HashMap.h.
References gaia::base::HashMapImpl::clear().
template<class KEY, class VAL > bool gaia::base::HashMap< KEY, VAL >::containsKey (const KEY & key) const [inline]
Returns whether this map contains the specified key.
Parameters:
key The key to search for.
Returns:
True if this map contains the specified key, false otherwise.
Definition at line 532 of file HashMap.h.
References gaia::base::HashMapImpl::containsKey(), and gaia::base::hashCode().
template<class KEY , class VAL> bool gaia::base::HashMap< KEY, VAL >::containsValue (const VAL & value) const [inline]
Returns whether this map contains the specified value.
Parameters:
value the value to search for.
Returns:
True if this map contains the specified value, false otherwise.
Definition at line 537 of file HashMap.h.
References gaia::base::HashMapImpl::containsValue().
template<class KEY , class VAL > void gaia::base::HashMap< KEY, VAL >::do_del_node (void * node) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 618 of file HashMap.h.
template<class KEY , class VAL > bool gaia::base::HashMap< KEY, VAL >::do_equals_key (const void * node, const void * key) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 623 of file HashMap.h.
template<class KEY , class VAL > bool gaia::base::HashMap< KEY, VAL >::do_equals_value (const void * node, const void * value) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 629 of file HashMap.h.
template<class KEY , class VAL > void * gaia::base::HashMap< KEY, VAL >::do_get_field (const void * field) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 605 of file HashMap.h.
template<class KEY , class VAL > size_t gaia::base::HashMap< KEY, VAL >::do_get_hash (const void * node) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 651 of file HashMap.h.
template<class KEY , class VAL > size_t gaia::base::HashMap< KEY, VAL >::do_get_hash_of_key (const void * key) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 636 of file HashMap.h.
References gaia::base::hashCode().
template<class KEY , class VAL > const void * gaia::base::HashMap< KEY, VAL >::do_get_key (const void * node) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 641 of file HashMap.h.
template<class KEY , class VAL > void * gaia::base::HashMap< KEY, VAL >::do_get_next (const void * node) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 656 of file HashMap.h.
template<class KEY , class VAL > const void * gaia::base::HashMap< KEY, VAL >::do_get_value (const void * node) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 646 of file HashMap.h.
template<class KEY , class VAL > void * gaia::base::HashMap< KEY, VAL >::do_new_node (const void * key, const void * value, size_t hash, void * next) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 610 of file HashMap.h.
template<class KEY , class VAL > void gaia::base::HashMap< KEY, VAL >::do_set_field (void * field, void * node) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 600 of file HashMap.h.
template<class KEY , class VAL > void gaia::base::HashMap< KEY, VAL >::do_set_next (void * node, void * next) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 667 of file HashMap.h.
template<class KEY , class VAL > void gaia::base::HashMap< KEY, VAL >::do_set_value (void * node, const void * value) const [private, virtual]
Implements gaia::base::HashMapImpl.
Definition at line 661 of file HashMap.h.
template<class KEY , class VAL > HashMap< KEY, VAL >::iterator gaia::base::HashMap< KEY, VAL >::end () [inline]
Acquires (non-const) hashmap iterator pointed to the tail of this hashmap.
Returns:
Non-const list iterator pointed to the tail of this hashmap.
Reimplemented from gaia::base::HashMapImpl.
Definition at line 582 of file HashMap.h.
References gaia::base::HashMapImpl::end().
template<class KEY , class VAL > HashMap< KEY, VAL >::const_iterator gaia::base::HashMap< KEY, VAL >::end () const [inline]
Acquires const hashmap iterator pointed to the tail of this hashmap.
Returns:
Const hashmap iterator pointed to the tail of this hashmap.
Reimplemented from gaia::base::HashMapImpl.
Definition at line 587 of file HashMap.h.
References gaia::base::HashMapImpl::end().
template<class KEY , class VAL > bool gaia::base::HashMap< KEY, VAL >::isEmpty () const [inline]
Returns whether this map is empty.
Returns:
True if this map has no elements, false otherwise.
See also:
size()
Reimplemented from gaia::base::HashMapImpl.
Definition at line 511 of file HashMap.h.
References gaia::base::HashMapImpl::isEmpty().
template<class KEY , class VAL > Vector< KEY > gaia::base::HashMap< KEY, VAL >::keys () const [inline]
Acquires all keys in this hashmap.
Returns:
Keys in vector format.
Definition at line 552 of file HashMap.h.
References gaia::base::Vector< TYPE >::append(), and gaia::base::Vector< TYPE >::setCapacity().
template<class KEY , class VAL > HashMap< KEY, VAL >::HashNode * gaia::base::HashMap< KEY, VAL >::nextNode (const HashNode * node) const [inline, private]
Definition at line 592 of file HashMap.h.
References gaia::base::HashMapImpl::nextNode().
template<class KEY, class VAL> HashMap< KEY, VAL > & gaia::base::HashMap< KEY, VAL >::operator= (const HashMap< KEY, VAL > & rhs) [inline]
Makes this hashmap the same as rhs.
Parameters:
rhs The target hashmap to be copied.
Returns:
Non-const address of this hashmap.
Definition at line 493 of file HashMap.h.
References gaia::base::HashMapImpl::operator=().
template<class KEY, class VAL> const HashMap< KEY, VAL > & gaia::base::HashMap< KEY, VAL >::operator= (const HashMap< KEY, VAL > & rhs) const [inline]
Makes this hashmap the same as rhs.
Parameters:
rhs The target hashmap to be copied.
Returns:
Const address of this hashmap.
Definition at line 499 of file HashMap.h.
References gaia::base::HashMapImpl::operator=().
template<class KEY, class VAL > void gaia::base::HashMap< KEY, VAL >::remove (const KEY & key) [inline]
Removes the mapping with the specified key from this map.
Parameters:
key the key of the mapping to remove.
Returns:
the value of the removed mapping or
 null
if no mapping for the specified key was found.
Definition at line 542 of file HashMap.h.
References gaia::base::hashCode(), and gaia::base::HashMapImpl::remove().
template<class KEY , class VAL > size_t gaia::base::HashMap< KEY, VAL >::size () const [inline]
Returns the number of elements in this map.
Returns:
The number of elements in this map.
Reimplemented from gaia::base::HashMapImpl.
Definition at line 506 of file HashMap.h.
References gaia::base::HashMapImpl::size().
template<class KEY, class VAL > VAL gaia::base::HashMap< KEY, VAL >::valueFor (const KEY & key) const [inline]
Returns the value of the mapping with the specified key.
Parameters:
key The key.
Returns:
The value of the mapping with the specified key, or null if no mapping for the specified key is found.
Definition at line 516 of file HashMap.h.
References gaia::base::hashCode(), and gaia::base::HashMapImpl::valueFor().
template<class KEY , class VAL > Vector< VAL > gaia::base::HashMap< KEY, VAL >::values () const [inline]
Acquires all values in this hashmap.
Returns:
Values in vector format.
Definition at line 562 of file HashMap.h.
References gaia::base::Vector< TYPE >::append(), and gaia::base::Vector< TYPE >::setCapacity().
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/base/HashMap.h