gaia::base::ListImpl Class Reference
gaia::base::ListImpl Class Reference
Implements list data structure.
#include <ListImpl.h>
Classes
class Node
A node structure that will be gathered into a list.
Private Types
enum { HAS_TRIVIAL_CTOR = 0x00000001, HAS_TRIVIAL_DTOR = 0x00000002, HAS_TRIVIAL_COPY = 0x00000004 }
Flags passed to the ctor.
Private Member Functions
ListImpl (size_t itemSize, uint32_t flags)
Constructor for ListImpl.
ListImpl (const ListImpl &rhs)
Copy constructor of ListImpl.
virtual ~ListImpl ()
Destructor of ListImpl.
ListImpl & operator= (const ListImpl &rhs)
Removes all nodes in this ListImpl and copies the list from the other entity.
bool isEmpty () const
Checks if possessed list is empty.
size_t listSize () const
Gets the number of nodes possessed.
Node * insertNodeAt (const Node *pivotNode, const void *data)
Inserts given data at pivotNode.
Node * removeNodeAt (Node *targetNode)
Removes an node at the specified position.
void removeNodeRange (const Node *startNode, const Node *endNode)
Removes a bundle of nodes.
const Node * acquireFirstNode () const
Acquires the first node in the list.
const Node * acquireLastNode () const
Acquires the last node in the list.
void copy_list (const ListImpl &rhs)
Copies whole list in rhs and directly inserts to current list at the head of list.
void finish_list ()
Removes all nodes except the mpMiddle node.
virtual void do_destroy (void *storage, size_t num) const =0
Used to destory datum stored in the list.
virtual void do_copy (void *dest, const void *from, size_t num) const =0
Used to copy datum stored in the list.
virtual void reservedListImpl1 ()
Used to take care of FBC.
virtual void reservedListImpl2 ()
Used to take care of FBC.
virtual void reservedListImpl3 ()
Used to take care of FBC.
virtual void reservedListImpl4 ()
Used to take care of FBC.
virtual void reservedListImpl5 ()
Used to take care of FBC.
virtual void reservedListImpl6 ()
Used to take care of FBC.
virtual void reservedListImpl7 ()
Used to take care of FBC.
virtual void reservedListImpl8 ()
Used to take care of FBC.
void prep ()
Creates a list by creating the mpMiddle node.
void deleteNode (Node *targetNode, const ListImpl *ptrListImpl)
Remvoes data stored in targetNode and delete this node.
void _do_destroy (void *storage, size_t num) const
Destory data by calling the destructor of that data type.
void _do_copy (void *dest, const void *from, size_t num) const
Copy data by calling the copy constructor of that data tpye.
Private Attributes
Node * mpMiddle
The access point of a list.
size_t mCount
The number of nodes in this list.
const uint32_t mFlags
Characteristics of the stored data.
const size_t mItemSize
Size of the type of stored data.
Detailed Description
Implements list data structure.
This class is not used directly. List should use instead.
See also:
List
 // Create a ListImpl and a node pointer as a list operator.
 ListImpl lst_impl(sizeof(int), HAS_TRIVIAL_CTOR);
 Node* target = lst_impl.acquireFirstNode();
 // Inserts node
 int a = 2011;
 target = lst_impl.insertNodeAt(target, a);
 // Removes node
 lst_impl.removeNodeAt(target);
Definition at line 33 of file ListImpl.h.
Member Enumeration Documentation
anonymous enum [private]
Flags passed to the ctor.
Enumerator:
HAS_TRIVIAL_CTOR
HAS_TRIVIAL_DTOR
HAS_TRIVIAL_COPY
Definition at line 191 of file ListImpl.h.
Constructor & Destructor Documentation
gaia::base::ListImpl::ListImpl (size_t itemSize, uint32_t flags) [private]
Constructor for ListImpl.
Parameters:
itemSize Data size of those datum which will be stored.
flags Characteristics of stored data type.
See also:
TypeHelpers.h
gaia::base::ListImpl::ListImpl (const ListImpl & rhs) [private]
Copy constructor of ListImpl.
Copy listImpl from the other entity.
Parameters:
rhs The other ListImpl entity provided for copy.
virtual gaia::base::ListImpl::~ListImpl () [private, virtual]
Destructor of ListImpl.
Member Function Documentation
void gaia::base::ListImpl::_do_copy (void * dest, const void * from, size_t num) const [inline, private]
Copy data by calling the copy constructor of that data tpye.
Parameters:
dest The memory address that datum is copied to.
from The memory address that datum is copied from.
num The number of datum counted in the unit of specified data type.
void gaia::base::ListImpl::_do_destroy (void * storage, size_t num) const [inline, private]
Destory data by calling the destructor of that data type.
Parameters:
storage The memory address where data is stored into.
num The number of datum counted in the unit of specified data type.
const Node* gaia::base::ListImpl::acquireFirstNode () const [private]
Acquires the first node in the list.
The first node is the node next to the mpMiddle.
Returns:
The first node in the list.
Referenced by gaia::base::List< X509Certificate * >::begin().
const Node* gaia::base::ListImpl::acquireLastNode () const [private]
Acquires the last node in the list.
The last node is exactly the mpMiddle node.
Returns:
The last node in the list.
Referenced by gaia::base::List< X509Certificate * >::end().
void gaia::base::ListImpl::copy_list (const ListImpl & rhs) [private]
Copies whole list in rhs and directly inserts to current list at the head of list.
This function is used for copy constructors of sub-classes.
Parameters:
rhs The other ListImpl entity provided for copy.
Referenced by gaia::base::List< TYPE >::List().
void gaia::base::ListImpl::deleteNode (Node * targetNode, const ListImpl * ptrListImpl) [private]
Remvoes data stored in targetNode and delete this node.
_do_destroy() is called to correctly remove data and release memory.
Parameters:
targetNode The node to be deleted.
ptrListImpl The ListImpl entity that possesses this node.
virtual void gaia::base::ListImpl::do_copy (void * dest, const void * from, size_t num) const [private, pure virtual]
Used to copy datum stored in the list.
This virtual function should be implemented by sub-classes.
Parameters:
dest The memory address of space that datum is copied to.
from The memory address of datum, which is to be copied.
num Number of datum in the unit of data type.
Implemented in gaia::base::List< TYPE >, and gaia::base::List< X509Certificate * >.
virtual void gaia::base::ListImpl::do_destroy (void * storage, size_t num) const [private, pure virtual]
Used to destory datum stored in the list.
This virtual function should be implemented by sub-classes.
Parameters:
storage The memory address of stored datum.
num Number of datum in the unit of data type.
Implemented in gaia::base::List< TYPE >, and gaia::base::List< X509Certificate * >.
void gaia::base::ListImpl::finish_list () [private]
Removes all nodes except the mpMiddle node.
This function is used for destructors of sub-classes.
Node* gaia::base::ListImpl::insertNodeAt (const Node * pivotNode, const void * data) [private]
Inserts given data at pivotNode.
Data is copied into list list and the original node at pivot is moved to the next position.
Parameters:
pivotNode The position that data inserted at.
data Data to be stored into list.
Returns:
The node that data is stored into.
Referenced by gaia::base::List< X509Certificate * >::insert().
bool gaia::base::ListImpl::isEmpty () const [inline, private]
Checks if possessed list is empty.
Returns:
True if it is empty, false otherwise.
Definition at line 241 of file ListImpl.h.
References gaia::base::ListImpl::Node::getNextPtr(), and mpMiddle.
size_t gaia::base::ListImpl::listSize () const [inline, private]
Gets the number of nodes possessed.
Returns:
The number of nodes.
Definition at line 251 of file ListImpl.h.
References mCount.
ListImpl& gaia::base::ListImpl::operator= (const ListImpl & rhs) [private]
Removes all nodes in this ListImpl and copies the list from the other entity.
Parameters:
rhs The other ListImpl entity provided for assignment.
Returns:
Address of this ListImpl.
Referenced by gaia::base::List< TYPE >::operator=().
void gaia::base::ListImpl::prep () [private]
Creates a list by creating the mpMiddle node.
Node* gaia::base::ListImpl::removeNodeAt (Node * targetNode) [private]
Removes an node at the specified position.
Parameters:
targetNode The node to be removed.
Returns:
The node next to the targetNode.
Referenced by gaia::base::List< X509Certificate * >::erase().
void gaia::base::ListImpl::removeNodeRange (const Node * startNode, const Node * endNode) [private]
Removes a bundle of nodes.
Be aware that the startNode is removed, but endNode is not. (STL-like operation)
Parameters:
startNode The first node of the given range.
endNode The last node of the given range.
virtual void gaia::base::ListImpl::reservedListImpl1 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl2 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl3 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl4 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl5 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl6 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl7 () [private, virtual]
Used to take care of FBC.
virtual void gaia::base::ListImpl::reservedListImpl8 () [private, virtual]
Used to take care of FBC.
Member Data Documentation
size_t gaia::base::ListImpl::mCount [private]
The number of nodes in this list.
Definition at line 451 of file ListImpl.h.
Referenced by listSize().
const uint32_t gaia::base::ListImpl::mFlags [private]
Characteristics of the stored data.
Definition at line 457 of file ListImpl.h.
const size_t gaia::base::ListImpl::mItemSize [private]
Size of the type of stored data.
Definition at line 463 of file ListImpl.h.
Node* gaia::base::ListImpl::mpMiddle [private]
The access point of a list.
Because the list is constructed as a circular bi-directional linkedlist, each node is linked forward and backward to others. This node is set in the middle of a list and plays the role of access point of a list. This node is also regarded as the tail of a list.
Definition at line 445 of file ListImpl.h.
Referenced by isEmpty().
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/base/ListImpl.h