gaia::core::GL10 Class Reference
gaia::core::GL10 Class Reference
#include <GL10.h>
Public Types
enum GL10Macro {
GL_ADD = 0x0104, GL_ALIASED_LINE_WIDTH_RANGE = 0x846E, GL_ALIASED_POINT_SIZE_RANGE = 0x846D, GL_ALPHA = 0x1906,
GL_ALPHA_BITS = 0x0D55, GL_ALPHA_TEST = 0x0BC0, GL_ALWAYS = 0x0207, GL_AMBIENT = 0x1200,
GL_AMBIENT_AND_DIFFUSE = 0x1602, GL_AND = 0x1501, GL_AND_INVERTED = 0x1504, GL_AND_REVERSE = 0x1502,
GL_BACK = 0x0405, GL_BLEND = 0x0BE2, GL_BLUE_BITS = 0x0D54, GL_BYTE = 0x1400,
GL_CCW = 0x0901, GL_CLAMP_TO_EDGE = 0x812F, GL_CLEAR = 0x1500, GL_COLOR_ARRAY = 0x8076,
GL_COLOR_BUFFER_BIT = 0x4000, GL_COLOR_LOGIC_OP = 0x0BF2, GL_COLOR_MATERIAL = 0x0B57, GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3,
GL_CONSTANT_ATTENUATION = 0x1207, GL_COPY = 0x1503, GL_COPY_INVERTED = 0x150C, GL_CULL_FACE = 0x0B44,
GL_CW = 0x0900, GL_DECAL = 0x2101, GL_DECR = 0x1E03, GL_DEPTH_BITS = 0x0D56,
GL_DEPTH_BUFFER_BIT = 0x0100, GL_DEPTH_TEST = 0x0B71, GL_DIFFUSE = 0x1201, GL_DITHER = 0x0BD0,
GL_DONT_CARE = 0x1100, GL_DST_ALPHA = 0x0304, GL_DST_COLOR = 0x0306, GL_EMISSION = 0x1600,
GL_EQUAL = 0x0202, GL_EQUIV = 0x1509, GL_EXP = 0x0800, GL_EXP2 = 0x0801,
GL_EXTENSIONS = 0x1F03, GL_FALSE = 0, GL_FASTEST = 0x1101, GL_FIXED = 0x140C,
GL_FLAT = 0x1D00, GL_FLOAT = 0x1406, GL_FOG = 0x0B60, GL_FOG_COLOR = 0x0B66,
GL_FOG_DENSITY = 0x0B62, GL_FOG_END = 0x0B64, GL_FOG_HINT = 0x0C54, GL_FOG_MODE = 0x0B65,
GL_FOG_START = 0x0B63, GL_FRONT = 0x0404, GL_FRONT_AND_BACK = 0x0408, GL_GEQUAL = 0x0206,
GL_GREATER = 0x0204, GL_GREEN_BITS = 0x0D53, GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES = 0x8B9B, GL_IMPLEMENTATION_COLOR_READ_TYPE_OES = 0x8B9A,
GL_INCR = 0x1E02, GL_INVALID_ENUM = 0x0500, GL_INVALID_OPERATION = 0x0502, GL_INVALID_VALUE = 0x0501,
GL_INVERT = 0x150A, GL_KEEP = 0x1E00, GL_LEQUAL = 0x0203, GL_LESS = 0x0201,
GL_LIGHT_MODEL_AMBIENT = 0x0B53, GL_LIGHT_MODEL_TWO_SIDE = 0x0B52, GL_LIGHT0 = 0x4000, GL_LIGHT1 = 0x4001,
GL_LIGHT2 = 0x4002, GL_LIGHT3 = 0x4003, GL_LIGHT4 = 0x4004, GL_LIGHT5 = 0x4005,
GL_LIGHT6 = 0x4006, GL_LIGHT7 = 0x4007, GL_LIGHTING = 0x0B50, GL_LINE_LOOP = 0x0002,
GL_LINE_SMOOTH = 0x0B20, GL_LINE_SMOOTH_HINT = 0x0C52, GL_LINE_STRIP = 0x0003, GL_LINEAR = 0x2601,
GL_LINEAR_ATTENUATION = 0x1208, GL_LINEAR_MIPMAP_LINEAR = 0x2703, GL_LINEAR_MIPMAP_NEAREST = 0x2701, GL_LINES = 0x0001,
GL_LUMINANCE = 0x1909, GL_LUMINANCE_ALPHA = 0x190A, GL_MAX_ELEMENTS_INDICES = 0x80E9, GL_MAX_ELEMENTS_VERTICES = 0x80E8,
GL_MAX_LIGHTS = 0x0D31, GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36, GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38, GL_MAX_TEXTURE_SIZE = 0x0D33,
GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39, GL_MAX_TEXTURE_UNITS = 0x84E2, GL_MAX_VIEWPORT_DIMS = 0x0D3A, GL_MODELVIEW = 0x1700,
GL_MODULATE = 0x2100, GL_MULTISAMPLE = 0x809D, GL_NAND = 0x150E, GL_NEAREST = 0x2600,
GL_NEAREST_MIPMAP_LINEAR = 0x2702, GL_NEAREST_MIPMAP_NEAREST = 0x2700, GL_NEVER = 0x0200, GL_NICEST = 0x1102,
GL_NO_ERROR = 0, GL_NOOP = 0x1505, GL_NOR = 0x1508, GL_NORMAL_ARRAY = 0x8075,
GL_NORMALIZE = 0x0BA1, GL_NOTEQUAL = 0x0205, GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2, GL_ONE = 1,
GL_ONE_MINUS_DST_ALPHA = 0x0305, GL_ONE_MINUS_DST_COLOR = 0x0307, GL_ONE_MINUS_SRC_ALPHA = 0x0303, GL_ONE_MINUS_SRC_COLOR = 0x0301,
GL_OR = 0x1507, GL_OR_INVERTED = 0x150D, GL_OR_REVERSE = 0x150B, GL_OUT_OF_MEMORY = 0x0505,
GL_PACK_ALIGNMENT = 0x0D05, GL_PALETTE4_R5_G6_B5_OES = 0x8B92, GL_PALETTE4_RGB5_A1_OES = 0x8B94, GL_PALETTE4_RGB8_OES = 0x8B90,
GL_PALETTE4_RGBA4_OES = 0x8B93, GL_PALETTE4_RGBA8_OES = 0x8B91, GL_PALETTE8_R5_G6_B5_OES = 0x8B97, GL_PALETTE8_RGB5_A1_OES = 0x8B99,
GL_PALETTE8_RGB8_OES = 0x8B95, GL_PALETTE8_RGBA4_OES = 0x8B98, GL_PALETTE8_RGBA8_OES = 0x8B96, GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50,
GL_POINT_SMOOTH = 0x0B10, GL_POINT_SMOOTH_HINT = 0x0C51, GL_POINTS = 0x0000, GL_POINT_FADE_THRESHOLD_SIZE = 0x8128,
GL_POINT_SIZE = 0x0B11, GL_POLYGON_OFFSET_FILL = 0x8037, GL_POLYGON_SMOOTH_HINT = 0x0C53, GL_POSITION = 0x1203,
GL_PROJECTION = 0x1701, GL_QUADRATIC_ATTENUATION = 0x1209, GL_RED_BITS = 0x0D52, GL_RENDERER = 0x1F01,
GL_REPEAT = 0x2901, GL_REPLACE = 0x1E01, GL_RESCALE_NORMAL = 0x803A, GL_RGB = 0x1907,
GL_RGBA = 0x1908, GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E, GL_SAMPLE_ALPHA_TO_ONE = 0x809F, GL_SAMPLE_COVERAGE = 0x80A0,
GL_SCISSOR_TEST = 0x0C11, GL_SET = 0x150F, GL_SHININESS = 0x1601, GL_SHORT = 0x1402,
GL_SMOOTH = 0x1D01, GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22, GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12, GL_SPECULAR = 0x1202,
GL_SPOT_CUTOFF = 0x1206, GL_SPOT_DIRECTION = 0x1204, GL_SPOT_EXPONENT = 0x1205, GL_SRC_ALPHA = 0x0302,
GL_SRC_ALPHA_SATURATE = 0x0308, GL_SRC_COLOR = 0x0300, GL_STACK_OVERFLOW = 0x0503, GL_STACK_UNDERFLOW = 0x0504,
GL_STENCIL_BITS = 0x0D57, GL_STENCIL_BUFFER_BIT = 0x0400, GL_STENCIL_TEST = 0x0B90, GL_SUBPIXEL_BITS = 0x0D50,
GL_TEXTURE = 0x1702, GL_TEXTURE_2D = 0x0DE1, GL_TEXTURE_COORD_ARRAY = 0x8078, GL_TEXTURE_ENV = 0x2300,
GL_TEXTURE_ENV_COLOR = 0x2201, GL_TEXTURE_ENV_MODE = 0x2200, GL_TEXTURE_MAG_FILTER = 0x2800, GL_TEXTURE_MIN_FILTER = 0x2801,
GL_TEXTURE_WRAP_S = 0x2802, GL_TEXTURE_WRAP_T = 0x2803, GL_TEXTURE0 = 0x84C0, GL_TEXTURE1 = 0x84C1,
GL_TEXTURE2 = 0x84C2, GL_TEXTURE3 = 0x84C3, GL_TEXTURE4 = 0x84C4, GL_TEXTURE5 = 0x84C5,
GL_TEXTURE6 = 0x84C6, GL_TEXTURE7 = 0x84C7, GL_TEXTURE8 = 0x84C8, GL_TEXTURE9 = 0x84C9,
GL_TEXTURE10 = 0x84CA, GL_TEXTURE11 = 0x84CB, GL_TEXTURE12 = 0x84CC, GL_TEXTURE13 = 0x84CD,
GL_TEXTURE14 = 0x84CE, GL_TEXTURE15 = 0x84CF, GL_TEXTURE16 = 0x84D0, GL_TEXTURE17 = 0x84D1,
GL_TEXTURE18 = 0x84D2, GL_TEXTURE19 = 0x84D3, GL_TEXTURE20 = 0x84D4, GL_TEXTURE21 = 0x84D5,
GL_TEXTURE22 = 0x84D6, GL_TEXTURE23 = 0x84D7, GL_TEXTURE24 = 0x84D8, GL_TEXTURE25 = 0x84D9,
GL_TEXTURE26 = 0x84DA, GL_TEXTURE27 = 0x84DB, GL_TEXTURE28 = 0x84DC, GL_TEXTURE29 = 0x84DD,
GL_TEXTURE30 = 0x84DE, GL_TEXTURE31 = 0x84DF, GL_TRIANGLE_FAN = 0x0006, GL_TRIANGLE_STRIP = 0x0005,
GL_TRIANGLES = 0x0004, GL_TRUE = 1, GL_UNPACK_ALIGNMENT = 0x0CF5, GL_UNSIGNED_BYTE = 0x1401,
GL_UNSIGNED_SHORT = 0x1403, GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033, GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034, GL_UNSIGNED_SHORT_5_6_5 = 0x8363,
GL_VENDOR = 0x1F00, GL_VERSION = 0x1F02, GL_VERTEX_ARRAY = 0x8074, GL_XOR = 0x1506,
GL_ZERO = 0
}
Public Member Functions
GL10 ()
GL10 (const GL10 &gl10)
virtual ~GL10 ()
GL10 & operator= (const GL10 &other)
void glActiveTexture (int32_t texture)
void glAlphaFunc (int32_t func, float ref)
void glAlphaFuncx (int32_t func, int32_t ref)
void glBindTexture (int32_t target, int32_t texture)
void glBlendFunc (int32_t sfactor, int32_t dfactor)
void glClear (int32_t mask)
void glClearColor (float red, float green, float blue, float alpha)
void glClearColorx (int32_t red, int32_t green, int32_t blue, int32_t alpha)
void glClearDepthf (float depth)
void glClearDepthx (int32_t depth)
void glClearStencil (int32_t s)
void glClientActiveTexture (int32_t texture)
void glColor4f (float red, float green, float blue, float alpha)
void glColor4x (int32_t red, int32_t green, int32_t blue, int32_t alpha)
void glColorMask (bool red, bool green, bool blue, bool alpha)
template<typename T >
void glColorPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
template<typename T >
void glCompressedTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const gaia::base::Array< T > &data)
template<typename T >
void glCompressedTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t imageSize, const gaia::base::Array< T > &data)
void glCopyTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border)
void glCopyTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height)
void glCullFace (int32_t mode)
void glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > &textures, int32_t offset)
void glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > &textures)
void glDepthFunc (int32_t func)
void glDepthMask (bool flag)
void glDepthRangef (float zNear, float zFar)
void glDepthRangex (int32_t zNear, int32_t zFar)
void glDisable (int32_t cap)
void glDisableClientState (int32_t array)
void glDrawArrays (int32_t mode, int32_t first, int32_t count)
template<typename T >
void glDrawElements (int32_t mode, int32_t count, int32_t type, const gaia::base::Array< T > &indices)
void glEnable (int32_t cap)
void glEnableClientState (int32_t array)
void glFinish ()
void glFlush ()
void glFogf (int32_t pname, float param)
void glFogfv (int32_t pname, const gaia::base::Array< float > &params)
void glFogfv (int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glFogx (int32_t pname, int32_t param)
void glFogxv (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glFogxv (int32_t pname, const gaia::base::Array< int32_t > &params)
void glFrontFace (int32_t mode)
void glFrustumf (float left, float right, float bottom, float top, float zNear, float zFar)
void glFrustumx (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
void glGenTextures (int32_t n, gaia::base::Array< uint32_t > *textures)
void glGenTextures (int32_t n, gaia::base::Array< uint32_t > *textures, int32_t offset)
int32_t glGetError ()
void glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > *params)
void glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
gaia::base::String glGetString (int32_t name)
void glHint (int32_t target, int32_t mode)
void glLightModelf (int32_t pname, float param)
void glLightModelfv (int32_t pname, const gaia::base::Array< float > &params)
void glLightModelfv (int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glLightModelx (int32_t pname, int32_t param)
void glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > &params)
void glLightf (int32_t light, int32_t pname, float param)
void glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > &params)
void glLightx (int32_t light, int32_t pname, int32_t param)
void glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > &params)
void glLineWidth (float width)
void glLineWidthx (int32_t width)
void glLoadIdentity ()
void glLoadMatrixf (const gaia::base::Array< float > &m, int32_t offset)
void glLoadMatrixf (const gaia::base::Array< float > &m)
void glLoadMatrixx (const gaia::base::Array< int32_t > &m)
void glLoadMatrixx (const gaia::base::Array< int32_t > &m, int32_t offset)
void glLogicOp (int32_t opcode)
void glMaterialf (int32_t face, int32_t pname, float param)
void glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > &params)
void glMaterialx (int32_t face, int32_t pname, int32_t param)
void glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > &params)
void glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glMatrixMode (int32_t mode)
void glMultMatrixf (const gaia::base::Array< float > &m, int32_t offset)
void glMultMatrixf (const gaia::base::Array< float > &m)
void glMultMatrixx (const gaia::base::Array< int32_t > &m)
void glMultMatrixx (const gaia::base::Array< int32_t > &m, int32_t offset)
void glMultiTexCoord4f (int32_t target, float s, float t, float r, float q)
void glMultiTexCoord4x (int32_t target, int32_t s, int32_t t, int32_t r, int32_t q)
void glNormal3f (float nx, float ny, float nz)
void glNormal3x (int32_t nx, int32_t ny, int32_t nz)
template<typename T >
void glNormalPointer (int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
void glOrthof (float left, float right, float bottom, float top, float zNear, float zFar)
void glOrthox (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
void glPixelStorei (int32_t pname, int32_t param)
void glPointSize (float size)
void glPointSizex (int32_t size)
void glPolygonOffset (float factor, float units)
void glPolygonOffsetx (int32_t factor, int32_t units)
void glPopMatrix ()
void glPushMatrix ()
template<typename T >
void glReadPixels (int32_t x, int32_t y, int32_t width, int32_t height, int32_t format, int32_t type, gaia::base::Array< T > *pixels)
void glRotatef (float angle, float x, float y, float z)
void glRotatex (int32_t angle, int32_t x, int32_t y, int32_t z)
void glSampleCoverage (float value, bool invert)
void glSampleCoveragex (int32_t value, bool invert)
void glScalef (float x, float y, float z)
void glScalex (int32_t x, int32_t y, int32_t z)
void glScissor (int32_t x, int32_t y, int32_t width, int32_t height)
void glShadeModel (int32_t mode)
void glStencilFunc (int32_t func, int32_t ref, int32_t mask)
void glStencilMask (int32_t mask)
void glStencilOp (int32_t fail, int32_t zfail, int32_t zpass)
template<typename T >
void glTexCoordPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
void glTexEnvf (int32_t target, int32_t pname, float param)
void glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params)
void glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glTexEnvx (int32_t target, int32_t pname, int32_t param)
void glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
template<typename T >
void glTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t format, int32_t type, const gaia::base::Array< T > &pixels)
void glTexParameterf (int32_t target, int32_t pname, float param)
void glTexParameterx (int32_t target, int32_t pname, int32_t param)
template<typename T >
void glTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t type, const gaia::base::Array< T > &pixels)
void glTranslatef (float x, float y, float z)
void glTranslatex (int32_t x, int32_t y, int32_t z)
template<typename T >
void glVertexPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
void glViewport (int32_t x, int32_t y, int32_t width, int32_t height)
Detailed Description
Definition at line 15 of file GL10.h.
Member Enumeration Documentation
enum gaia::core::GL10::GL10Macro
Enumerator:
GL_ADD
GL_ALIASED_LINE_WIDTH_RANGE
GL_ALIASED_POINT_SIZE_RANGE
GL_ALPHA
GL_ALPHA_BITS
GL_ALPHA_TEST
GL_ALWAYS
GL_AMBIENT
GL_AMBIENT_AND_DIFFUSE
GL_AND
GL_AND_INVERTED
GL_AND_REVERSE
GL_BACK
GL_BLEND
GL_BLUE_BITS
GL_BYTE
GL_CCW
GL_CLAMP_TO_EDGE
GL_CLEAR
GL_COLOR_ARRAY
GL_COLOR_BUFFER_BIT
GL_COLOR_LOGIC_OP
GL_COLOR_MATERIAL
GL_COMPRESSED_TEXTURE_FORMATS
GL_CONSTANT_ATTENUATION
GL_COPY
GL_COPY_INVERTED
GL_CULL_FACE
GL_CW
GL_DECAL
GL_DECR
GL_DEPTH_BITS
GL_DEPTH_BUFFER_BIT
GL_DEPTH_TEST
GL_DIFFUSE
GL_DITHER
GL_DONT_CARE
GL_DST_ALPHA
GL_DST_COLOR
GL_EMISSION
GL_EQUAL
GL_EQUIV
GL_EXP
GL_EXP2
GL_EXTENSIONS
GL_FALSE
GL_FASTEST
GL_FIXED
GL_FLAT
GL_FLOAT
GL_FOG
GL_FOG_COLOR
GL_FOG_DENSITY
GL_FOG_END
GL_FOG_HINT
GL_FOG_MODE
GL_FOG_START
GL_FRONT
GL_FRONT_AND_BACK
GL_GEQUAL
GL_GREATER
GL_GREEN_BITS
GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES
GL_IMPLEMENTATION_COLOR_READ_TYPE_OES
GL_INCR
GL_INVALID_ENUM
GL_INVALID_OPERATION
GL_INVALID_VALUE
GL_INVERT
GL_KEEP
GL_LEQUAL
GL_LESS
GL_LIGHT_MODEL_AMBIENT
GL_LIGHT_MODEL_TWO_SIDE
GL_LIGHT0
GL_LIGHT1
GL_LIGHT2
GL_LIGHT3
GL_LIGHT4
GL_LIGHT5
GL_LIGHT6
GL_LIGHT7
GL_LIGHTING
GL_LINE_LOOP
GL_LINE_SMOOTH
GL_LINE_SMOOTH_HINT
GL_LINE_STRIP
GL_LINEAR
GL_LINEAR_ATTENUATION
GL_LINEAR_MIPMAP_LINEAR
GL_LINEAR_MIPMAP_NEAREST
GL_LINES
GL_LUMINANCE
GL_LUMINANCE_ALPHA
GL_MAX_ELEMENTS_INDICES
GL_MAX_ELEMENTS_VERTICES
GL_MAX_LIGHTS
GL_MAX_MODELVIEW_STACK_DEPTH
GL_MAX_PROJECTION_STACK_DEPTH
GL_MAX_TEXTURE_SIZE
GL_MAX_TEXTURE_STACK_DEPTH
GL_MAX_TEXTURE_UNITS
GL_MAX_VIEWPORT_DIMS
GL_MODELVIEW
GL_MODULATE
GL_MULTISAMPLE
GL_NAND
GL_NEAREST
GL_NEAREST_MIPMAP_LINEAR
GL_NEAREST_MIPMAP_NEAREST
GL_NEVER
GL_NICEST
GL_NO_ERROR
GL_NOOP
GL_NOR
GL_NORMAL_ARRAY
GL_NORMALIZE
GL_NOTEQUAL
GL_NUM_COMPRESSED_TEXTURE_FORMATS
GL_ONE
GL_ONE_MINUS_DST_ALPHA
GL_ONE_MINUS_DST_COLOR
GL_ONE_MINUS_SRC_ALPHA
GL_ONE_MINUS_SRC_COLOR
GL_OR
GL_OR_INVERTED
GL_OR_REVERSE
GL_OUT_OF_MEMORY
GL_PACK_ALIGNMENT
GL_PALETTE4_R5_G6_B5_OES
GL_PALETTE4_RGB5_A1_OES
GL_PALETTE4_RGB8_OES
GL_PALETTE4_RGBA4_OES
GL_PALETTE4_RGBA8_OES
GL_PALETTE8_R5_G6_B5_OES
GL_PALETTE8_RGB5_A1_OES
GL_PALETTE8_RGB8_OES
GL_PALETTE8_RGBA4_OES
GL_PALETTE8_RGBA8_OES
GL_PERSPECTIVE_CORRECTION_HINT
GL_POINT_SMOOTH
GL_POINT_SMOOTH_HINT
GL_POINTS
GL_POINT_FADE_THRESHOLD_SIZE
GL_POINT_SIZE
GL_POLYGON_OFFSET_FILL
GL_POLYGON_SMOOTH_HINT
GL_POSITION
GL_PROJECTION
GL_QUADRATIC_ATTENUATION
GL_RED_BITS
GL_RENDERER
GL_REPEAT
GL_REPLACE
GL_RESCALE_NORMAL
GL_RGB
GL_RGBA
GL_SAMPLE_ALPHA_TO_COVERAGE
GL_SAMPLE_ALPHA_TO_ONE
GL_SAMPLE_COVERAGE
GL_SCISSOR_TEST
GL_SET
GL_SHININESS
GL_SHORT
GL_SMOOTH
GL_SMOOTH_LINE_WIDTH_RANGE
GL_SMOOTH_POINT_SIZE_RANGE
GL_SPECULAR
GL_SPOT_CUTOFF
GL_SPOT_DIRECTION
GL_SPOT_EXPONENT
GL_SRC_ALPHA
GL_SRC_ALPHA_SATURATE
GL_SRC_COLOR
GL_STACK_OVERFLOW
GL_STACK_UNDERFLOW
GL_STENCIL_BITS
GL_STENCIL_BUFFER_BIT
GL_STENCIL_TEST
GL_SUBPIXEL_BITS
GL_TEXTURE
GL_TEXTURE_2D
GL_TEXTURE_COORD_ARRAY
GL_TEXTURE_ENV
GL_TEXTURE_ENV_COLOR
GL_TEXTURE_ENV_MODE
GL_TEXTURE_MAG_FILTER
GL_TEXTURE_MIN_FILTER
GL_TEXTURE_WRAP_S
GL_TEXTURE_WRAP_T
GL_TEXTURE0
GL_TEXTURE1
GL_TEXTURE2
GL_TEXTURE3
GL_TEXTURE4
GL_TEXTURE5
GL_TEXTURE6
GL_TEXTURE7
GL_TEXTURE8
GL_TEXTURE9
GL_TEXTURE10
GL_TEXTURE11
GL_TEXTURE12
GL_TEXTURE13
GL_TEXTURE14
GL_TEXTURE15
GL_TEXTURE16
GL_TEXTURE17
GL_TEXTURE18
GL_TEXTURE19
GL_TEXTURE20
GL_TEXTURE21
GL_TEXTURE22
GL_TEXTURE23
GL_TEXTURE24
GL_TEXTURE25
GL_TEXTURE26
GL_TEXTURE27
GL_TEXTURE28
GL_TEXTURE29
GL_TEXTURE30
GL_TEXTURE31
GL_TRIANGLE_FAN
GL_TRIANGLE_STRIP
GL_TRIANGLES
GL_TRUE
GL_UNPACK_ALIGNMENT
GL_UNSIGNED_BYTE
GL_UNSIGNED_SHORT
GL_UNSIGNED_SHORT_4_4_4_4
GL_UNSIGNED_SHORT_5_5_5_1
GL_UNSIGNED_SHORT_5_6_5
GL_VENDOR
GL_VERSION
GL_VERTEX_ARRAY
GL_XOR
GL_ZERO
Definition at line 17 of file GL10.h.
Constructor & Destructor Documentation
gaia::core::GL10::GL10 ()
gaia::core::GL10::GL10 (const GL10 & gl10)
virtual gaia::core::GL10::~GL10 () [virtual]
Member Function Documentation
void gaia::core::GL10::glActiveTexture (int32_t texture)
void gaia::core::GL10::glAlphaFunc (int32_t func, float ref)
void gaia::core::GL10::glAlphaFuncx (int32_t func, int32_t ref)
void gaia::core::GL10::glBindTexture (int32_t target, int32_t texture)
void gaia::core::GL10::glBlendFunc (int32_t sfactor, int32_t dfactor)
void gaia::core::GL10::glClear (int32_t mask)
void gaia::core::GL10::glClearColor (float red, float green, float blue, float alpha)
void gaia::core::GL10::glClearColorx (int32_t red, int32_t green, int32_t blue, int32_t alpha)
void gaia::core::GL10::glClearDepthf (float depth)
void gaia::core::GL10::glClearDepthx (int32_t depth)
void gaia::core::GL10::glClearStencil (int32_t s)
void gaia::core::GL10::glClientActiveTexture (int32_t texture)
void gaia::core::GL10::glColor4f (float red, float green, float blue, float alpha)
void gaia::core::GL10::glColor4x (int32_t red, int32_t green, int32_t blue, int32_t alpha)
void gaia::core::GL10::glColorMask (bool red, bool green, bool blue, bool alpha)
template<typename T > void gaia::core::GL10::glColorPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 308 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
template<typename T > void gaia::core::GL10::glCompressedTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const gaia::base::Array< T > & data) [inline]
Definition at line 313 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
template<typename T > void gaia::core::GL10::glCompressedTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t imageSize, const gaia::base::Array< T > & data) [inline]
Definition at line 318 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glCopyTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border)
void gaia::core::GL10::glCopyTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height)
void gaia::core::GL10::glCullFace (int32_t mode)
void gaia::core::GL10::glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > & textures, int32_t offset)
void gaia::core::GL10::glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > & textures)
void gaia::core::GL10::glDepthFunc (int32_t func)
void gaia::core::GL10::glDepthMask (bool flag)
void gaia::core::GL10::glDepthRangef (float zNear, float zFar)
void gaia::core::GL10::glDepthRangex (int32_t zNear, int32_t zFar)
void gaia::core::GL10::glDisable (int32_t cap)
void gaia::core::GL10::glDisableClientState (int32_t array)
void gaia::core::GL10::glDrawArrays (int32_t mode, int32_t first, int32_t count)
template<typename T > void gaia::core::GL10::glDrawElements (int32_t mode, int32_t count, int32_t type, const gaia::base::Array< T > & indices) [inline]
Definition at line 347 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glEnable (int32_t cap)
void gaia::core::GL10::glEnableClientState (int32_t array)
void gaia::core::GL10::glFinish ()
void gaia::core::GL10::glFlush ()
void gaia::core::GL10::glFogf (int32_t pname, float param)
void gaia::core::GL10::glFogfv (int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL10::glFogfv (int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL10::glFogx (int32_t pname, int32_t param)
void gaia::core::GL10::glFogxv (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL10::glFogxv (int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL10::glFrontFace (int32_t mode)
void gaia::core::GL10::glFrustumf (float left, float right, float bottom, float top, float zNear, float zFar)
void gaia::core::GL10::glFrustumx (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
void gaia::core::GL10::glGenTextures (int32_t n, gaia::base::Array< uint32_t > * textures)
void gaia::core::GL10::glGenTextures (int32_t n, gaia::base::Array< uint32_t > * textures, int32_t offset)
int32_t gaia::core::GL10::glGetError ()
void gaia::core::GL10::glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL10::glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
gaia::base::String gaia::core::GL10::glGetString (int32_t name)
void gaia::core::GL10::glHint (int32_t target, int32_t mode)
void gaia::core::GL10::glLightf (int32_t light, int32_t pname, float param)
void gaia::core::GL10::glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL10::glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL10::glLightModelf (int32_t pname, float param)
void gaia::core::GL10::glLightModelfv (int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL10::glLightModelfv (int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL10::glLightModelx (int32_t pname, int32_t param)
void gaia::core::GL10::glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL10::glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL10::glLightx (int32_t light, int32_t pname, int32_t param)
void gaia::core::GL10::glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL10::glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL10::glLineWidth (float width)
void gaia::core::GL10::glLineWidthx (int32_t width)
void gaia::core::GL10::glLoadIdentity ()
void gaia::core::GL10::glLoadMatrixf (const gaia::base::Array< float > & m, int32_t offset)
void gaia::core::GL10::glLoadMatrixf (const gaia::base::Array< float > & m)
void gaia::core::GL10::glLoadMatrixx (const gaia::base::Array< int32_t > & m)
void gaia::core::GL10::glLoadMatrixx (const gaia::base::Array< int32_t > & m, int32_t offset)
void gaia::core::GL10::glLogicOp (int32_t opcode)
void gaia::core::GL10::glMaterialf (int32_t face, int32_t pname, float param)
void gaia::core::GL10::glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL10::glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL10::glMaterialx (int32_t face, int32_t pname, int32_t param)
void gaia::core::GL10::glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL10::glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL10::glMatrixMode (int32_t mode)
void gaia::core::GL10::glMultiTexCoord4f (int32_t target, float s, float t, float r, float q)
void gaia::core::GL10::glMultiTexCoord4x (int32_t target, int32_t s, int32_t t, int32_t r, int32_t q)
void gaia::core::GL10::glMultMatrixf (const gaia::base::Array< float > & m, int32_t offset)
void gaia::core::GL10::glMultMatrixf (const gaia::base::Array< float > & m)
void gaia::core::GL10::glMultMatrixx (const gaia::base::Array< int32_t > & m)
void gaia::core::GL10::glMultMatrixx (const gaia::base::Array< int32_t > & m, int32_t offset)
void gaia::core::GL10::glNormal3f (float nx, float ny, float nz)
void gaia::core::GL10::glNormal3x (int32_t nx, int32_t ny, int32_t nz)
template<typename T > void gaia::core::GL10::glNormalPointer (int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 462 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glOrthof (float left, float right, float bottom, float top, float zNear, float zFar)
void gaia::core::GL10::glOrthox (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
void gaia::core::GL10::glPixelStorei (int32_t pname, int32_t param)
void gaia::core::GL10::glPointSize (float size)
void gaia::core::GL10::glPointSizex (int32_t size)
void gaia::core::GL10::glPolygonOffset (float factor, float units)
void gaia::core::GL10::glPolygonOffsetx (int32_t factor, int32_t units)
void gaia::core::GL10::glPopMatrix ()
void gaia::core::GL10::glPushMatrix ()
template<typename T > void gaia::core::GL10::glReadPixels (int32_t x, int32_t y, int32_t width, int32_t height, int32_t format, int32_t type, gaia::base::Array< T > * pixels) [inline]
Definition at line 485 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glRotatef (float angle, float x, float y, float z)
void gaia::core::GL10::glRotatex (int32_t angle, int32_t x, int32_t y, int32_t z)
void gaia::core::GL10::glSampleCoverage (float value, bool invert)
void gaia::core::GL10::glSampleCoveragex (int32_t value, bool invert)
void gaia::core::GL10::glScalef (float x, float y, float z)
void gaia::core::GL10::glScalex (int32_t x, int32_t y, int32_t z)
void gaia::core::GL10::glScissor (int32_t x, int32_t y, int32_t width, int32_t height)
void gaia::core::GL10::glShadeModel (int32_t mode)
void gaia::core::GL10::glStencilFunc (int32_t func, int32_t ref, int32_t mask)
void gaia::core::GL10::glStencilMask (int32_t mask)
void gaia::core::GL10::glStencilOp (int32_t fail, int32_t zfail, int32_t zpass)
template<typename T > void gaia::core::GL10::glTexCoordPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 512 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glTexEnvf (int32_t target, int32_t pname, float param)
void gaia::core::GL10::glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL10::glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL10::glTexEnvx (int32_t target, int32_t pname, int32_t param)
void gaia::core::GL10::glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL10::glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
template<typename T > void gaia::core::GL10::glTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t format, int32_t type, const gaia::base::Array< T > & pixels) [inline]
Definition at line 529 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glTexParameterf (int32_t target, int32_t pname, float param)
void gaia::core::GL10::glTexParameterx (int32_t target, int32_t pname, int32_t param)
template<typename T > void gaia::core::GL10::glTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t type, const gaia::base::Array< T > & pixels) [inline]
Definition at line 538 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glTranslatef (float x, float y, float z)
void gaia::core::GL10::glTranslatex (int32_t x, int32_t y, int32_t z)
template<typename T > void gaia::core::GL10::glVertexPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 547 of file GL10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL10::glViewport (int32_t x, int32_t y, int32_t width, int32_t height)
GL10& gaia::core::GL10::operator= (const GL10 & other)
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/GL10.h