gaia::core::Parcelable Class Reference
gaia::core::Parcelable Class Reference
Generic wrapper that holds classes whose instances can be written to and restored from a Parcel.
#include <Parcelable.h>
Classes
struct Creator
struct Writer
Public Member Functions
Parcelable ()
Create a null Parcelable.
Parcelable (ParcelableProxy *proxy)
template<class T >
Parcelable (T *ptr, bool takeOwnership=false)
Create a parcelable to hold the object.
Parcelable (const Parcelable &o)
~Parcelable ()
Parcelable & operator= (const Parcelable &o)
bool isNull () const
Return if the held object is NULL.
template<class T >
T * getN () const
Create a copy of the held object passed in constructor.
void writeToParcel (Parcel *dest, int32_t flags) const
Call writeToParcel() of the held object.
ParcelableProxy * getProxy () const
Private Member Functions
void construct (const char *name, Writer *writer)
void * getInner (const char *name, const Creator &creator) const
Static Private Member Functions
template<class T >
static const char * getName (type_check< const char *(*)(),&T::PARCELABLE_NAME > *)
template<class T >
static const char * getName (...)
Private Attributes
ParcelableProxy * mpProxy
Detailed Description
Generic wrapper that holds classes whose instances can be written to and restored from a Parcel.
Classes that can be wrapped by Parcelable should implement two functions:
 void writeToParcel(gaia::core::Parcel* dest, int32_t flags);
 static T* createFromParcelN(const gaia::core::Parcel& source);
 struct MySavedState {
     int32_t mInt;
     gaia::base::String mString;
     double mDouble;
     void writeToParcel(gaia::core::Parcel* dest, int32_t flags) {
         dest->writeInt(mInt);
         dest->writeString(mString);
         dest->writeDouble(mDouble);
     }
     static MySavedState* createFromParcelN(const gaia::core::Parcel& source) {
         MySavedState* me = new MySavedState();
         me->mInt = source.readInt();
         me->mString = source.readString();
         me->mDouble = source.readDouble();
         return me;
     }
 };
 MySavedState* state = new MySavedState();
 Demand demand;
 demand.putParcelableExtra("SAVE", Parcelable(state));
 Parcelable parcelable = demand.getParcelableExtra("SAVE");
 MySavedState* state2 = parcelable.getN<MySavedState>();
If you want to give your class a custom name when writing into parcel, please implement a static function in your class:
 static const char* PARCELABLE_NAME() {
     return "gaia::MyCurtomClassName";
 }
Definition at line 62 of file Parcelable.h.
Constructor & Destructor Documentation
gaia::core::Parcelable::Parcelable ()
Create a null Parcelable.
gaia::core::Parcelable::Parcelable (ParcelableProxy * proxy) [explicit]
template<class T > gaia::core::Parcelable::Parcelable (T * ptr, bool takeOwnership = false)
Create a parcelable to hold the object.
If takeOwnership is true, lifetime of held object is managed by framework.
Definition at line 135 of file Parcelable.h.
References construct(), and writeToParcel().
gaia::core::Parcelable::Parcelable (const Parcelable & o)
gaia::core::Parcelable::~Parcelable ()
Member Function Documentation
void gaia::core::Parcelable::construct (const char * name, Writer * writer) [private]
Referenced by Parcelable().
void* gaia::core::Parcelable::getInner (const char * name, const Creator & creator) const [private]
Referenced by getN().
template<class T > T * gaia::core::Parcelable::getN () const
Create a copy of the held object passed in constructor.
Return NULL if T is not the same as the held object.
Definition at line 165 of file Parcelable.h.
References getInner().
template<class T > static const char* gaia::core::Parcelable::getName (type_check< const char *(*)(),&T::PARCELABLE_NAME > *) [inline, static, private]
Definition at line 110 of file Parcelable.h.
template<class T > static const char* gaia::core::Parcelable::getName (...) [inline, static, private]
Definition at line 116 of file Parcelable.h.
ParcelableProxy* gaia::core::Parcelable::getProxy () const
bool gaia::core::Parcelable::isNull () const
Return if the held object is NULL.
Parcelable& gaia::core::Parcelable::operator= (const Parcelable & o)
void gaia::core::Parcelable::writeToParcel (Parcel * dest, int32_t flags) const
Call writeToParcel() of the held object.
The held object should not be NULL when calling this function. Caller should check by using isNull() before calling this function.
Referenced by Parcelable().
Member Data Documentation
ParcelableProxy* gaia::core::Parcelable::mpProxy [private]
Definition at line 125 of file Parcelable.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Parcelable.h