gaia::testing::InstrumentationTestCase< TestFixture > Class Template Reference
gaia::testing::InstrumentationTestCase< TestFixture > Class Template Reference
A test case that has access to gaia::core::Instrumentation.
#include <InstrumentationTestCase.h>
Public Member Functions
InstrumentationTestCase ()
virtual ~InstrumentationTestCase ()
Instrumentation * getInstrumentation ()
Inheritors can access the instrumentation using this.
gaia::core::Page * launchPage (const gaia::base::String &pkg, const gaia::base::String &pageCls, gaia::core::Persistence *extras)
Utility method for launching an page.
gaia::core::Page * launchPageWithDemand (const gaia::base::String &pkg, const gaia::base::String &pageCls, gaia::core::Demand *demand)
Utility method for launching an page with a specific Demand.
void runTestOnUiThread (gaia::core::WorkItem *workItem)
Helper for running portions of a test on the UI thread.
void sendKeys (int32_t count, int32_t *keys)
Sends a series of key events through instrumentation and waits for idle.
void sendRepeatedKeys (int32_t count, int32_t *keys)
Sends a series of key events through instrumentation and waits for idle.
Protected Member Functions
virtual void SetUp ()
Sets up the test fixture.
Private Attributes
Instrumentation * mpInstrumentation
Detailed Description
template<class TestFixture>
class gaia::testing::InstrumentationTestCase< TestFixture >
A test case that has access to gaia::core::Instrumentation.
Inherited by gaia::testing::SingleLaunchPageTestCase.
TestFixture is extend from gtest/testing/test
Definition at line 40 of file InstrumentationTestCase.h.
Constructor & Destructor Documentation
template<class TestFixture > gaia::testing::InstrumentationTestCase< TestFixture >::InstrumentationTestCase ()
Definition at line 141 of file InstrumentationTestCase.h.
template<class TestFixture > gaia::testing::InstrumentationTestCase< TestFixture >::~InstrumentationTestCase () [virtual]
Definition at line 146 of file InstrumentationTestCase.h.
Member Function Documentation
template<class TestFixture > Instrumentation* gaia::testing::InstrumentationTestCase< TestFixture >::getInstrumentation () [inline]
Inheritors can access the instrumentation using this.
Returns:
instrumentation
Definition at line 52 of file InstrumentationTestCase.h.
References gaia::testing::InstrumentationTestCase< TestFixture >::mpInstrumentation.
template<class TestFixture > Page * gaia::testing::InstrumentationTestCase< TestFixture >::launchPage (const gaia::base::String & pkg, const gaia::base::String & pageCls, gaia::core::Persistence * extras)
Utility method for launching an page.
The gaia::core::Demand used to launch the Page is: action = Demand#ACTION_MAIN() extras = null, unless a custom Persistence is provided here All other fields are null or empty.
NOTE: The parameter pkg must refer to the package identifier of the package hosting the page to be launched, which is specified in the gaia.xml file.
Parameters:
pkg The package hosting the page to be launched.
pageCls The page class to launch.
extras Optional extra stuff to pass to the page.
Returns:
The page, or null if non launched.
Definition at line 153 of file InstrumentationTestCase.h.
References gaia::core::Demand::ACTION_MAIN(), GLOGENTRY, and gaia::core::Demand::putExtras().
template<class TestFixture > Page * gaia::testing::InstrumentationTestCase< TestFixture >::launchPageWithDemand (const gaia::base::String & pkg, const gaia::base::String & pageCls, gaia::core::Demand * demand)
Utility method for launching an page with a specific Demand.
NOTE: The parameter pkg must refer to the package identifier of the package hosting the page to be launched, which is specified in the gaia.xml file.
Parameters:
pkg The package hosting the page to be launched.
pageCls The page class to launch.
demand The Demand to launch with
Returns:
The page, or null if non launched.
Definition at line 170 of file InstrumentationTestCase.h.
References GLOGENTRY, gaia::core::Demand::setClassName(), gaia::core::Instrumentation::startPageSync(), and gaia::core::Instrumentation::waitForIdleSync().
template<class TestFixture > void gaia::testing::InstrumentationTestCase< TestFixture >::runTestOnUiThread (gaia::core::WorkItem * workItem)
Helper for running portions of a test on the UI thread.
Use this method if you need to switch in and out of the UI thread to perform your test.
Parameters:
workItem runnable containing test code in the gaia::core::WorkItem#run() method
Definition at line 181 of file InstrumentationTestCase.h.
template<class TestFixture > void gaia::testing::InstrumentationTestCase< TestFixture >::sendKeys (int32_t count, int32_t * keys)
Sends a series of key events through instrumentation and waits for idle.
For instance: sendKeys(KEYCODE_DPAD_LEFT, KEYCODE_DPAD_CENTER).
Parameters:
count The count of keys.
keys The series of key codes to send through instrumentation.
Definition at line 186 of file InstrumentationTestCase.h.
References GLOGENTRY, gaia::core::Instrumentation::sendKeyDownUpSync(), and gaia::core::Instrumentation::waitForIdleSync().
template<class TestFixture > void gaia::testing::InstrumentationTestCase< TestFixture >::sendRepeatedKeys (int32_t count, int32_t * keys)
Sends a series of key events through instrumentation and waits for idle.
Each key code must be preceded by the number of times the key code must be sent. For instance: sendRepeatedKeys(1, KEYCODE_DPAD_CENTER, 2, KEYCODE_DPAD_LEFT).
Parameters:
count The count of keys.
keys The series of key repeats and codes to send through instrumentation.
Definition at line 198 of file InstrumentationTestCase.h.
References GLOGENTRY, gaia::core::Instrumentation::sendKeyDownUpSync(), and gaia::core::Instrumentation::waitForIdleSync().
template<class TestFixture > void gaia::testing::InstrumentationTestCase< TestFixture >::SetUp () [protected, virtual]
Sets up the test fixture.
Definition at line 149 of file InstrumentationTestCase.h.
Member Data Documentation
template<class TestFixture > Instrumentation* gaia::testing::InstrumentationTestCase< TestFixture >::mpInstrumentation [private]
Definition at line 42 of file InstrumentationTestCase.h.
Referenced by gaia::testing::InstrumentationTestCase< TestFixture >::getInstrumentation().
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/testing/InstrumentationTestCase.h