gaia::core::Export< CLASS, Delegate > Class Template Reference
gaia::core::Export< CLASS, Delegate > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static Delegate * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, Delegate >
Definition at line 251 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, Delegate >::Export () [private]
Definition at line 275 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, Delegate >::constructor () [static, private]
Definition at line 279 of file Export.h.
References gaia::core::COMPONENT_DELEGATE, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, Delegate >::destructor () [static, private]
Definition at line 285 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > Delegate * gaia::core::Export< CLASS, Delegate >::maker () [static, private]
Definition at line 290 of file Export.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/Export.h