gaia::core::Export< CLASS, gaia::ui::PreferenceFragment > Class Template Reference
gaia::core::Export< CLASS, gaia::ui::PreferenceFragment > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static
gaia::ui::PreferenceFragment * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >
Definition at line 592 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::Export () [private]
Definition at line 615 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::constructor () [static, private]
Definition at line 619 of file Export.h.
References gaia::core::COMPONENT_PREFERENCEFRAGMENT, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::destructor () [static, private]
Definition at line 627 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > gaia::ui::PreferenceFragment * gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::maker () [static, private]
Definition at line 634 of file Export.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/Export.h