gaia::core::ComponentLoader Class Reference
gaia::core::ComponentLoader Class Reference
Public Member Functions
template<class BASE >
BASE * newInstance (const char *classname, ArgsAdaptor *argsAdaptor)
ComponentType getType (const char *classname)
Return object type.
Private Member Functions
ComponentLoader ()
~ComponentLoader ()
void setToUnLoadLibrary ()
void registerComponent (ComponentType type, const char *classname, void *maker)
void unregisterComponent (const char *classname)
template<class BASE >
BASE * newInstance (const char *classname)
void loadLibraries (const char *path, bool recursive=false)
void unloadLibraries (const char *path, bool recursive=false)
void * getMaker (ComponentType type, const char *classname)
Static Private Member Functions
static ComponentLoader * getDefault ()
Private Attributes
bool mIsUnloadLibrary
Detailed Description
Definition at line 80 of file ComponentLoader.h.
Constructor & Destructor Documentation
gaia::core::ComponentLoader::ComponentLoader () [private]
gaia::core::ComponentLoader::~ComponentLoader () [private]
Member Function Documentation
static ComponentLoader* gaia::core::ComponentLoader::getDefault () [static, private]
Referenced by gaia::core::Export< CLASS, BASE >::constructor(), gaia::core::Export< CLASS, PersistentPage >::constructor(), gaia::core::Export< CLASS, Page >::constructor(), gaia::core::Export< CLASS, Screenlet >::constructor(), gaia::core::Export< CLASS, Delegate >::constructor(), gaia::core::Export< CLASS, DemandDelegate >::constructor(), gaia::core::Export< CLASS, View >::constructor(), gaia::core::Export< CLASS, gaia::content::ContentProvider >::constructor(), gaia::core::Export< CLASS, Subscriber >::constructor(), gaia::core::Export< CLASS, Fragment >::constructor(), gaia::core::Export< CLASS, gaia::ui::PreferencePage >::constructor(), gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::constructor(), gaia::core::Export< CLASS, gaia::core::MultiWindow >::constructor(), gaia::core::Export< CLASS, gaia::core::Widget >::constructor(), gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::constructor(), gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::CreateDelegate(), gaia::core::Export< CLASS, BASE >::destructor(), gaia::core::Export< CLASS, PersistentPage >::destructor(), gaia::core::Export< CLASS, Page >::destructor(), gaia::core::Export< CLASS, Screenlet >::destructor(), gaia::core::Export< CLASS, Delegate >::destructor(), gaia::core::Export< CLASS, DemandDelegate >::destructor(), gaia::core::Export< CLASS, View >::destructor(), gaia::core::Export< CLASS, gaia::content::ContentProvider >::destructor(), gaia::core::Export< CLASS, Subscriber >::destructor(), gaia::core::Export< CLASS, Fragment >::destructor(), gaia::core::Export< CLASS, gaia::ui::PreferencePage >::destructor(), gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::destructor(), gaia::core::Export< CLASS, gaia::core::MultiWindow >::destructor(), gaia::core::Export< CLASS, gaia::core::Widget >::destructor(), gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::destructor(), gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::SetUp(), and gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::TearDown().
void* gaia::core::ComponentLoader::getMaker (ComponentType type, const char * classname) [private]
Referenced by newInstance().
ComponentType gaia::core::ComponentLoader::getType (const char * classname)
Return object type.
void gaia::core::ComponentLoader::loadLibraries (const char * path, bool recursive = false) [private]
Parameters:
path accepts either regular file or directory.
recursive only take effect when path is directory.
Referenced by gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::SetUp().
Fragment * gaia::core::ComponentLoader::newInstance< Fragment > (const char * classname) [private]
Definition at line 142 of file ComponentLoader.h.
References gaia::core::COMPONENT_UNKNOWN, and getMaker().
template<class BASE > BASE* gaia::core::ComponentLoader::newInstance (const char * classname, ArgsAdaptor * argsAdaptor)
void gaia::core::ComponentLoader::registerComponent (ComponentType type, const char * classname, void * maker) [private]
Referenced by gaia::core::Export< CLASS, BASE >::constructor(), gaia::core::Export< CLASS, PersistentPage >::constructor(), gaia::core::Export< CLASS, Page >::constructor(), gaia::core::Export< CLASS, Screenlet >::constructor(), gaia::core::Export< CLASS, Delegate >::constructor(), gaia::core::Export< CLASS, DemandDelegate >::constructor(), gaia::core::Export< CLASS, View >::constructor(), gaia::core::Export< CLASS, gaia::content::ContentProvider >::constructor(), gaia::core::Export< CLASS, Subscriber >::constructor(), gaia::core::Export< CLASS, Fragment >::constructor(), gaia::core::Export< CLASS, gaia::ui::PreferencePage >::constructor(), gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::constructor(), gaia::core::Export< CLASS, gaia::core::MultiWindow >::constructor(), gaia::core::Export< CLASS, gaia::core::Widget >::constructor(), and gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::constructor().
void gaia::core::ComponentLoader::setToUnLoadLibrary () [private]
void gaia::core::ComponentLoader::unloadLibraries (const char * path, bool recursive = false) [private]
Parameters:
path accepts either regular file or directory.
recursive only take effect when path is directory.
Referenced by gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::TearDown().
void gaia::core::ComponentLoader::unregisterComponent (const char * classname) [private]
Referenced by gaia::core::Export< CLASS, BASE >::destructor(), gaia::core::Export< CLASS, PersistentPage >::destructor(), gaia::core::Export< CLASS, Page >::destructor(), gaia::core::Export< CLASS, Screenlet >::destructor(), gaia::core::Export< CLASS, Delegate >::destructor(), gaia::core::Export< CLASS, DemandDelegate >::destructor(), gaia::core::Export< CLASS, View >::destructor(), gaia::core::Export< CLASS, gaia::content::ContentProvider >::destructor(), gaia::core::Export< CLASS, Subscriber >::destructor(), gaia::core::Export< CLASS, Fragment >::destructor(), gaia::core::Export< CLASS, gaia::ui::PreferencePage >::destructor(), gaia::core::Export< CLASS, gaia::ui::PreferenceFragment >::destructor(), gaia::core::Export< CLASS, gaia::core::MultiWindow >::destructor(), gaia::core::Export< CLASS, gaia::core::Widget >::destructor(), and gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::destructor().
Member Data Documentation
bool gaia::core::ComponentLoader::mIsUnloadLibrary [private]
Definition at line 138 of file ComponentLoader.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/ComponentLoader.h