gaia::base Namespace Reference
gaia::base Namespace Reference
Classes
class Array
Implements array to replace C-style array.
class ArrayImpl
Implements array data structure and its operation methods.
class ByteArray
class CharSequence
This interface represents an ordered set of characters and defines the methods to probe them.
class EnumBase
class HashMap
Implements hashmap data structure and operation functions.
class HashMapImpl
class HashSet
Implements hashset data structure and operation methods.
class List
The class implements circular bi-directional linked list data structure.
class ListImpl
Implements list data structure.
class LruCacheKeyImpl
class LruCacheNode
class LruCacheImpl
class SharedBuffer
class String
A String is represented by array of UTF-16 values, such that Unicode supplementary characters (code points) are stored/encoded as surrogate pairs via Unicode code units (char).
class StringArray
This an array to contain String object.
struct trait_trivial_ctor
struct trait_trivial_dtor
struct trait_trivial_copy
struct trait_trivial_move
struct trait_pointer
struct trait_pointer< T * >
struct trait_trivial_move< sp< T > >
struct trait_trivial_move< wp< T > >
struct traits
struct aggregate_traits
struct key_value_pair_t
struct trait_trivial_ctor< key_value_pair_t< K, V > >
struct trait_trivial_dtor< key_value_pair_t< K, V > >
struct trait_trivial_copy< key_value_pair_t< K, V > >
struct trait_trivial_move< key_value_pair_t< K, V > >
class Vector
This class implements the vector data structure.
class Vector2D
This is 2 dimension Vector.
class VectorImpl
Implements vector data structure equipped with copy-on-write mechanism.
Enumerations
enum {
SUCCESS = 0, OK = 0, NO_ERROR = 0, UNKNOWN_ERROR = 0x80000000,
NO_MEMORY = -1, INVALID_OPERATION = -2, BAD_VALUE = -3, BAD_TYPE = -4,
NAME_NOT_FOUND = -5, PERMISSION_DENIED = -6, NO_INIT = -7, ALREADY_EXISTS = -8,
DEAD_OBJECT = -9, FAILED_TRANSACTION = -10, JPARKS_BROKE_IT = -11, BAD_INDEX = -12,
NOT_ENOUGH_DATA = -13, WOULD_BLOCK = -14, TIMED_OUT = -15, UNKNOWN_TRANSACTION = -16
}
enum LOGLEVEL {
LOGVER = 1, LOGDBG = 2, LOGINFO = 3, LOGWARN = 4,
LOGER = 5
}
Functions
template<class U >
bool arraycopy (const Array< U > &src, size_t srcPos, Array< U > &dst, size_t dstPos, size_t length)
int32_t GetLastError ()
Get last error in current thread.
void SetLastError (int32_t errorCode)
Set error in current thread.
void __gaia_currentPackageName__ ()
char * __gaia_getPackageName__ ()
bool __gaia_bFirstGet__ ()
bool __gaia_bGetPackageName__ ()
void __gaia_glog__ (const char *__logtag, LOGLEVEL level, const char *__format,...)
void __gaia_glogstart__ (const char *__pattern, const char *__object)
void __gaia_glogstop__ (const char *__pattern, const char *__object)
void __gaia_glogonce__ (const char *__pattern, const char *__object, const char *__measure)
BASIC_TYPES_HASHCODE (char) BASIC_TYPES_HASHCODE(uint8_t) BASIC_TYPES_HASHCODE(int16_t) BASIC_TYPES_HASHCODE(uint16_t) BASIC_TYPES_HASHCODE(int32_t) BASIC_TYPES_HASHCODE(uint32_t) BASIC_TYPES_HASHCODE(int64_t) BASIC_TYPES_HASHCODE(uint64_t) BASIC_TYPES_HASHCODE(float) BASIC_TYPES_HASHCODE(double) template< class T > inline size_t hashCode(const T *key)
size_t hash_string (const char *__s)
template<>
size_t hashCode (const char *key)
bool operator== (const char *s1, const String &s2)
bool operator!= (const char *s1, const String &s2)
String operator+ (const String &s1, const String &s2)
String operator+ (const String &s1, const char *s2)
String operator+ (const char *s1, const String &s2)
size_t hashCode (const String &key)
GAIA_BASIC_TYPES_TRAITS (void) GAIA_BASIC_TYPES_TRAITS(bool) GAIA_BASIC_TYPES_TRAITS(char) GAIA_BASIC_TYPES_TRAITS(uint8_t) GAIA_BASIC_TYPES_TRAITS(int16_t) GAIA_BASIC_TYPES_TRAITS(uint16_t) GAIA_BASIC_TYPES_TRAITS(int32_t) GAIA_BASIC_TYPES_TRAITS(uint32_t) GAIA_BASIC_TYPES_TRAITS(int64_t) GAIA_BASIC_TYPES_TRAITS(uint64_t) GAIA_BASIC_TYPES_TRAITS(float) GAIA_BASIC_TYPES_TRAITS(double) template< typename TYPE > inline int32_t strictly_order_type(const TYPE &lhs
Enumeration Type Documentation
anonymous enum
Enumerator:
SUCCESS
OK
NO_ERROR
UNKNOWN_ERROR
NO_MEMORY
INVALID_OPERATION
BAD_VALUE
BAD_TYPE
NAME_NOT_FOUND
PERMISSION_DENIED
NO_INIT
ALREADY_EXISTS
DEAD_OBJECT
FAILED_TRANSACTION
JPARKS_BROKE_IT
BAD_INDEX
NOT_ENOUGH_DATA
WOULD_BLOCK
TIMED_OUT
UNKNOWN_TRANSACTION
Definition at line 24 of file gerrcode.h.
enum gaia::base::LOGLEVEL
Enumerator:
LOGVER
LOGDBG
LOGINFO
LOGWARN
LOGER
Definition at line 23 of file gloger.h.
Function Documentation
bool gaia::base::__gaia_bFirstGet__ ()
bool gaia::base::__gaia_bGetPackageName__ ()
void gaia::base::__gaia_currentPackageName__ ()
char* gaia::base::__gaia_getPackageName__ ()
void gaia::base::__gaia_glog__ (const char * __logtag, LOGLEVEL level, const char * __format, ...)
Referenced by __GaiaCallLog__::__GaiaCallLog__(), and __GaiaCallLog__::~__GaiaCallLog__().
void gaia::base::__gaia_glogonce__ (const char * __pattern, const char * __object, const char * __measure)
void gaia::base::__gaia_glogstart__ (const char * __pattern, const char * __object)
void gaia::base::__gaia_glogstop__ (const char * __pattern, const char * __object)
template<class U > bool gaia::base::arraycopy (const Array< U > & src, size_t srcPos, Array< U > & dst, size_t dstPos, size_t length) [inline]
Parameters:
src Source array to be copied.
srcPos Location starts to copy.
dst Desetination to copy to.
dstPos Location to put copied datum.
length Nubmer of datum to be copied
Returns:
True if datum is copied. False if the specified range is incorrect.
Definition at line 226 of file Array.h.
References gaia::base::ArrayImpl::arraycopy().
Referenced by gaia::base::Array< TYPE >::clone().
gaia::base::BASIC_TYPES_HASHCODE (char) const
Definition at line 14 of file HashFunc.h.
gaia::base::GAIA_BASIC_TYPES_TRAITS (void) const
int32_t gaia::base::GetLastError ()
Get last error in current thread.
Returns:
current thread error.
size_t gaia::base::hash_string (const char * __s) [inline]
Definition at line 37 of file HashFunc.h.
Referenced by hashCode().
template<> size_t gaia::base::hashCode (const char * key) [inline]
Definition at line 45 of file HashFunc.h.
References hash_string().
Referenced by gaia::base::HashMap< KEY, VAL >::add(), gaia::base::HashMap< KEY, VAL >::containsKey(), gaia::base::HashMap< KEY, VAL >::do_get_hash_of_key(), gaia::base::HashMap< KEY, VAL >::remove(), and gaia::base::HashMap< KEY, VAL >::valueFor().
size_t gaia::base::hashCode (const String & key) [inline]
Definition at line 819 of file String.h.
References hash_string().
bool gaia::base::operator!= (const char * s1, const String & s2) [inline]
Definition at line 803 of file String.h.
String gaia::base::operator+ (const char * s1, const String & s2) [inline]
Definition at line 815 of file String.h.
String gaia::base::operator+ (const String & s1, const String & s2) [inline]
Definition at line 807 of file String.h.
String gaia::base::operator+ (const String & s1, const char * s2) [inline]
Definition at line 811 of file String.h.
bool gaia::base::operator== (const char * s1, const String & s2) [inline]
Definition at line 799 of file String.h.
void gaia::base::SetLastError (int32_t errorCode)
Set error in current thread.
Parameters:
errorCode Error code set by user.
Returns:
void.