gaia::testing::GaiaTestCase< TestFixture > Class Template Reference
gaia::testing::GaiaTestCase< TestFixture > Class Template Reference
Save the dependencies of gaia component classes(Provider and Delegate).
#include <GaiaTestCase.h>
Public Member Functions
virtual ~GaiaTestCase ()
The d'tor is virtual as we intend to inherit from Test.
void TestGaiaTestCaseSetupProperly ()
void SetContext (core::Context *context)
Get the Interface to global information about an application environment.
core::Context * GetContext ()
void SetTestContext (core::Context *context)
Test context can be used to access resources from the test's own package as opposed to the resources from the test target package.
core::Context * GetTestContext ()
Static Public Member Functions
static void SetUpTestCase ()
Sets up the stuff shared by all tests in this test case.
static void TearDownTestCase ()
Tears down the stuff shared by all tests in this test case.
Protected Member Functions
GaiaTestCase ()
Creates a test fixture.
virtual void SetUp ()
Sets up the test fixture.
virtual void TearDown ()
Tears down the test fixture.
Private Attributes
core::Context * mpContext
core::Context * mpTestContext
Detailed Description
template<class TestFixture>
class gaia::testing::GaiaTestCase< TestFixture >
Save the dependencies of gaia component classes(Provider and Delegate).
Inherited by gaia::testing::DelegateTestCase, gaia::testing::ProviderTestCase.
TestFixture is extend from gtest/testing/test
Definition at line 24 of file GaiaTestCase.h.
Constructor & Destructor Documentation
template<class TestFixture > gaia::testing::GaiaTestCase< TestFixture >::~GaiaTestCase () [virtual]
The d'tor is virtual as we intend to inherit from Test.
Definition at line 97 of file GaiaTestCase.h.
template<class TestFixture > gaia::testing::GaiaTestCase< TestFixture >::GaiaTestCase () [protected]
Creates a test fixture.
Definition at line 138 of file GaiaTestCase.h.
Member Function Documentation
template<class TestFixture > core::Context * gaia::testing::GaiaTestCase< TestFixture >::GetContext ()
Definition at line 123 of file GaiaTestCase.h.
template<class TestFixture > core::Context * gaia::testing::GaiaTestCase< TestFixture >::GetTestContext ()
Definition at line 133 of file GaiaTestCase.h.
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::SetContext (core::Context * context)
Get the Interface to global information about an application environment.
So we can access to application-specific resources and classes, as well as up-calls for application-level operations such as launching activities, broadcasting and receiving intents, etc.
Definition at line 118 of file GaiaTestCase.h.
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::SetTestContext (core::Context * context)
Test context can be used to access resources from the test's own package as opposed to the resources from the test target package.
Access to the latter is provided by the context set with the SetContext method.
Definition at line 128 of file GaiaTestCase.h.
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::SetUp () [protected, virtual]
Sets up the test fixture.
Definition at line 143 of file GaiaTestCase.h.
Referenced by gaia::testing::ProviderTestCase< TextendsContentProvider, TestFixture >::SetUp(), and gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::SetUp().
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::SetUpTestCase () [static]
Sets up the stuff shared by all tests in this test case.
Testing will call Foo::SetUpTestCase() before running the first test in test case Foo. Hence a sub-class can define its own SetUpTestCase() method to shadow the one defined in the super class.
Definition at line 101 of file GaiaTestCase.h.
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::TearDown () [protected, virtual]
Tears down the test fixture.
Definition at line 150 of file GaiaTestCase.h.
Referenced by gaia::testing::ProviderTestCase< TextendsContentProvider, TestFixture >::TearDown(), and gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::TearDown().
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::TearDownTestCase () [static]
Tears down the stuff shared by all tests in this test case.
Testing will call Foo::TearDownTestCase() after running the last test in test case Foo. Hence a sub-class can define its own TearDownTestCase() method to shadow the one defined in the super class.
Definition at line 106 of file GaiaTestCase.h.
template<class TestFixture > void gaia::testing::GaiaTestCase< TestFixture >::TestGaiaTestCaseSetupProperly ()
Definition at line 111 of file GaiaTestCase.h.
Member Data Documentation
template<class TestFixture > core::Context* gaia::testing::GaiaTestCase< TestFixture >::mpContext [private]
Definition at line 90 of file GaiaTestCase.h.
template<class TestFixture > core::Context* gaia::testing::GaiaTestCase< TestFixture >::mpTestContext [private]
Definition at line 91 of file GaiaTestCase.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/testing/GaiaTestCase.h