gaia::core::Export< CLASS, Screenlet > Class Template Reference
gaia::core::Export< CLASS, Screenlet > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static Screenlet * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, Screenlet >
Definition at line 201 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, Screenlet >::Export () [private]
Definition at line 225 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, Screenlet >::constructor () [static, private]
Definition at line 229 of file Export.h.
References gaia::core::COMPONENT_SCREENLET, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, Screenlet >::destructor () [static, private]
Definition at line 235 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > Screenlet * gaia::core::Export< CLASS, Screenlet >::maker () [static, private]
Definition at line 240 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h