gaia::base::Array< TYPE > Class Template Reference
gaia::base::Array< TYPE > Class Template Reference
Implements array to replace C-style array.
#include <Array.h>
Public Member Functions
Array (size_t length)
Constructor of Array.
Array (const Array< TYPE > &rhs)
Copy constructor of Array.
virtual ~Array ()
Desetructor of Array.
TYPE * array ()
Acquires the inner datum for editing.
const TYPE * array () const
Acquires the inner datum for reading.
size_t length () const
Acquires the number of inner datum.
size_t size () const
Acquires the number of inner datum.
Array< TYPE > & operator= (const Array< TYPE > &rhs)
Release self datum and copies from the other array.
const TYPE & operator[] (size_t index) const
Subscript operator for array operations.
TYPE & operator[] (size_t index)
Subscript operator for array operations.
Array< TYPE > clone () const
Produces a clone array from this array.
Protected Member Functions
virtual void do_construct (void *storage, size_t num) const
Constructs datum at specified storage.
virtual void do_destroy (void *storage, size_t num) const
Destories datum at specified storage.
virtual void do_copy (void *dest, const void *from, size_t num) const
Copies datum from one specified momory to another.
Private Member Functions
Array ()
Constructor for Array.
Friends
template<class U >
bool arraycopy (const Array< U > &src, size_t srcPos, Array< U > &dst, size_t dstPos, size_t length)
Copiese datum in one array to the other.
Detailed Description
template<class TYPE>
class gaia::base::Array< TYPE >
Implements array to replace C-style array.
The main templated array class ensuring type safety while making use of ArrayImpl. This is the class users want to use.
 // Creates an array with 50 elements.
 Array<int> ary(50);
 // Saves datum into thie array.
 for (size_t = 0; i < 50; i++) {
        ary[i] = i;
 }
 // Gets array length
 int length = ary.length();
 // Copies from to
 Array<int> ary2(100);
 ary.arraycopy(ary, 0, ary2, 0, 50);
Definition at line 63 of file Array.h.
Constructor & Destructor Documentation
template<class TYPE > gaia::base::Array< TYPE >::Array (size_t length) [inline, explicit]
Constructor of Array.
Creates an array by setting its length.
Parameters:
length Size of array to be set.
Definition at line 238 of file Array.h.
template<class TYPE> gaia::base::Array< TYPE >::Array (const Array< TYPE > & rhs) [inline]
Copy constructor of Array.
Creates an array by copying datum from the other one.
Parameters:
rhs Array to be copied.
Definition at line 261 of file Array.h.
template<class TYPE > gaia::base::Array< TYPE >::~Array () [inline, virtual]
Desetructor of Array.
Definition at line 266 of file Array.h.
template<class TYPE> gaia::base::Array< TYPE >::Array () [inline, private]
Constructor for Array.
This is not in-use. Set for preventing misuse.
Definition at line 234 of file Array.h.
Member Function Documentation
template<class TYPE > TYPE * gaia::base::Array< TYPE >::array () [inline]
Acquires the inner datum for editing.
Returns:
Non-const datum address.
Definition at line 271 of file Array.h.
References gaia::base::ArrayImpl::arrayImpl().
Referenced by gaia::core::GL11::glBufferData(), gaia::core::GL11::glBufferSubData(), gaia::core::GLES10::glColorPointer(), gaia::core::GL10::glColorPointer(), gaia::core::GL11ExtensionPack::glCompressedTexImage2D(), gaia::core::GL10::glCompressedTexImage2D(), gaia::core::GL10::glCompressedTexSubImage2D(), gaia::core::GLES20::glDrawElements(), gaia::core::GLES10::glDrawElements(), gaia::core::GL10::glDrawElements(), gaia::core::GLES11Ext::glMatrixIndexPointerOES(), gaia::core::GL11Ext::glMatrixIndexPointerOES(), gaia::core::GLES10::glNormalPointer(), gaia::core::GL10::glNormalPointer(), gaia::core::GL11::glPointSizePointerOES(), gaia::core::GL10::glReadPixels(), gaia::core::GLES10::glTexCoordPointer(), gaia::core::GL10::glTexCoordPointer(), gaia::core::GLES20::glTexImage2D(), gaia::core::GLES10::glTexImage2D(), gaia::core::GL10::glTexImage2D(), gaia::core::GL10::glTexSubImage2D(), gaia::core::GLES20::glVertexAttribPointer(), gaia::core::GLES10::glVertexPointer(), gaia::core::GL10::glVertexPointer(), gaia::core::GLES11Ext::glWeightPointerOES(), gaia::core::GL11Ext::glWeightPointerOES(), and gaia::base::Vector< TYPE >::toArray().
template<class TYPE > const TYPE * gaia::base::Array< TYPE >::array () const [inline]
Acquires the inner datum for reading.
Returns:
Const datum address.
Definition at line 276 of file Array.h.
References gaia::base::ArrayImpl::arrayImpl().
template<class TYPE > Array< TYPE > gaia::base::Array< TYPE >::clone () const [inline]
Produces a clone array from this array.
Returns:
The cloned array.
Definition at line 307 of file Array.h.
References gaia::base::arraycopy().
template<class TYPE > void gaia::base::Array< TYPE >::do_construct (void * storage, size_t num) const [protected, virtual]
Constructs datum at specified storage.
It calls the constructor (if there is) specified by Vector template parameter <TYPE> to execute construct process.
See also:
gaia::base::construct_type()
Parameters:
storage Memory address of Datum.
num Number of datum in the unit of data type <TYPE>.
Implements gaia::base::ArrayImpl.
Definition at line 316 of file Array.h.
template<class TYPE > void gaia::base::Array< TYPE >::do_copy (void * dest, const void * from, size_t num) const [protected, virtual]
Copies datum from one specified momory to another.
It calls the copy constructor (if there is) specified by Voctor tamplate parameter <TYPE> to execute copy process.
See also:
gaia::base::copy_type()
Parameters:
dest Destination that datum to be copied to.
from Memory of datum to be copied.
num Number of datum in the unit of data type <TYPE>
Implements gaia::base::ArrayImpl.
Definition at line 326 of file Array.h.
template<class TYPE > void gaia::base::Array< TYPE >::do_destroy (void * storage, size_t num) const [protected, virtual]
Destories datum at specified storage.
It calls the destructor (if there is) specified by Vector template parameter <TYPE> to execute destory process.
See also:
gaia::base::destroy_type()
Parameters:
storage Memory address of Datum.
num Number of datum in the unit of data type <TYPE>.
Implements gaia::base::ArrayImpl.
Definition at line 321 of file Array.h.
template<class TYPE > size_t gaia::base::Array< TYPE >::length () const [inline]
Acquires the number of inner datum.
Returns:
Number of inner datum.
Reimplemented from gaia::base::ArrayImpl.
Definition at line 281 of file Array.h.
References gaia::base::ArrayImpl::length().
Referenced by gaia::core::GL11::glBufferData(), gaia::core::GL11::glBufferSubData(), gaia::core::GLES10::glColorPointer(), gaia::core::GL10::glColorPointer(), gaia::core::GL11ExtensionPack::glCompressedTexImage2D(), gaia::core::GL10::glCompressedTexImage2D(), gaia::core::GL10::glCompressedTexSubImage2D(), gaia::core::GLES20::glDrawElements(), gaia::core::GLES10::glDrawElements(), gaia::core::GL10::glDrawElements(), gaia::core::GLES11Ext::glMatrixIndexPointerOES(), gaia::core::GL11Ext::glMatrixIndexPointerOES(), gaia::core::GLES10::glNormalPointer(), gaia::core::GL10::glNormalPointer(), gaia::core::GL11::glPointSizePointerOES(), gaia::core::GL10::glReadPixels(), gaia::core::GLES10::glTexCoordPointer(), gaia::core::GL10::glTexCoordPointer(), gaia::core::GLES20::glTexImage2D(), gaia::core::GLES10::glTexImage2D(), gaia::core::GL10::glTexImage2D(), gaia::core::GL10::glTexSubImage2D(), gaia::core::GLES20::glVertexAttribPointer(), gaia::core::GLES10::glVertexPointer(), gaia::core::GL10::glVertexPointer(), gaia::core::GLES11Ext::glWeightPointerOES(), gaia::core::GL11Ext::glWeightPointerOES(), and gaia::base::Vector< TYPE >::toArray().
template<class TYPE> Array< TYPE > & gaia::base::Array< TYPE >::operator= (const Array< TYPE > & rhs) [inline]
Release self datum and copies from the other array.
Parameters:
rhs The other array to be copied from.
Definition at line 291 of file Array.h.
References gaia::base::ArrayImpl::operator=().
template<class TYPE > TYPE & gaia::base::Array< TYPE >::operator[] (size_t index) [inline]
Subscript operator for array operations.
Used to query data by its index. The acquired data is used for editing.
Parameters:
index
Returns:
Non-const data pointer of the queried data.
Definition at line 302 of file Array.h.
template<class TYPE > const TYPE & gaia::base::Array< TYPE >::operator[] (size_t index) const [inline]
Subscript operator for array operations.
Used to query data by its index.
Parameters:
index
Returns:
Const data pointer of the queried data.
Definition at line 297 of file Array.h.
template<class TYPE > size_t gaia::base::Array< TYPE >::size () const [inline]
Acquires the number of inner datum.
Returns:
Number of inner datum.
Definition at line 286 of file Array.h.
References gaia::base::ArrayImpl::length().
Friends And Related Function Documentation
template<class TYPE> template<class U > bool arraycopy (const Array< U > & src, size_t srcPos, Array< U > & dst, size_t dstPos, size_t length) [friend]
Copiese datum in one array to the other.
Parameters:
src Source array to be copied.
srcPos Location starts to copy.
dst Desetination to copy to.
dstPos Location to put copied datum.
length Nubmer of datum to be copied
Returns:
True if datum is copied. False if the specified range is incorrect.
Definition at line 226 of file Array.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/base/Array.h