gaia::core::Export< CLASS, Page > Class Template Reference
gaia::core::Export< CLASS, Page > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static Page * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, Page >
Definition at line 152 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, Page >::Export () [private]
Definition at line 176 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, Page >::constructor () [static, private]
Definition at line 180 of file Export.h.
References gaia::core::COMPONENT_PAGE, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, Page >::destructor () [static, private]
Definition at line 186 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > Page * gaia::core::Export< CLASS, Page >::maker () [static, private]
Definition at line 191 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h