gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher > Class Template Reference
gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static
gaia::core::MultiWindowLauncher * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >
Definition at line 744 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::Export () [private]
Definition at line 767 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::constructor () [static, private]
Definition at line 771 of file Export.h.
References gaia::core::COMPONENT_MULTIWINDOW_LAUNCHER, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::destructor () [static, private]
Definition at line 779 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > gaia::core::MultiWindowLauncher * gaia::core::Export< CLASS, gaia::core::MultiWindowLauncher >::maker () [static, private]
Definition at line 786 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h