gaia::base::List< TYPE > Class Template Reference
gaia::base::List< TYPE > Class Template Reference
The class implements circular bi-directional linked list data structure.
#include <List.h>
Classes
struct CONST_ITERATOR
Iterator structure for const list iterator.
class ListIterator
Iterator for List.
struct NON_CONST_ITERATOR
Iterator structure for non-const list iterator.
Public Types
typedef ListIterator< TYPE,
NON_CONST_ITERATOR > iterator
Defines a non-const list iterator.
typedef ListIterator< TYPE,
CONST_ITERATOR > const_iterator
Defines a const list iterator.
Public Member Functions
List ()
Constructs a new list using the default capacity.
List (const List< TYPE > &src)
Constructs a new instance of list containing copied elements from src.
virtual ~List ()
Destructs an existing list.
List< TYPE > & operator= (const List< TYPE > &rhs)
Makes (this) list the same as rhs.
bool empty () const
Returns if this list has no elements, a size of zero.
size_t size () const
Returns the number of elements in this list.
void push_front (const TYPE &val)
Push data at the head of list.
void push_back (const TYPE &val)
Push data at the tail of list.
void clear ()
Removes all elements from this list.
iterator begin ()
Acquires (non-const) list iterator pointed to the head of list.
const_iterator begin () const
Acquires const list iterator pointed to the head of list.
iterator end ()
Acquires (non-const) list iterator pointed to the tail of list, which is the only access point.
const_iterator end () const
Acquires const list iterator pointed to the tail of list, which is the only access point.
iterator insert (iterator posn, const TYPE &val)
Inserts before the specified iterator.
void insert (iterator posn, const_iterator first, const_iterator last)
Inserts a range of elements before the current node.
iterator erase (iterator posn)
Removes one element at the specified location.
iterator erase (iterator first, iterator last)
Removes a bundle of elements specified.
Protected Member Functions
virtual void do_destroy (void *storage, size_t num) const
Destories datum at specified storage.
virtual void do_copy (void *dest, const void *from, size_t num) const
Copies datum from one specified momory to another.
Detailed Description
template<class TYPE>
class gaia::base::List< TYPE >
The class implements circular bi-directional linked list data structure.
It implemets circular bi-directional linked list operation methods. List possesses an access point, whcih is forwardly linked head and backwardly linked tail of list. Usually, it is used with ListIerator.
See also:
ListIterator
 // Create a list
 gaia::base::List<gaia::base::String> lst;
 // Insert two strings into list at head.
 lst.insert(lst.begin(), String::valueOf(2011));
 lst.insert(lst.begin(), String::valueOf(2012));
 // Delete string "2012".
 lst.erase(lst.begin());
Definition at line 36 of file List.h.
Member Typedef Documentation
template<class TYPE> typedef ListIterator<TYPE, CONST_ITERATOR> gaia::base::List< TYPE >::const_iterator
Defines a const list iterator.
Definition at line 175 of file List.h.
template<class TYPE> typedef ListIterator<TYPE, NON_CONST_ITERATOR> gaia::base::List< TYPE >::iterator
Defines a non-const list iterator.
Definition at line 165 of file List.h.
Constructor & Destructor Documentation
template<class TYPE > gaia::base::List< TYPE >::List ()
Constructs a new list using the default capacity.
Definition at line 302 of file List.h.
template<class TYPE> gaia::base::List< TYPE >::List (const List< TYPE > & src)
Constructs a new instance of list containing copied elements from src.
The order of the elements in the new list is dependent on the iteration order of the seed collection.
Parameters:
src the list to add.
Definition at line 310 of file List.h.
References gaia::base::ListImpl::copy_list().
template<class TYPE > gaia::base::List< TYPE >::~List () [virtual]
Destructs an existing list.
Definition at line 316 of file List.h.
Member Function Documentation
template<class TYPE> iterator gaia::base::List< TYPE >::begin () [inline]
Acquires (non-const) list iterator pointed to the head of list.
Returns:
Non-const list iterator pointed to the head of list.
Definition at line 182 of file List.h.
template<class TYPE> const_iterator gaia::base::List< TYPE >::begin () const [inline]
Acquires const list iterator pointed to the head of list.
Returns:
Const list iterator pointed to the head of list.
Definition at line 191 of file List.h.
template<class TYPE > void gaia::base::List< TYPE >::clear ()
Removes all elements from this list.
See also:
isEmpty
size
Definition at line 347 of file List.h.
template<class TYPE > void gaia::base::List< TYPE >::do_copy (void * dest, const void * from, size_t num) const [protected, virtual]
Copies datum from one specified momory to another.
It calls the copy constructor specified by list tamplate parameter <TYPE> to execute copy process.
See also:
gaia::base::copy_type()
Parameters:
dest Destination that datum to be copied to.
from Memory of datum to be copied.
num Number of datum in the unit of data type <TYPE>
Implements gaia::base::ListImpl.
Definition at line 358 of file List.h.
template<class TYPE > void gaia::base::List< TYPE >::do_destroy (void * storage, size_t num) const [protected, virtual]
Destories datum at specified storage.
It calls the destructor specified by List template parameter <TYPE> to execute destory process.
See also:
gaia::base::destroy_type()
Parameters:
storage Memory address of Datum.
num Number of datum in the unit of data type <TYPE>.
Implements gaia::base::ListImpl.
Definition at line 353 of file List.h.
template<class TYPE > bool gaia::base::List< TYPE >::empty () const
Returns if this list has no elements, a size of zero.
Returns:
True if this list has no elements, false otherwise.
See also:
size
Definition at line 327 of file List.h.
template<class TYPE> iterator gaia::base::List< TYPE >::end () [inline]
Acquires (non-const) list iterator pointed to the tail of list, which is the only access point.
Returns:
Non-const list iterator pointed to the tail of list.
Definition at line 201 of file List.h.
template<class TYPE> const_iterator gaia::base::List< TYPE >::end () const [inline]
Acquires const list iterator pointed to the tail of list, which is the only access point.
Returns:
Const list iterator pointed to the tail of list.
Definition at line 211 of file List.h.
template<class TYPE> iterator gaia::base::List< TYPE >::erase (iterator posn) [inline]
Removes one element at the specified location.
Parameters:
posn The location of node.
Returns:
Iterator the node next to the specified location.
Definition at line 250 of file List.h.
Referenced by gaia::base::List< X509Certificate * >::erase().
template<class TYPE> iterator gaia::base::List< TYPE >::erase (iterator first, iterator last) [inline]
Removes a bundle of elements specified.
Be aware that the last element is not removed.
Parameters:
first The first iterator of specified elements.
last The last iterator of specified elements.
Definition at line 263 of file List.h.
template<class TYPE> iterator gaia::base::List< TYPE >::insert (iterator posn, const TYPE & val) [inline]
Inserts before the specified iterator.
Parameters:
posn The location to be inserted at.
val Data to be added.
Returns:
The iterator pointed to the new inserted node.
Definition at line 224 of file List.h.
Referenced by gaia::base::List< X509Certificate * >::insert().
template<class TYPE> void gaia::base::List< TYPE >::insert (iterator posn, const_iterator first, const_iterator last) [inline]
Inserts a range of elements before the current node.
Be aware that the data of the iterator last is not inserted into list.
Parameters:
posn The location to be inserted at.
first The start iterator of the inserted elements.
last The last iterator of the inserted elements.
Definition at line 239 of file List.h.
template<class TYPE> List< TYPE > & gaia::base::List< TYPE >::operator= (const List< TYPE > & rhs)
Makes (this) list the same as rhs.
Those elements in (this) list are removed and all elements in rhs are copied into (this) list.
Parameters:
rhs The target list to be copied.
Returns:
Address of (this) list
Definition at line 321 of file List.h.
References gaia::base::ListImpl::operator=().
template<class TYPE> void gaia::base::List< TYPE >::push_back (const TYPE & val)
Push data at the tail of list.
Parameters:
val Data to be pushed.
Definition at line 342 of file List.h.
template<class TYPE> void gaia::base::List< TYPE >::push_front (const TYPE & val)
Push data at the head of list.
Parameters:
val Data to be pushed.
Definition at line 337 of file List.h.
template<class TYPE > size_t gaia::base::List< TYPE >::size () const
Returns the number of elements in this list.
Returns:
The number of elements in this list.
Definition at line 332 of file List.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/base/List.h