gaia::base::Vector2D< TYPE > Class Template Reference
gaia::base::Vector2D< TYPE > Class Template Reference
This is 2 dimension Vector.
#include <Vector2D.h>
Public Member Functions
Vector2D ()
Constructs a new 2D vector using the default capacity.
Vector2D (const Vector2D< TYPE > &rhs)
Constructs a new item of Vector2D containing the elements in rhs.
virtual ~Vector2D ()
Destructor of Vector2D.
const Vector2D< TYPE > & operator= (const Vector2D< TYPE > &rhs)
Const-to-const assignment operation of vector.
const Vector< TYPE > & operator[] (size_t index) const
Access to a Vector at a given index.
void clear ()
Removes all elements in this 2D Vector, leaving it empty.
size_t size () const
Returns the number of elements in this 2D vector.
bool isEmpty () const
Returns if this 2D vector has no elements, a size of zero.
size_t capacity () const
Returns the total number of elements this Vector2D can hold without growing.
size_t idvCapacity (size_t index) const
Returns the number of elements specific vector can hold without growing.
void setIdvCapacity (size_t index, size_t size)
Sets the capacity.
const TYPE & itemAt (size_t index1, size_t index2) const
Returns the item at the specified location in this vector.
void append (size_t index, const TYPE &item, size_t numItems=1)
Adds the specified item at the end of this vector.
void appendVector (size_t index, const Vector< TYPE > &vector)
Adds the items in the specified vector to the end of this vector.
void insertAt (size_t index1, size_t index2, const TYPE &prototype_item, size_t numItems=1)
Inserts the specified item into this vector at the specified location.
void insertVectorAt (size_t index1, size_t index2, const Vector< TYPE > &vector)
Inserts the items in the specified vector at the specified location in this vector.
void removeAt (size_t index1, size_t index2, size_t count=1)
Removes items at the specified location from this vector.
void replaceAt (size_t index1, size_t index2, const TYPE &item)
Replaces the element at the specified location in this vector with the specified item.
Array< TYPE > toArray (size_t index) const
Returns a new array containing all elements contained in this vector.
Private Attributes
Vector< Vector< TYPE > > mData
Detailed Description
template<class TYPE>
class gaia::base::Vector2D< TYPE >
This is 2 dimension Vector.
Definition at line 30 of file Vector2D.h.
Constructor & Destructor Documentation
template<class TYPE > gaia::base::Vector2D< TYPE >::Vector2D () [inline]
Constructs a new 2D vector using the default capacity.
Definition at line 246 of file Vector2D.h.
template<class TYPE > gaia::base::Vector2D< TYPE >::Vector2D (const Vector2D< TYPE > & rhs)
Constructs a new item of Vector2D containing the elements in rhs.
The order of the elements in the new Vector2D is dependent on the iteration order of the seed collection.
Parameters:
rhs The Vector2D to be copied from.
Warning:
Copy for Vector2D<TYPE> is different from Vector<Vector<TYPE> >. Both of them are shallow copy, but in different level.
Definition at line 250 of file Vector2D.h.
References gaia::base::Vector2D< TYPE >::mData, and gaia::base::Vector< TYPE >::size().
template<class TYPE > gaia::base::Vector2D< TYPE >::~Vector2D () [virtual]
Destructor of Vector2D.
Definition at line 258 of file Vector2D.h.
Member Function Documentation
template<class TYPE > void gaia::base::Vector2D< TYPE >::append (size_t index, const TYPE & item, size_t numItems = 1)
Adds the specified item at the end of this vector.
Parameters:
index The Vector to be added to.
item The item to add to the vector.
numItems The number of items to be added.
Definition at line 348 of file Vector2D.h.
References gaia::base::Vector< TYPE >::append().
template<class TYPE > void gaia::base::Vector2D< TYPE >::appendVector (size_t index, const Vector< TYPE > & vector)
Adds the items in the specified vector to the end of this vector.
Parameters:
index The Vector to be added to.
vector The vector which possesses desired datum.
Returns:
True if this vector is modified, false otherwise.
Definition at line 362 of file Vector2D.h.
References gaia::base::Vector< TYPE >::append(), and gaia::base::Vector< TYPE >::appendVector().
template<class TYPE > size_t gaia::base::Vector2D< TYPE >::capacity () const
Returns the total number of elements this Vector2D can hold without growing.
Returns:
The capacity of this Vector2D.
Definition at line 310 of file Vector2D.h.
template<class TYPE > void gaia::base::Vector2D< TYPE >::clear ()
Removes all elements in this 2D Vector, leaving it empty.
See also:
isEmpty
size
Definition at line 278 of file Vector2D.h.
References gaia::base::Vector< TYPE >::clear().
template<class TYPE > size_t gaia::base::Vector2D< TYPE >::idvCapacity (size_t index) const
Returns the number of elements specific vector can hold without growing.
Parameters:
index The index of Vector
Returns:
The capacity of specific vector.
Definition at line 318 of file Vector2D.h.
template<class TYPE > void gaia::base::Vector2D< TYPE >::insertAt (size_t index1, size_t index2, const TYPE & prototype_item, size_t numItems = 1)
Inserts the specified item into this vector at the specified location.
This item is inserted before any previous element at the specified location. All elements with an index equal or greater than location have their index increased by 1. If the location is equal to the size of this vector, the item is added at the end. The specified items are initialized from prototype items.
Parameters:
index1 The Vector to be added to.
prototype_item The item to insert in this vector.
index2 The index at which to insert the element.
numItems Number of items to be inserted.
See also:
append
size
Definition at line 376 of file Vector2D.h.
References gaia::base::Vector< TYPE >::append(), and gaia::base::Vector< TYPE >::insertAt().
template<class TYPE > void gaia::base::Vector2D< TYPE >::insertVectorAt (size_t index1, size_t index2, const Vector< TYPE > & vector)
Inserts the items in the specified vector at the specified location in this vector.
The items are inserted in the order in which they are returned from the vector iterator. The items with an index equal or higher than vector size have their index increased by the size of the added collection.
Parameters:
index1 The Vector to be added to.
vector Given vector to be inserted into list vector.
index2 The location to insert the items.
Returns:
True if this vector is modified, false otherwise.
Definition at line 391 of file Vector2D.h.
References gaia::base::Vector< TYPE >::append(), and gaia::base::Vector< TYPE >::insertVectorAt().
template<class TYPE > bool gaia::base::Vector2D< TYPE >::isEmpty () const
Returns if this 2D vector has no elements, a size of zero.
Returns:
True if this vector has no elements, false otherwise.
See also:
size
Definition at line 299 of file Vector2D.h.
template<class TYPE > const TYPE & gaia::base::Vector2D< TYPE >::itemAt (size_t index1, size_t index2) const
Returns the item at the specified location in this vector.
Parameters:
index1 The first index of the item to return in this vector.
index2 The second index of the item to return in this vector.
Returns:
The item at the specified location.
See also:
size
Definition at line 343 of file Vector2D.h.
template<class TYPE > const Vector2D< TYPE > & gaia::base::Vector2D< TYPE >::operator= (const Vector2D< TYPE > & rhs)
Const-to-const assignment operation of vector.
Because copy-on-write mechanism, the original datum possesses by this vector is releaseed and this vector will acquire to possess datum on rhs vector.
Parameters:
rhs The Vector2D to be copied from.
Warning:
Copy for Vector2D<TYPE> is different from Vector<Vector<TYPE> >. Both of them are shallow copy, but in different level.
Definition at line 263 of file Vector2D.h.
References gaia::base::Vector2D< TYPE >::mData, and gaia::base::Vector< TYPE >::size().
template<class TYPE > const Vector< TYPE > & gaia::base::Vector2D< TYPE >::operator[] (size_t index) const
Access to a Vector at a given index.
Parameters:
index The index of Vector2D.
Definition at line 273 of file Vector2D.h.
template<class TYPE > void gaia::base::Vector2D< TYPE >::removeAt (size_t index1, size_t index2, size_t count = 1)
Removes items at the specified location from this vector.
All elements with an index bigger than location + count have their index decreased by count.
Parameters:
index1 The Vector to be removed from.
index2 The index of the first item to be removed.
count Number of items to be removed.
Definition at line 406 of file Vector2D.h.
References gaia::base::Vector< TYPE >::removeAt().
template<class TYPE > void gaia::base::Vector2D< TYPE >::replaceAt (size_t index1, size_t index2, const TYPE & item)
Replaces the element at the specified location in this vector with the specified item.
Parameters:
index1 The Vector to be replaced with.
index2 Specified item used to replace.
index The index at which to put the specified item.
See also:
size
Definition at line 414 of file Vector2D.h.
References gaia::base::Vector< TYPE >::replaceAt().
template<class TYPE > void gaia::base::Vector2D< TYPE >::setIdvCapacity (size_t index, size_t size)
Sets the capacity.
Capacity can never be reduced less than size()
Parameters:
index The index of the Vector to be set.
size The assigned size of vector. Be aware that the size should be smaller its capacity.
Definition at line 329 of file Vector2D.h.
References gaia::base::Vector< TYPE >::append(), and gaia::base::Vector< TYPE >::setCapacity().
template<class TYPE > size_t gaia::base::Vector2D< TYPE >::size () const
Returns the number of elements in this 2D vector.
Returns:
The number of elements in this 2D vector.
Definition at line 287 of file Vector2D.h.
template<class TYPE > Array< TYPE > gaia::base::Vector2D< TYPE >::toArray (size_t index) const
Returns a new array containing all elements contained in this vector.
Parameters:
index The queried Vector
Returns:
an array of the elements from this vector.
Definition at line 422 of file Vector2D.h.
Member Data Documentation
template<class TYPE> Vector<Vector<TYPE> > gaia::base::Vector2D< TYPE >::mData [private]
Definition at line 242 of file Vector2D.h.
Referenced by gaia::base::Vector2D< TYPE >::operator=(), and gaia::base::Vector2D< TYPE >::Vector2D().
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/base/Vector2D.h