gaia::base::ArrayImpl Class Reference
gaia::base::ArrayImpl Class Reference
Implements array data structure and its operation methods.
#include <ArrayImpl.h>
Public Types
enum { HAS_TRIVIAL_CTOR = 0x00000001, HAS_TRIVIAL_DTOR = 0x00000002, HAS_TRIVIAL_COPY = 0x00000004 }
Flags passed to the constructor.
Public Member Functions
ArrayImpl (size_t itemSize, uint32_t flags, size_t arrayLength)
Constructor of ArrayImpl.
ArrayImpl (const ArrayImpl &rhs)
Copy constructor for ArrayImpl.
void finish_array ()
Destroies datum and Releases datum storage.
ArrayImpl & operator= (const ArrayImpl &rhs)
This ArrayImpl release its datum and acquire for use rhs datum.
const void * arrayImpl () const
Acquires for direct use of inner datum.
void * arrayImpl ()
Acquires for direct use of inner datum.
size_t length () const
Acquires the number of inner datum.
size_t capacity () const
Gets storage capacity.
const void * itemLocation (size_t index) const
Acquires the data at the specified index.
void * itemLocation (size_t index)
Acquires the data at the specified index.
Static Public Member Functions
static bool arraycopy (const ArrayImpl &src, size_t srcPos, ArrayImpl &dst, size_t dstPos, size_t length)
Copiese datum in one array to the other.
Protected Member Functions
virtual void do_construct (void *storage, size_t num) const =0
Used to construct datum stored in the vector.
virtual void do_destroy (void *storage, size_t num) const =0
Used to destory datum stored in the list.
virtual void do_copy (void *dest, const void *from, size_t num) const =0
Used to copy datum stored in the list.
virtual void reservedVectorImpl1 ()
Take care of FBC.
virtual void reservedVectorImpl2 ()
Take care of FBC.
virtual void reservedVectorImpl3 ()
Take care of FBC.
virtual void reservedVectorImpl4 ()
Take care of FBC.
virtual void reservedVectorImpl5 ()
Take care of FBC.
virtual void reservedVectorImpl6 ()
Take care of FBC.
virtual void reservedVectorImpl7 ()
Take care of FBC.
virtual void reservedVectorImpl8 ()
Take care of FBC.
Private Member Functions
virtual ~ArrayImpl ()
This is marked comment.
void request_storage () const
Release its storage and acquire a new one.
void release_storage () const
Release its right of use.
void _do_construct (void *storage, size_t num) const
Construct data by calling the constructor of that data type.
void _do_destroy (void *storage, size_t num) const
Destory data by calling the destructor of that data type.
void _do_copy (void *dest, const void *from, size_t num) const
Copy data by calling the copy constructor of that data tpye.
Private Attributes
void * mpStorage
Base address of the array.
size_t mCount
Number of items.
const uint32_t mFlags
Characteristics of the stored data.
const size_t mItemSize
Size of the type of stored data.
Detailed Description
Implements array data structure and its operation methods.
This class is not designed for use. Users should use Array instead.
See also:
Array
 // Create an ArrayImpl object.
 ArrayImpl ary_impl(sizeof(int), HAS_TRIVIAL_CTOR, 50);
 // Sets its datum
 for (size_t i = 0; i < 50; i++) {
        ary_impl.itemLocation(i) = i;
 }
 // Gets its data length
 int length = ary_impl.length();
Definition at line 47 of file ArrayImpl.h.
Member Enumeration Documentation
anonymous enum
Flags passed to the constructor.
Enumerator:
HAS_TRIVIAL_CTOR
HAS_TRIVIAL_DTOR
HAS_TRIVIAL_COPY
Definition at line 52 of file ArrayImpl.h.
Constructor & Destructor Documentation
gaia::base::ArrayImpl::ArrayImpl (size_t itemSize, uint32_t flags, size_t arrayLength)
Constructor of ArrayImpl.
Parameters:
itemSize Size of the type of stored data.
flags Characteristics of stored data type.
arrayLength Number of elements.
gaia::base::ArrayImpl::ArrayImpl (const ArrayImpl & rhs)
Copy constructor for ArrayImpl.
Creates an array by coping datum from the other.
Parameters:
rhs The other array to be copied.
virtual gaia::base::ArrayImpl::~ArrayImpl () [private, virtual]
This is marked comment.
Destructor of ArrayImpl.
Member Function Documentation
void gaia::base::ArrayImpl::_do_construct (void * storage, size_t num) const [inline, private]
Construct data by calling the constructor of that data type.
Parameters:
storage The memory address where data is stored into.
num The number of datum counted in the unit of specified data type.
void gaia::base::ArrayImpl::_do_copy (void * dest, const void * from, size_t num) const [inline, private]
Copy data by calling the copy constructor of that data tpye.
Parameters:
dest The memory address that datum is copied to.
from The memory address that datum is copied from.
num The number of datum counted in the unit of specified data type.
void gaia::base::ArrayImpl::_do_destroy (void * storage, size_t num) const [inline, private]
Destory data by calling the destructor of that data type.
Parameters:
storage The memory address where data is stored into.
num The number of datum counted in the unit of specified data type.
static bool gaia::base::ArrayImpl::arraycopy (const ArrayImpl & src, size_t srcPos, ArrayImpl & dst, size_t dstPos, size_t length) [static]
Copiese datum in one array to the other.
Parameters:
src Source array to be copied.
srcPos Location starts to copy.
dst Desetination to copy to.
dstPos Location to put copied datum.
length Nubmer of datum to be copied
Returns:
True if datum is copied. False if the specified range is incorrect.
Referenced by gaia::base::arraycopy().
const void* gaia::base::ArrayImpl::arrayImpl () const
Acquires for direct use of inner datum.
This function is for reading only.
Warning:
C-style array access
Returns:
Const pointer of inner datum.
Referenced by gaia::base::Array< TYPE >::array().
void* gaia::base::ArrayImpl::arrayImpl ()
Acquires for direct use of inner datum.
Warning:
C-style array access
Returns:
Non-const pointer of inner datum.
size_t gaia::base::ArrayImpl::capacity () const
Gets storage capacity.
Capacity is the actual memory array possesses. Size is the number of stored data.
See also:
ArrayImpl::size()
Returns:
Capacity of its storage.
virtual void gaia::base::ArrayImpl::do_construct (void * storage, size_t num) const [protected, pure virtual]
Used to construct datum stored in the vector.
This virtual function should be implemented by sub-classes.
Parameters:
storage The memory address of stored datum.
num Number of datum in the unit of data type.
Implemented in gaia::base::Array< TYPE >, gaia::base::Array< SHA1FingerPrint >, gaia::base::Array< float >, gaia::base::Array< TextKeyListener * >, gaia::base::Array< IPEndPoint >, gaia::base::Array< gaia::security::X509Certificate * >, gaia::base::Array< DigitsKeyListener * >, gaia::base::Array< gaia::base::String >, and gaia::base::Array< const gaia::graphics::Drawer * >.
virtual void gaia::base::ArrayImpl::do_copy (void * dest, const void * from, size_t num) const [protected, pure virtual]
Used to copy datum stored in the list.
This virtual function should be implemented by sub-classes.
Parameters:
dest The memory address of space that datum is copied to.
from The memory address of datum, which is to be copied.
num Number of datum in the unit of data type.
Implemented in gaia::base::Array< TYPE >, gaia::base::Array< SHA1FingerPrint >, gaia::base::Array< float >, gaia::base::Array< TextKeyListener * >, gaia::base::Array< IPEndPoint >, gaia::base::Array< gaia::security::X509Certificate * >, gaia::base::Array< DigitsKeyListener * >, gaia::base::Array< gaia::base::String >, and gaia::base::Array< const gaia::graphics::Drawer * >.
virtual void gaia::base::ArrayImpl::do_destroy (void * storage, size_t num) const [protected, pure virtual]
Used to destory datum stored in the list.
This virtual function should be implemented by sub-classes.
Parameters:
storage The memory address of stored datum.
num Number of datum in the unit of data type.
Implemented in gaia::base::Array< TYPE >, gaia::base::Array< SHA1FingerPrint >, gaia::base::Array< float >, gaia::base::Array< TextKeyListener * >, gaia::base::Array< IPEndPoint >, gaia::base::Array< gaia::security::X509Certificate * >, gaia::base::Array< DigitsKeyListener * >, gaia::base::Array< gaia::base::String >, and gaia::base::Array< const gaia::graphics::Drawer * >.
void gaia::base::ArrayImpl::finish_array ()
Destroies datum and Releases datum storage.
Warning:
Must be called from subclasses destructor.
const void* gaia::base::ArrayImpl::itemLocation (size_t index) const
Acquires the data at the specified index.
Parameters:
index Index of the data.
Returns:
Const data pointer if data is acquired, 0 otherwise.
void* gaia::base::ArrayImpl::itemLocation (size_t index)
Acquires the data at the specified index.
This function answers editing needs.
Parameters:
index Index of the data.
Returns:
Non-const data pointer if data is acquired, 0 otherwise.
size_t gaia::base::ArrayImpl::length () const [inline]
Acquires the number of inner datum.
Returns:
Number of inner datum.
Reimplemented in gaia::base::Array< TYPE >, gaia::base::Array< SHA1FingerPrint >, gaia::base::Array< float >, gaia::base::Array< TextKeyListener * >, gaia::base::Array< IPEndPoint >, gaia::base::Array< gaia::security::X509Certificate * >, gaia::base::Array< DigitsKeyListener * >, gaia::base::Array< gaia::base::String >, and gaia::base::Array< const gaia::graphics::Drawer * >.
Definition at line 124 of file ArrayImpl.h.
References mCount.
Referenced by gaia::base::Array< TYPE >::length(), and gaia::base::Array< TYPE >::size().
ArrayImpl& gaia::base::ArrayImpl::operator= (const ArrayImpl & rhs)
This ArrayImpl release its datum and acquire for use rhs datum.
Parameters:
rhs The other ArrayImpl entity provided for assignment.
Returns:
Address of this ArrayImpl.
Referenced by gaia::base::Array< TYPE >::operator=().
void gaia::base::ArrayImpl::release_storage () const [private]
Release its right of use.
If it is only owner, release the storage.
void gaia::base::ArrayImpl::request_storage () const [private]
Release its storage and acquire a new one.
Memory operation errors are recorded in logs.
virtual void gaia::base::ArrayImpl::reservedVectorImpl1 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl2 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl3 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl4 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl5 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl6 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl7 () [protected, virtual]
Take care of FBC.
virtual void gaia::base::ArrayImpl::reservedVectorImpl8 () [protected, virtual]
Take care of FBC.
Member Data Documentation
size_t gaia::base::ArrayImpl::mCount [private]
Number of items.
Definition at line 297 of file ArrayImpl.h.
Referenced by length().
const uint32_t gaia::base::ArrayImpl::mFlags [private]
Characteristics of the stored data.
Definition at line 302 of file ArrayImpl.h.
const size_t gaia::base::ArrayImpl::mItemSize [private]
Size of the type of stored data.
Definition at line 307 of file ArrayImpl.h.
void* gaia::base::ArrayImpl::mpStorage [mutable, private]
Base address of the array.
Definition at line 292 of file ArrayImpl.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/base/ArrayImpl.h