gaia::base::Vector< TYPE > Class Template Reference
gaia::base::Vector< TYPE > Class Template Reference
This class implements the vector data structure.
#include <Vector.h>
Public Member Functions
Vector ()
Constructs a new vector using the default capacity.
Vector (const Vector< TYPE > &rhs)
Constructs a new item of Vector containing the elements in rhs.
virtual ~Vector ()
Destructor of Vector.
const Vector< TYPE > & operator= (const Vector< TYPE > &rhs) const
Const-to-const assignment operation of vector.
Vector< TYPE > & operator= (const Vector< TYPE > &rhs)
Nonconst-to-nonconst assignment operation of vector with copy-on-write mechanism mentioned before.
const TYPE & operator[] (size_t index) const
Read-only access to an item at a given index.
void clear ()
Removes all elements from this vector, leaving it empty.
size_t size () const
Returns the number of elements in this vector.
bool isEmpty () const
Returns if this vector has no elements, a size of zero.
size_t capacity () const
Returns the number of elements this vector can hold without growing.
void setCapacity (size_t size)
Sets the capacity.
const TYPE & itemAt (size_t index) const
Returns the item at the specified location in this vector.
const TYPE & firstItem () const
Returns the first item in this vector.
const TYPE & lastItem () const
Returns the last item in this vector.
void append (const TYPE &item, size_t numItems=1)
Adds the specified item at the end of this vector.
void appendVector (const Vector< TYPE > &vector)
Adds the items in the specified vector to the end of this vector.
void insertAt (const TYPE &prototype_item, size_t index, size_t numItems=1)
Inserts the specified item into this vector at the specified location.
void insertVectorAt (const Vector< TYPE > &vector, size_t index)
Inserts the items in the specified vector at the specified location in this vector.
void removeAt (size_t index, size_t count=1)
Removes items at the specified location from this vector.
void replaceAt (const TYPE &item, size_t index)
Replaces the element at the specified location in this vector with the specified item.
Array< TYPE > toArray () const
Returns a new array containing all elements contained in this vector.
const TYPE & top () const
Stack-usage of the vector.
void pop ()
Pops the top of the stack (removes the last element).
void push (const TYPE &item)
Pushes an item on the top of the stack.
TYPE * innerDatum ()
Acquires the inner datum for editing.
const TYPE * innerDatum () const
Acquires the inner datum for reading.
Protected Member Functions
virtual void do_construct (void *storage, size_t num) const
Constructs datum at specified storage.
virtual void do_destroy (void *storage, size_t num) const
Destories datum at specified storage.
virtual void do_copy (void *dest, const void *from, size_t num) const
Copies datum from one specified momory to another.
virtual void do_splat (void *dest, const void *item, size_t num) const
Copies numbers of the same item to specified location.
virtual void do_move_forward (void *dest, const void *from, size_t num) const
Backward copies numbers of datum to specified location.
virtual void do_move_backward (void *dest, const void *from, size_t num) const
Forward copies numbers of datum to specified location.
Detailed Description
template<class TYPE>
class gaia::base::Vector< TYPE >
This class implements the vector data structure.
The main templated vector class ensuring type safety while making use of VectorImpl. This is the class users want to use.
This class implements templated vector class, which makes use of VectorImpl. Developers should use Vector class instead of VectorImpl.
 // Creates a vector
 Vector<String> vec;
 // Adds data into vector
 for (size_t i = 0; i < 50; i++) {
        vec.append(String::valueOf(i));
 }
 // Gets vector size
 size_t vec_size = vec.size();
 // Inserts item at index 10.
 vec.insert(String::valueOf(2011), 10);
 // Replaces item at index 20.
 vec.replaceAt(String::valueOf(2011), 20);
 // Inserts item at index 30.
 vec.insert(String::valueOf(2011), 30);
 // Transforms vector to array.
 Array<String> p_tv = vec.toArray();
 // Clears all
 vec.clear();
Definition at line 73 of file Vector.h.
Constructor & Destructor Documentation
template<class TYPE > gaia::base::Vector< TYPE >::Vector () [inline]
Constructs a new vector using the default capacity.
Definition at line 407 of file Vector.h.
template<class TYPE> gaia::base::Vector< TYPE >::Vector (const Vector< TYPE > & rhs) [inline]
Constructs a new item of Vector containing the elements in rhs.
The order of the elements in the new Vector is dependent on the iteration order of the seed collection.
Parameters:
rhs the vector of elements to add.
Definition at line 416 of file Vector.h.
template<class TYPE > gaia::base::Vector< TYPE >::~Vector () [inline, virtual]
Destructor of Vector.
It calls finish_vector() to destory vector.
Definition at line 421 of file Vector.h.
Member Function Documentation
template<class TYPE> void gaia::base::Vector< TYPE >::append (const TYPE & item, size_t numItems = 1) [inline]
Adds the specified item at the end of this vector.
Parameters:
item The item to add to the vector.
numItems The number of items to be added.
Definition at line 483 of file Vector.h.
References gaia::base::VectorImpl::append().
Referenced by gaia::ui::IItemProvider::addToRecycler(), gaia::base::Vector2D< TYPE >::append(), gaia::base::Vector2D< TYPE >::appendVector(), gaia::core::Parcel::createTypedVectorN(), gaia::base::Vector2D< TYPE >::insertAt(), gaia::base::Vector2D< TYPE >::insertVectorAt(), gaia::base::HashMap< KEY, VAL >::keys(), gaia::core::Parcel::readTypedVector(), gaia::base::Vector2D< TYPE >::setIdvCapacity(), and gaia::base::HashMap< KEY, VAL >::values().
template<class TYPE> void gaia::base::Vector< TYPE >::appendVector (const Vector< TYPE > & vector) [inline]
Adds the items in the specified vector to the end of this vector.
Parameters:
vector The vector which possesses desired datum.
Returns:
True if this vector is modified, false otherwise.
Definition at line 488 of file Vector.h.
References gaia::base::VectorImpl::appendVector().
Referenced by gaia::base::Vector2D< TYPE >::appendVector().
template<class TYPE > size_t gaia::base::Vector< TYPE >::capacity () const [inline]
Returns the number of elements this vector can hold without growing.
Returns:
The capacity of this vector.
Reimplemented from gaia::base::VectorImpl.
Definition at line 458 of file Vector.h.
References gaia::base::VectorImpl::capacity().
template<class TYPE > void gaia::base::Vector< TYPE >::clear () [inline]
Removes all elements from this vector, leaving it empty.
See also:
isEmpty
size
Reimplemented from gaia::base::VectorImpl.
Definition at line 443 of file Vector.h.
References gaia::base::VectorImpl::clear().
Referenced by gaia::base::Vector2D< TYPE >::clear().
template<class TYPE > void gaia::base::Vector< TYPE >::do_construct (void * storage, size_t num) const [protected, virtual]
Constructs datum at specified storage.
It calls the constructor (if there is) specified by Vector template parameter <TYPE> to execute construct process.
See also:
gaia::base::construct_type()
Parameters:
storage Memory address of Datum.
num Number of datum in the unit of data type <TYPE>.
Implements gaia::base::VectorImpl.
Definition at line 547 of file Vector.h.
template<class TYPE > void gaia::base::Vector< TYPE >::do_copy (void * dest, const void * from, size_t num) const [protected, virtual]
Copies datum from one specified momory to another.
It calls the copy constructor (if there is) specified by Voctor tamplate parameter <TYPE> to execute copy process.
See also:
gaia::base::copy_type()
Parameters:
dest Destination that datum to be copied to.
from Memory of datum to be copied.
num Number of datum in the unit of data type <TYPE>
Implements gaia::base::VectorImpl.
Definition at line 557 of file Vector.h.
template<class TYPE > void gaia::base::Vector< TYPE >::do_destroy (void * storage, size_t num) const [protected, virtual]
Destories datum at specified storage.
It calls the destructor (if there is) specified by Vector template parameter <TYPE> to execute destory process.
See also:
gaia::base::destroy_type()
Parameters:
storage Memory address of Datum.
num Number of datum in the unit of data type <TYPE>.
Implements gaia::base::VectorImpl.
Definition at line 552 of file Vector.h.
template<class TYPE > void gaia::base::Vector< TYPE >::do_move_backward (void * dest, const void * from, size_t num) const [protected, virtual]
Forward copies numbers of datum to specified location.
It calls the copy constructor (if there is) specified by Vector tamplate parameter <TYPE> to execute copy process.
See also:
gaia::base::move_backward_type()
Parameters:
dest Destination that datum to be copied to.
from Memory of datum to be copied.
num Number of datum in the unit of data type <TYPE>
Implements gaia::base::VectorImpl.
Definition at line 576 of file Vector.h.
template<class TYPE > void gaia::base::Vector< TYPE >::do_move_forward (void * dest, const void * from, size_t num) const [protected, virtual]
Backward copies numbers of datum to specified location.
It calls the copy constructor (if there is) specified by Vector tamplate parameter <TYPE> to execute copy process.
See also:
gaia::base::move_forward_type()
Parameters:
dest Destination that datum to be copied to.
from Memory of datum to be copied.
num Number of datum in the unit of data type <TYPE>
Implements gaia::base::VectorImpl.
Definition at line 569 of file Vector.h.
template<class TYPE > void gaia::base::Vector< TYPE >::do_splat (void * dest, const void * item, size_t num) const [protected, virtual]
Copies numbers of the same item to specified location.
It calls the copy constructor (if there is) specified by Vector tamplate parameter <TYPE> to execute copy process.
See also:
gaia::base::splat_type()
Parameters:
dest Destination that datum to be copied to.
item Memory of datum to be copied.
num Number of datum in the unit of data type <TYPE>
Implements gaia::base::VectorImpl.
Definition at line 563 of file Vector.h.
template<class TYPE > const TYPE & gaia::base::Vector< TYPE >::firstItem () const [inline]
Returns the first item in this vector.
Returns:
The item at the first position.
See also:
itemAt
lastItem
size
Definition at line 473 of file Vector.h.
template<class TYPE > TYPE * gaia::base::Vector< TYPE >::innerDatum () [inline]
Acquires the inner datum for editing.
Returns:
Non-const datum address.
Definition at line 536 of file Vector.h.
References gaia::base::VectorImpl::editArrayImpl().
template<class TYPE > const TYPE * gaia::base::Vector< TYPE >::innerDatum () const [inline]
Acquires the inner datum for reading.
Returns:
Const datum address.
Definition at line 541 of file Vector.h.
References gaia::base::VectorImpl::arrayImpl().
template<class TYPE> void gaia::base::Vector< TYPE >::insertAt (const TYPE & prototype_item, size_t index, size_t numItems = 1) [inline]
Inserts the specified item into this vector at the specified location.
This item is inserted before any previous element at the specified location. All elements with an index equal or greater than location have their index increased by 1. If the location is equal to the size of this vector, the item is added at the end. The specified items are initialized from prototype items.
Parameters:
prototype_item The item to insert in this vector.
index The index at which to insert the element.
numItems Number of items to be inserted.
See also:
append
size
Definition at line 493 of file Vector.h.
References gaia::base::VectorImpl::insertAt().
Referenced by gaia::base::Vector2D< TYPE >::insertAt().
template<class TYPE> void gaia::base::Vector< TYPE >::insertVectorAt (const Vector< TYPE > & vector, size_t index) [inline]
Inserts the items in the specified vector at the specified location in this vector.
The items are inserted in the order in which they are returned from the vector iterator. The items with an index equal or higher than vector size have their index increased by the size of the added collection.
Parameters:
vector Given vector to be inserted into list vector.
index The location to insert the items.
Returns:
True if this vector is modified, false otherwise.
Definition at line 498 of file Vector.h.
References gaia::base::VectorImpl::insertVectorAt().
Referenced by gaia::base::Vector2D< TYPE >::insertVectorAt().
template<class TYPE > bool gaia::base::Vector< TYPE >::isEmpty () const [inline]
Returns if this vector has no elements, a size of zero.
Returns:
True if this vector has no elements, false otherwise.
See also:
size
Reimplemented from gaia::base::VectorImpl.
Definition at line 453 of file Vector.h.
References gaia::base::VectorImpl::isEmpty().
template<class TYPE > const TYPE & gaia::base::Vector< TYPE >::itemAt (size_t index) const [inline]
Returns the item at the specified location in this vector.
Parameters:
index The index of the item to return in this vector.
Returns:
The item at the specified location.
See also:
size
Definition at line 468 of file Vector.h.
template<class TYPE > const TYPE & gaia::base::Vector< TYPE >::lastItem () const [inline]
Returns the last item in this vector.
Returns:
The item at the last position.
See also:
itemAt
firstItem
size
Definition at line 478 of file Vector.h.
template<class TYPE> const Vector< TYPE > & gaia::base::Vector< TYPE >::operator= (const Vector< TYPE > & rhs) const [inline]
Const-to-const assignment operation of vector.
Because copy-on-write mechanism, the original datum possesses by this vector is releaseed and this vector will acquire to possess datum on rhs vector.
Definition at line 432 of file Vector.h.
References gaia::base::VectorImpl::operator=().
template<class TYPE> Vector< TYPE > & gaia::base::Vector< TYPE >::operator= (const Vector< TYPE > & rhs) [inline]
Nonconst-to-nonconst assignment operation of vector with copy-on-write mechanism mentioned before.
Definition at line 426 of file Vector.h.
References gaia::base::VectorImpl::operator=().
template<class TYPE > const TYPE & gaia::base::Vector< TYPE >::operator[] (size_t index) const [inline]
Read-only access to an item at a given index.
Parameters:
index The index of vector.
Definition at line 438 of file Vector.h.
template<class TYPE > void gaia::base::Vector< TYPE >::pop () [inline]
Pops the top of the stack (removes the last element).
No-op if the stack is empty.
Reimplemented from gaia::base::VectorImpl.
Definition at line 526 of file Vector.h.
References gaia::base::VectorImpl::pop().
template<class TYPE> void gaia::base::Vector< TYPE >::push (const TYPE & item) [inline]
Pushes an item on the top of the stack.
Parameters:
item The item to be pushed into this vector.
Definition at line 531 of file Vector.h.
References gaia::base::VectorImpl::push().
template<class TYPE > void gaia::base::Vector< TYPE >::removeAt (size_t index, size_t count = 1) [inline]
Removes items at the specified location from this vector.
All elements with an index bigger than location + count have their index decreased by count.
Parameters:
index The index of the first item to be removed.
count Number of items to be removed.
Definition at line 504 of file Vector.h.
References gaia::base::VectorImpl::removeItemsAt().
Referenced by gaia::core::Parcel::readTypedVector(), and gaia::base::Vector2D< TYPE >::removeAt().
template<class TYPE> void gaia::base::Vector< TYPE >::replaceAt (const TYPE & item, size_t index) [inline]
Replaces the element at the specified location in this vector with the specified item.
Parameters:
item Specified item used to replace.
index The index at which to put the specified item.
See also:
size
Definition at line 509 of file Vector.h.
References gaia::base::VectorImpl::replaceAt().
Referenced by gaia::core::Parcel::readTypedVector(), and gaia::base::Vector2D< TYPE >::replaceAt().
template<class TYPE > void gaia::base::Vector< TYPE >::setCapacity (size_t size) [inline]
Sets the capacity.
Capacity can never be reduced less than size()
Parameters:
size The assigned size of vector. Be aware that the size should be smaller its capacity.
Reimplemented from gaia::base::VectorImpl.
Definition at line 463 of file Vector.h.
References gaia::base::VectorImpl::setCapacity().
Referenced by gaia::base::HashMap< KEY, VAL >::keys(), gaia::base::Vector2D< TYPE >::setIdvCapacity(), and gaia::base::HashMap< KEY, VAL >::values().
template<class TYPE > size_t gaia::base::Vector< TYPE >::size () const [inline]
Returns the number of elements in this vector.
Returns:
The number of elements in this vector.
Reimplemented from gaia::base::VectorImpl.
Definition at line 448 of file Vector.h.
References gaia::base::VectorImpl::size().
Referenced by gaia::base::Vector2D< TYPE >::operator=(), gaia::core::Parcel::readTypedVector(), gaia::base::Vector2D< TYPE >::Vector2D(), and gaia::core::Parcel::writeTypedVector().
template<class TYPE > Array< TYPE > gaia::base::Vector< TYPE >::toArray () const
Returns a new array containing all elements contained in this vector.
Returns:
an array of the elements from this vector.
Definition at line 514 of file Vector.h.
References gaia::base::Array< TYPE >::array(), gaia::base::VectorImpl::copyIntoArray(), and gaia::base::Array< TYPE >::length().
template<class TYPE > const TYPE & gaia::base::Vector< TYPE >::top () const [inline]
Stack-usage of the vector.
Returns the top of the stack.
Returns:
The top of the stack (the last element)
Definition at line 521 of file Vector.h.
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/base/Vector.h