gaia::core::GLES11Ext Class Reference
gaia::core::GLES11Ext Class Reference
#include <GLES11Ext.h>
Static Public Member Functions
static void glBlendEquationSeparateOES (int32_t modeRGB, int32_t modeAlpha)
static void glBlendFuncSeparateOES (int32_t srcRGB, int32_t dstRGB, int32_t srcAlpha, int32_t dstAlpha)
static void glBlendEquationOES (int32_t mode)
static void glDrawTexsOES (int16_t x, int16_t y, int16_t z, int16_t width, int16_t height)
static void glDrawTexiOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)
static void glDrawTexxOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)
static void glDrawTexsvOES (const gaia::base::Array< int16_t > &coords, int32_t offset)
static void glDrawTexsvOES (const gaia::base::Array< int16_t > &coords)
static void glDrawTexivOES (const gaia::base::Array< int32_t > &coords, int32_t offset)
static void glDrawTexivOES (const gaia::base::Array< int32_t > &coords)
static void glDrawTexxvOES (const gaia::base::Array< int32_t > &coords, int32_t offset)
static void glDrawTexxvOES (const gaia::base::Array< int32_t > &coords)
static void glDrawTexfOES (float x, float y, float z, float width, float height)
static void glDrawTexfvOES (const gaia::base::Array< float > &coords, int32_t offset)
static void glDrawTexfvOES (const gaia::base::Array< float > &coords)
static void glEGLImageTargetTexture2DOES (int32_t target, void *image)
static void glEGLImageTargetRenderbufferStorageOES (int32_t target, void *image)
static void glAlphaFuncxOES (int32_t func, int32_t ref)
static void glClearColorxOES (int32_t red, int32_t green, int32_t blue, int32_t alpha)
static void glClearDepthxOES (int32_t depth)
static void glClipPlanexOES (int32_t plane, const gaia::base::Array< int32_t > &equation, int32_t offset)
static void glClipPlanexOES (int32_t plane, const gaia::base::Array< int32_t > &equation)
static void glColor4xOES (int32_t red, int32_t green, int32_t blue, int32_t alpha)
static void glDepthRangexOES (int32_t zNear, int32_t zFar)
static void glFogxOES (int32_t pname, int32_t param)
static void glFogxvOES (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glFogxvOES (int32_t pname, const gaia::base::Array< int32_t > &params)
static void glFrustumxOES (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
static void glGetClipPlanexOES (int32_t pname, gaia::base::Array< int32_t > *eqn, int32_t offset)
static void glGetClipPlanexOES (int32_t pname, gaia::base::Array< int32_t > *eqn)
static void glGetFixedvOES (int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetFixedvOES (int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetLightxvOES (int32_t light, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetLightxvOES (int32_t light, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetMaterialxvOES (int32_t face, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetMaterialxvOES (int32_t face, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetTexEnvxvOES (int32_t env, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetTexEnvxvOES (int32_t env, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetTexParameterxvOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetTexParameterxvOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
static void glLightModelxOES (int32_t pname, int32_t param)
static void glLightModelxvOES (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glLightModelxvOES (int32_t pname, const gaia::base::Array< int32_t > &params)
static void glLightxOES (int32_t light, int32_t pname, int32_t param)
static void glLightxvOES (int32_t light, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glLightxvOES (int32_t light, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glLineWidthxOES (int32_t width)
static void glLoadMatrixxOES (const gaia::base::Array< int32_t > &m, int32_t offset)
static void glLoadMatrixxOES (const gaia::base::Array< int32_t > &m)
static void glMaterialxOES (int32_t face, int32_t pname, int32_t param)
static void glMaterialxvOES (int32_t face, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glMaterialxvOES (int32_t face, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glMultMatrixxOES (const gaia::base::Array< int32_t > &m, int32_t offset)
static void glMultMatrixxOES (const gaia::base::Array< int32_t > &m)
static void glMultiTexCoord4xOES (int32_t target, int32_t s, int32_t t, int32_t r, int32_t q)
static void glNormal3xOES (int32_t nx, int32_t ny, int32_t nz)
static void glOrthoxOES (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
static void glPointParameterxOES (int32_t pname, int32_t param)
static void glPointParameterxvOES (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glPointParameterxvOES (int32_t pname, const gaia::base::Array< int32_t > &params)
static void glPointSizexOES (int32_t size)
static void glPolygonOffsetxOES (int32_t factor, int32_t units)
static void glRotatexOES (int32_t angle, int32_t x, int32_t y, int32_t z)
static void glSampleCoveragexOES (int32_t value, bool invert)
static void glScalexOES (int32_t x, int32_t y, int32_t z)
static void glTexEnvxOES (int32_t target, int32_t pname, int32_t param)
static void glTexEnvxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glTexEnvxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glTexParameterxOES (int32_t target, int32_t pname, int32_t param)
static void glTexParameterxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glTexParameterxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glTranslatexOES (int32_t x, int32_t y, int32_t z)
static bool glIsRenderbufferOES (int32_t renderbuffer)
static void glBindRenderbufferOES (int32_t target, int32_t renderbuffer)
static void glDeleteRenderbuffersOES (int32_t n, const gaia::base::Array< int32_t > &renderbuffers, int32_t offset)
static void glDeleteRenderbuffersOES (int32_t n, const gaia::base::Array< int32_t > &renderbuffers)
static void glGenRenderbuffersOES (int32_t n, gaia::base::Array< int32_t > *renderbuffers, int32_t offset)
static void glGenRenderbuffersOES (int32_t n, gaia::base::Array< int32_t > *renderbuffers)
static void glRenderbufferStorageOES (int32_t target, int32_t int32_ternalformat, int32_t width, int32_t height)
static void glGetRenderbufferParameterivOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetRenderbufferParameterivOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
static bool glIsFramebufferOES (int32_t framebuffer)
static void glBindFramebufferOES (int32_t target, int32_t framebuffer)
static void glDeleteFramebuffersOES (int32_t n, const gaia::base::Array< int32_t > &framebuffers, int32_t offset)
static void glDeleteFramebuffersOES (int32_t n, const gaia::base::Array< int32_t > &framebuffers)
static void glGenFramebuffersOES (int32_t n, gaia::base::Array< int32_t > *framebuffers, int32_t offset)
static void glGenFramebuffersOES (int32_t n, gaia::base::Array< int32_t > *framebuffers)
static int32_t glCheckFramebufferStatusOES (int32_t target)
static void glFramebufferRenderbufferOES (int32_t target, int32_t attachment, int32_t renderbuffertarget, int32_t renderbuffer)
static void glFramebufferTexture2DOES (int32_t target, int32_t attachment, int32_t textarget, int32_t texture, int32_t level)
static void glGetFramebufferAttachmentParameterivOES (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetFramebufferAttachmentParameterivOES (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGenerateMipmapOES (int32_t target)
static void glCurrentPaletteMatrixOES (int32_t matrixpaletteindex)
static void glLoadPaletteFromModelViewMatrixOES ()
template<typename TYPE >
static void glMatrixIndexPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > &pointer_buf)
template<typename TYPE >
static void glWeightPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > &pointer_buf)
static void glDepthRangefOES (float zNear, float zFar)
static void glFrustumfOES (float left, float right, float bottom, float top, float zNear, float zFar)
static void glOrthofOES (float left, float right, float bottom, float top, float zNear, float zFar)
static void glClipPlanefOES (int32_t plane, const gaia::base::Array< float > &equation, int32_t offset)
static void glClipPlanefOES (int32_t plane, const gaia::base::Array< float > &equation)
static void glGetClipPlanefOES (int32_t pname, gaia::base::Array< float > *eqn, int32_t offset)
static void glGetClipPlanefOES (int32_t pname, gaia::base::Array< float > *eqn)
static void glClearDepthfOES (float depth)
static void glTexGenfOES (int32_t coord, int32_t pname, float param)
static void glTexGenfvOES (int32_t coord, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glTexGenfvOES (int32_t coord, int32_t pname, const gaia::base::Array< float > &params)
static void glTexGeniOES (int32_t coord, int32_t pname, int32_t param)
static void glTexGenivOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glTexGenivOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glTexGenxOES (int32_t coord, int32_t pname, int32_t param)
static void glTexGenxvOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glTexGenxvOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glGetTexGenfvOES (int32_t coord, int32_t pname, gaia::base::Array< float > *params, int32_t offset)
static void glGetTexGenfvOES (int32_t coord, int32_t pname, gaia::base::Array< float > *params)
static void glGetTexGenivOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetTexGenivOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetTexGenxvOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static void glGetTexGenxvOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > *params)
Private Member Functions
DISALLOW_COPY_AND_ASSIGN (GLES11Ext)
Detailed Description
Definition at line 14 of file GLES11Ext.h.
Member Function Documentation
gaia::core::GLES11Ext::DISALLOW_COPY_AND_ASSIGN (GLES11Ext) [private]
static void gaia::core::GLES11Ext::glAlphaFuncxOES (int32_t func, int32_t ref) [static]
static void gaia::core::GLES11Ext::glBindFramebufferOES (int32_t target, int32_t framebuffer) [static]
static void gaia::core::GLES11Ext::glBindRenderbufferOES (int32_t target, int32_t renderbuffer) [static]
static void gaia::core::GLES11Ext::glBlendEquationOES (int32_t mode) [static]
static void gaia::core::GLES11Ext::glBlendEquationSeparateOES (int32_t modeRGB, int32_t modeAlpha) [static]
static void gaia::core::GLES11Ext::glBlendFuncSeparateOES (int32_t srcRGB, int32_t dstRGB, int32_t srcAlpha, int32_t dstAlpha) [static]
static int32_t gaia::core::GLES11Ext::glCheckFramebufferStatusOES (int32_t target) [static]
static void gaia::core::GLES11Ext::glClearColorxOES (int32_t red, int32_t green, int32_t blue, int32_t alpha) [static]
static void gaia::core::GLES11Ext::glClearDepthfOES (float depth) [static]
static void gaia::core::GLES11Ext::glClearDepthxOES (int32_t depth) [static]
static void gaia::core::GLES11Ext::glClipPlanefOES (int32_t plane, const gaia::base::Array< float > & equation) [static]
static void gaia::core::GLES11Ext::glClipPlanefOES (int32_t plane, const gaia::base::Array< float > & equation, int32_t offset) [static]
static void gaia::core::GLES11Ext::glClipPlanexOES (int32_t plane, const gaia::base::Array< int32_t > & equation, int32_t offset) [static]
static void gaia::core::GLES11Ext::glClipPlanexOES (int32_t plane, const gaia::base::Array< int32_t > & equation) [static]
static void gaia::core::GLES11Ext::glColor4xOES (int32_t red, int32_t green, int32_t blue, int32_t alpha) [static]
static void gaia::core::GLES11Ext::glCurrentPaletteMatrixOES (int32_t matrixpaletteindex) [static]
static void gaia::core::GLES11Ext::glDeleteFramebuffersOES (int32_t n, const gaia::base::Array< int32_t > & framebuffers, int32_t offset) [static]
static void gaia::core::GLES11Ext::glDeleteFramebuffersOES (int32_t n, const gaia::base::Array< int32_t > & framebuffers) [static]
static void gaia::core::GLES11Ext::glDeleteRenderbuffersOES (int32_t n, const gaia::base::Array< int32_t > & renderbuffers, int32_t offset) [static]
static void gaia::core::GLES11Ext::glDeleteRenderbuffersOES (int32_t n, const gaia::base::Array< int32_t > & renderbuffers) [static]
static void gaia::core::GLES11Ext::glDepthRangefOES (float zNear, float zFar) [static]
static void gaia::core::GLES11Ext::glDepthRangexOES (int32_t zNear, int32_t zFar) [static]
static void gaia::core::GLES11Ext::glDrawTexfOES (float x, float y, float z, float width, float height) [static]
static void gaia::core::GLES11Ext::glDrawTexfvOES (const gaia::base::Array< float > & coords, int32_t offset) [static]
static void gaia::core::GLES11Ext::glDrawTexfvOES (const gaia::base::Array< float > & coords) [static]
static void gaia::core::GLES11Ext::glDrawTexiOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height) [static]
static void gaia::core::GLES11Ext::glDrawTexivOES (const gaia::base::Array< int32_t > & coords, int32_t offset) [static]
static void gaia::core::GLES11Ext::glDrawTexivOES (const gaia::base::Array< int32_t > & coords) [static]
static void gaia::core::GLES11Ext::glDrawTexsOES (int16_t x, int16_t y, int16_t z, int16_t width, int16_t height) [static]
static void gaia::core::GLES11Ext::glDrawTexsvOES (const gaia::base::Array< int16_t > & coords) [static]
static void gaia::core::GLES11Ext::glDrawTexsvOES (const gaia::base::Array< int16_t > & coords, int32_t offset) [static]
static void gaia::core::GLES11Ext::glDrawTexxOES (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height) [static]
static void gaia::core::GLES11Ext::glDrawTexxvOES (const gaia::base::Array< int32_t > & coords, int32_t offset) [static]
static void gaia::core::GLES11Ext::glDrawTexxvOES (const gaia::base::Array< int32_t > & coords) [static]
static void gaia::core::GLES11Ext::glEGLImageTargetRenderbufferStorageOES (int32_t target, void * image) [static]
static void gaia::core::GLES11Ext::glEGLImageTargetTexture2DOES (int32_t target, void * image) [static]
static void gaia::core::GLES11Ext::glFogxOES (int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glFogxvOES (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glFogxvOES (int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glFramebufferRenderbufferOES (int32_t target, int32_t attachment, int32_t renderbuffertarget, int32_t renderbuffer) [static]
static void gaia::core::GLES11Ext::glFramebufferTexture2DOES (int32_t target, int32_t attachment, int32_t textarget, int32_t texture, int32_t level) [static]
static void gaia::core::GLES11Ext::glFrustumfOES (float left, float right, float bottom, float top, float zNear, float zFar) [static]
static void gaia::core::GLES11Ext::glFrustumxOES (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar) [static]
static void gaia::core::GLES11Ext::glGenerateMipmapOES (int32_t target) [static]
static void gaia::core::GLES11Ext::glGenFramebuffersOES (int32_t n, gaia::base::Array< int32_t > * framebuffers, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGenFramebuffersOES (int32_t n, gaia::base::Array< int32_t > * framebuffers) [static]
static void gaia::core::GLES11Ext::glGenRenderbuffersOES (int32_t n, gaia::base::Array< int32_t > * renderbuffers, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGenRenderbuffersOES (int32_t n, gaia::base::Array< int32_t > * renderbuffers) [static]
static void gaia::core::GLES11Ext::glGetClipPlanefOES (int32_t pname, gaia::base::Array< float > * eqn, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetClipPlanefOES (int32_t pname, gaia::base::Array< float > * eqn) [static]
static void gaia::core::GLES11Ext::glGetClipPlanexOES (int32_t pname, gaia::base::Array< int32_t > * eqn, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetClipPlanexOES (int32_t pname, gaia::base::Array< int32_t > * eqn) [static]
static void gaia::core::GLES11Ext::glGetFixedvOES (int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetFixedvOES (int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetFramebufferAttachmentParameterivOES (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetFramebufferAttachmentParameterivOES (int32_t target, int32_t attachment, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetLightxvOES (int32_t light, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetLightxvOES (int32_t light, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetMaterialxvOES (int32_t face, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetMaterialxvOES (int32_t face, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetRenderbufferParameterivOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetRenderbufferParameterivOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetTexEnvxvOES (int32_t env, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetTexEnvxvOES (int32_t env, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetTexGenfvOES (int32_t coord, int32_t pname, gaia::base::Array< float > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetTexGenfvOES (int32_t coord, int32_t pname, gaia::base::Array< float > * params) [static]
static void gaia::core::GLES11Ext::glGetTexGenivOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetTexGenivOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetTexGenxvOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetTexGenxvOES (int32_t coord, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES11Ext::glGetTexParameterxvOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glGetTexParameterxvOES (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params) [static]
static bool gaia::core::GLES11Ext::glIsFramebufferOES (int32_t framebuffer) [static]
static bool gaia::core::GLES11Ext::glIsRenderbufferOES (int32_t renderbuffer) [static]
static void gaia::core::GLES11Ext::glLightModelxOES (int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glLightModelxvOES (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glLightModelxvOES (int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glLightxOES (int32_t light, int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glLightxvOES (int32_t light, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glLightxvOES (int32_t light, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glLineWidthxOES (int32_t width) [static]
static void gaia::core::GLES11Ext::glLoadMatrixxOES (const gaia::base::Array< int32_t > & m, int32_t offset) [static]
static void gaia::core::GLES11Ext::glLoadMatrixxOES (const gaia::base::Array< int32_t > & m) [static]
static void gaia::core::GLES11Ext::glLoadPaletteFromModelViewMatrixOES () [static]
static void gaia::core::GLES11Ext::glMaterialxOES (int32_t face, int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glMaterialxvOES (int32_t face, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glMaterialxvOES (int32_t face, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
template<typename TYPE > static void gaia::core::GLES11Ext::glMatrixIndexPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > & pointer_buf) [inline, static]
Definition at line 211 of file GLES11Ext.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES11Ext::glMultiTexCoord4xOES (int32_t target, int32_t s, int32_t t, int32_t r, int32_t q) [static]
static void gaia::core::GLES11Ext::glMultMatrixxOES (const gaia::base::Array< int32_t > & m, int32_t offset) [static]
static void gaia::core::GLES11Ext::glMultMatrixxOES (const gaia::base::Array< int32_t > & m) [static]
static void gaia::core::GLES11Ext::glNormal3xOES (int32_t nx, int32_t ny, int32_t nz) [static]
static void gaia::core::GLES11Ext::glOrthofOES (float left, float right, float bottom, float top, float zNear, float zFar) [static]
static void gaia::core::GLES11Ext::glOrthoxOES (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar) [static]
static void gaia::core::GLES11Ext::glPointParameterxOES (int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glPointParameterxvOES (int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glPointParameterxvOES (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glPointSizexOES (int32_t size) [static]
static void gaia::core::GLES11Ext::glPolygonOffsetxOES (int32_t factor, int32_t units) [static]
static void gaia::core::GLES11Ext::glRenderbufferStorageOES (int32_t target, int32_t int32_ternalformat, int32_t width, int32_t height) [static]
static void gaia::core::GLES11Ext::glRotatexOES (int32_t angle, int32_t x, int32_t y, int32_t z) [static]
static void gaia::core::GLES11Ext::glSampleCoveragexOES (int32_t value, bool invert) [static]
static void gaia::core::GLES11Ext::glScalexOES (int32_t x, int32_t y, int32_t z) [static]
static void gaia::core::GLES11Ext::glTexEnvxOES (int32_t target, int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glTexEnvxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glTexEnvxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glTexGenfOES (int32_t coord, int32_t pname, float param) [static]
static void gaia::core::GLES11Ext::glTexGenfvOES (int32_t coord, int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES11Ext::glTexGenfvOES (int32_t coord, int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glTexGeniOES (int32_t coord, int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glTexGenivOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glTexGenivOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glTexGenxOES (int32_t coord, int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glTexGenxvOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glTexGenxvOES (int32_t coord, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glTexParameterxOES (int32_t target, int32_t pname, int32_t param) [static]
static void gaia::core::GLES11Ext::glTexParameterxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES11Ext::glTexParameterxvOES (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES11Ext::glTranslatexOES (int32_t x, int32_t y, int32_t z) [static]
template<typename TYPE > static void gaia::core::GLES11Ext::glWeightPointerOES (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > & pointer_buf) [inline, static]
Definition at line 216 of file GLES11Ext.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/GLES11Ext.h