gaia::core::Export< CLASS, Subscriber > Class Template Reference
gaia::core::Export< CLASS, Subscriber > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static Subscriber * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, Subscriber >
Definition at line 445 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, Subscriber >::Export () [private]
Definition at line 469 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, Subscriber >::constructor () [static, private]
Definition at line 473 of file Export.h.
References gaia::core::COMPONENT_SUBSCRIBER, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, Subscriber >::destructor () [static, private]
Definition at line 481 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > Subscriber * gaia::core::Export< CLASS, Subscriber >::maker () [static, private]
Definition at line 486 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h