gaia::core::Instrumentation Class Reference
gaia::core::Instrumentation Class Reference
Base class for implementing application Instrumentation.
#include <Instrumentation.h>
Public Types
enum enumStatus { STATUS_EXIT = -1, STATUS_OK }
Status.
Public Member Functions
Instrumentation ()
virtual ~Instrumentation ()
virtual void onCreate (Persistence *arguments)
Called when the Instrumentation is starting, before any application code has been loaded.
void start ()
Create and start a new thread in which to run instrumentation.
virtual void onStart ()
Method where the instrumentation thread enters execution.
void sendStatus (int32_t resultCode, Persistence *results)
Provide a status report about the application.
void finish (int32_t resultCode, Persistence *results)
Terminate instrumentation of the application.
void setAutomaticPerformanceSnapshots ()
void startPerformanceSnapshot ()
void endPerformanceSnapshot ()
virtual void onDestroy ()
Called when the instrumented application is stopping, after all of the normal application cleanup has occurred.
Context * getContext ()
Return the Context of this Instrumentation's package.
Context * getTargetContext ()
Return a Context for the target application being Instrumentationed.
bool isProfiling ()
Check whether this Instrumentation was started with profiling enabled.
void startProfiling ()
This method will start profiling if isProfiling() returns true.
void stopProfiling ()
Stops profiling if isProfiling() returns true.
void setInTouchMode (bool inTouch)
Force the global system in or out of touch mode.
void waitForIdleSync ()
Synchronously wait for the application to be idle.
void runOnMainSync (gaia::core::WorkItem *workItem)
Execute a call on the application's main thread, blocking until it is complete.
Page * startPageSync (Demand *demand)
Start a new page and wait for it to begin running before returning.
bool invokeMenuActionSync (Page *targetPage, int32_t id, int32_t flag)
Execute a particular menu item.
bool invokeContextMenuAction (Page *targetPage, int32_t id, int32_t flag)
Show the context menu for the currently focused view and executes a particular context menu item.
void sendStringSync (const gaia::base::String &text)
Sends the key events corresponding to the text to the app being instrumented.
void sendKeySync (KeyEvent *event)
Send a key event to the currently focused window/view and wait for it to be processed.
void sendKeyDownUpSync (int32_t key)
Sends an up and down key event sync to the currently focused window.
void sendCharacterSync (int32_t keyCode)
Higher-level method for sending both the down and up key events for a particular character key code.
void sendPointerSync (MotionEvent *event)
Dispatch a pointer event.
void sendTrackballEventSync (MotionEvent *event)
Dispatch a trackball event.
Page * newPage (const gaia::base::String &className, gaia::testing::MockPage *parent, Context *context, Demand *demand)
Perform instantiation of an Page object.
void callPageOnInit (Page *page, Persistence *icicle)
Perform calling of an Page's Page#onInit method.
void callPageOnTear (Page *page)
void callPageOnRestoreInstanceState (Page *page, Persistence *savedInstanceState)
Perform calling of an Page's Page#onRestoreInstanceState method.
void callPageOnNewDemand (Page *page, Demand *demand)
Perform calling of an Page's Page#onNewDemand method.
void callPageOnStart (Page *page)
Perform calling of an Page's Page#onStart method.
void callPageOnRestart (Page *page)
Perform calling of an Page's Page#onRestart method.
void callPageOnResume (Page *page)
Perform calling of an Page's Page#onResume method.
void callPageOnStop (Page *page)
Perform calling of an Page's Page#onStop method.
void callPageOnSaveInstanceState (Page *page, Persistence *outState)
Perform calling of an Page's Page#onSaveInstanceState method.
void callPageOnPause (Page *page)
Perform calling of an Page's Page#onPause method.
void callPageOnUserLeaving (Page *page)
Perform calling of an Page's Page#onUserLeaveHint method.
Detailed Description
Base class for implementing application Instrumentation.
Base class for implementing application Instrumentation code. When running with Instrumentation turned on, this class will be instantiated for you before any of the application code, allowing you to monitor all of the interaction the system has with the application. An Instrumentation implementation is described to the system through an AndroidManifest.xml's <instrumentation> tag.
 // Header file: InstrumentationTest.h
 #include <gaia/core/Instrumentation.h>
 #include <gaia/core/Persistence.h>
 class InstrumentationTest : public gaia::core::Instrumentation
 {
 public:
     InstrumentationTest();
     virtual ~InstrumentationTest();
     virtual void onCreate(gaia::core::Persistence* arguments);
     virtual void onStart();
 };
 // Implementation file
 #include "InstrumentationTest.h"
 using namespace gaia::core;
 InstrumentationTest::InstrumentationTest() {
     // Do something.
 }
 InstrumentationTest::~InstrumentationTest() {
 }
 void InstrumentationTest::onCreate(Persistence* arguments) {
     // Do something before loading application code.
 }
 void InstrumentationTest::onStart() {
     // Do something to interacte with target application in a separate thread.
     // The target application is set in the android:targetPackage attribute
     // in AndroidManifest.xml
 }
Definition at line 68 of file Instrumentation.h.
Member Enumeration Documentation
enum gaia::core::Instrumentation::enumStatus
Status.
Enumerator:
STATUS_EXIT
STATUS_OK
Definition at line 74 of file Instrumentation.h.
Constructor & Destructor Documentation
gaia::core::Instrumentation::Instrumentation ()
virtual gaia::core::Instrumentation::~Instrumentation () [virtual]
Member Function Documentation
void gaia::core::Instrumentation::callPageOnInit (Page * page, Persistence * icicle)
Perform calling of an Page's Page#onInit method.
The default implementation simply calls through to that method.
Parameters:
page The page being created.
icicle The previously frozen state (or NULL) to pass through to onInit().
void gaia::core::Instrumentation::callPageOnNewDemand (Page * page, Demand * demand)
Perform calling of an Page's Page#onNewDemand method.
The default implementation simply calls through to that method.
Parameters:
page The Page receiving a new Demand.
demand The new Demand being received.
void gaia::core::Instrumentation::callPageOnPause (Page * page)
Perform calling of an Page's Page#onPause method.
The default implementation simply calls through to that method.
Parameters:
page The Page being paused.
void gaia::core::Instrumentation::callPageOnRestart (Page * page)
Perform calling of an Page's Page#onRestart method.
The default implementation simply calls through to that method.
Parameters:
page The Page being restarted.
void gaia::core::Instrumentation::callPageOnRestoreInstanceState (Page * page, Persistence * savedInstanceState)
Perform calling of an Page's Page#onRestoreInstanceState method.
The default implementation simply calls through to that method.
Parameters:
page The Page being restored.
savedInstanceState The previously saved state being restored.
void gaia::core::Instrumentation::callPageOnResume (Page * page)
Perform calling of an Page's Page#onResume method.
The default implementation simply calls through to that method.
Parameters:
page The Page being resumed.
void gaia::core::Instrumentation::callPageOnSaveInstanceState (Page * page, Persistence * outState)
Perform calling of an Page's Page#onSaveInstanceState method.
The default implementation simply calls through to that method.
Parameters:
page The Page being saved.
outState The Persistence to pass to the call.
void gaia::core::Instrumentation::callPageOnStart (Page * page)
Perform calling of an Page's Page#onStart method.
The default implementation simply calls through to that method.
Parameters:
page The Page being started.
void gaia::core::Instrumentation::callPageOnStop (Page * page)
Perform calling of an Page's Page#onStop method.
The default implementation simply calls through to that method.
Parameters:
page The page being stopped.
void gaia::core::Instrumentation::callPageOnTear (Page * page)
void gaia::core::Instrumentation::callPageOnUserLeaving (Page * page)
Perform calling of an Page's Page#onUserLeaveHint method.
The default implementation simply calls through to that method.
Parameters:
page The Page being notified that the user has navigated away
void gaia::core::Instrumentation::endPerformanceSnapshot ()
void gaia::core::Instrumentation::finish (int32_t resultCode, Persistence * results)
Terminate instrumentation of the application.
This will cause the application process to exit, removing this instrumentation from the next time the application is started.
Parameters:
resultCode Overall success/failure of instrumentation.
results Any results to send back to the code that started the instrumentation.
Context* gaia::core::Instrumentation::getContext ()
Return the Context of this Instrumentation's package.
Note that this is often different than the Context of the application being Instrumentationed, since the Instrumentation code often lives is a different package than that of the application it is running against. See getTargetContext to retrieve a Context for the target application.
Returns:
The Instrumentation's package context.
See also:
getTargetContext
Context* gaia::core::Instrumentation::getTargetContext ()
Return a Context for the target application being Instrumentationed.
Note that this is often different than the Context of the Instrumentation code, since the Instrumentation code often lives is a different package than that of the application it is running against. See getContext to retrieve a Context for the Instrumentation code.
Returns:
A Context in the target application.
See also:
getContext
bool gaia::core::Instrumentation::invokeContextMenuAction (Page * targetPage, int32_t id, int32_t flag)
Show the context menu for the currently focused view and executes a particular context menu item.
Parameters:
targetPage The page in question.
id The identifier associated with the context menu item.
flag Additional flags, if any.
Returns:
Whether the invocation was successful (for example, it could be false if item is disabled).
bool gaia::core::Instrumentation::invokeMenuActionSync (Page * targetPage, int32_t id, int32_t flag)
Execute a particular menu item.
Parameters:
targetPage The page in question.
id The identifier associated with the menu item.
flag Additional flags, if any.
Returns:
Whether the invocation was successful (for example, it could be false if item is disabled).
bool gaia::core::Instrumentation::isProfiling ()
Check whether this Instrumentation was started with profiling enabled.
Returns:
Returns true if profiling was enabled when starting, else false.
Page* gaia::core::Instrumentation::newPage (const gaia::base::String & className, gaia::testing::MockPage * parent, Context * context, Demand * demand)
Perform instantiation of an Page object.
This method is intended for use with unit tests, such as gaia/testing/PageUnitTestCase. The page will be useable locally but will be missing some of the linkages necessary for use within the sytem.
Parameters:
className The ClassName of the desired Page
parent The parent Page (if any)
context The base context for the activity to use
demand The demand that started this Page
Returns:
Returns the instantiated page
virtual void gaia::core::Instrumentation::onCreate (Persistence * arguments) [virtual]
Called when the Instrumentation is starting, before any application code has been loaded.
Usually this will be implemented to simply start the Instrumentation thread, which will then continue execution in onStart.
If you do not need your own thread -- that is you are writing your Instrumentation to be completely asynchronous (returning to the event loop so that the application can run), you can simply begin your Instrumentation here, for example call Context#startPage to begin the appropriate first page of the application.
Parameters:
arguments Any additional arguments that were supplied when the instrumentation was started.
Reimplemented in gaia::testing::InstrumentationTestRunner.
virtual void gaia::core::Instrumentation::onDestroy () [virtual]
Called when the instrumented application is stopping, after all of the normal application cleanup has occurred.
virtual void gaia::core::Instrumentation::onStart () [virtual]
Method where the instrumentation thread enters execution.
This allows you to run your instrumentation code in a separate thread than the application, so that it can perform blocking operation such as sendKeySync or startPageSync.
You will typically want to call finish() when this function is done, to end your instrumentation.
Reimplemented in gaia::testing::InstrumentationTestRunner.
void gaia::core::Instrumentation::runOnMainSync (gaia::core::WorkItem * workItem)
Execute a call on the application's main thread, blocking until it is complete.
Useful for doing things that are not thread-safe, such as looking at or modifying the view hierarchy.
Parameters:
workItem The code to run on the main thread.
void gaia::core::Instrumentation::sendCharacterSync (int32_t keyCode)
Higher-level method for sending both the down and up key events for a particular character key code.
Equivalent to creating both KeyEvent objects by hand and calling sendKeySync. The event appears as if it came from keyboard 0, the built in one.
Parameters:
keyCode The key code of the character to send.
void gaia::core::Instrumentation::sendKeyDownUpSync (int32_t key)
Sends an up and down key event sync to the currently focused window.
Parameters:
key The integer keycode for the event.
Referenced by gaia::testing::InstrumentationTestCase< TestFixture >::sendKeys(), and gaia::testing::InstrumentationTestCase< TestFixture >::sendRepeatedKeys().
void gaia::core::Instrumentation::sendKeySync (KeyEvent * event)
Send a key event to the currently focused window/view and wait for it to be processed.
Finished at some point after the recipient has returned from its event processing, though it may not have completely finished reacting from the event -- for example, if it needs to update its display as a result, it may still be in the process of doing that.
Parameters:
event The event to send to the current focus.
void gaia::core::Instrumentation::sendPointerSync (MotionEvent * event)
Dispatch a pointer event.
Finished at some point after the recipient has returned from its event processing, though it may not have completely finished reacting from the event -- for example, if it needs to update its display as a result, it may still be in the process of doing that.
Parameters:
event A motion event describing the pointer action.
void gaia::core::Instrumentation::sendStatus (int32_t resultCode, Persistence * results)
Provide a status report about the application.
Parameters:
resultCode Current success/failure of instrumentation.
results Any results to send back to the code that started the instrumentation.
void gaia::core::Instrumentation::sendStringSync (const gaia::base::String & text)
Sends the key events corresponding to the text to the app being instrumented.
Parameters:
text The text to be sent.
void gaia::core::Instrumentation::sendTrackballEventSync (MotionEvent * event)
Dispatch a trackball event.
Finished at some point after the recipient has returned from its event processing, though it may not have completely finished reacting from the event -- for example, if it needs to update its display as a result, it may still be in the process of doing that.
Parameters:
event A motion event describing the trackball action.
void gaia::core::Instrumentation::setAutomaticPerformanceSnapshots ()
void gaia::core::Instrumentation::setInTouchMode (bool inTouch)
Force the global system in or out of touch mode.
This can be used if your Instrumentation relies on the UI being in one more or the other when it starts.
Parameters:
inTouch Set to true to be in touch mode, false to be in focus mode.
void gaia::core::Instrumentation::start ()
Create and start a new thread in which to run instrumentation.
This new thread will call to onStart where you can implement the instrumentation.
Page* gaia::core::Instrumentation::startPageSync (Demand * demand)
Start a new page and wait for it to begin running before returning.
In addition to being synchronous, this method as some semantic differences from the standard Context#startPage call: the page component is resolved before talking with the page manager (its class name is specified in the Demand that this method ultimately starts), and it does not allow you to start pages that run in a different process. In addition, if the given Demand resolves to multiple pages, instead of displaying a dialog for the user to select an page, an exception will be thrown.
The function returns as soon as the page goes idle following the call to its Page#onInit. Generally this means it has gone through the full initialization including Page#onResume and drawn and displayed its initial window.
Parameters:
demand Description of the page to start.
See also:
Context::startPage
Referenced by gaia::testing::InstrumentationTestCase< TestFixture >::launchPageWithDemand().
void gaia::core::Instrumentation::startPerformanceSnapshot ()
void gaia::core::Instrumentation::startProfiling ()
This method will start profiling if isProfiling() returns true.
You should only call this method if you set the handleProfiling attribute in the manifest file for this Instrumentation to true.
void gaia::core::Instrumentation::stopProfiling ()
Stops profiling if isProfiling() returns true.
void gaia::core::Instrumentation::waitForIdleSync ()
Synchronously wait for the application to be idle.
Can not be called from the main application thread -- use start to execute Instrumentation in its own thread.
Referenced by gaia::testing::InstrumentationTestCase< TestFixture >::launchPageWithDemand(), gaia::testing::InstrumentationTestCase< TestFixture >::sendKeys(), and gaia::testing::InstrumentationTestCase< TestFixture >::sendRepeatedKeys().
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Instrumentation.h