gaia::core::Export< CLASS, gaia::ui::PreferencePage > Class Template Reference
gaia::core::Export< CLASS, gaia::ui::PreferencePage > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static gaia::ui::PreferencePage * maker ()
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, gaia::ui::PreferencePage >
Definition at line 545 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, gaia::ui::PreferencePage >::Export () [private]
Definition at line 568 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, gaia::ui::PreferencePage >::constructor () [static, private]
Definition at line 572 of file Export.h.
References gaia::core::COMPONENT_PREFERENCEPAGE, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, gaia::ui::PreferencePage >::destructor () [static, private]
Definition at line 578 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > gaia::ui::PreferencePage * gaia::core::Export< CLASS, gaia::ui::PreferencePage >::maker () [static, private]
Definition at line 584 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h