gaia::core::GLES10 Class Reference
gaia::core::GLES10 Class Reference
#include <GLES10.h>
Static Public Member Functions
template<typename TYPE >
static void glColorPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > &pointer_buf)
template<typename TYPE >
static void glNormalPointer (int32_t type, int32_t stride, const gaia::base::Array< TYPE > &pointer_buf)
template<typename TYPE >
static void glTexCoordPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > &pointer_buf)
template<typename TYPE >
static void glVertexPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > &pointer_buf)
static void glActiveTexture (int32_t texture)
static void glAlphaFunc (int32_t func, float ref)
static void glAlphaFuncx (int32_t func, int32_t ref)
static void glBindTexture (int32_t target, int32_t texture)
static void glBlendFunc (int32_t sfactor, int32_t dfactor)
static void glClear (int32_t mask)
static void glClearColor (float red, float green, float blue, float alpha)
static void glClearColorx (int32_t red, int32_t green, int32_t blue, int32_t alpha)
static void glClearDepthf (float depth)
static void glClearDepthx (int32_t depth)
static void glClearStencil (int32_t s)
static void glClientActiveTexture (int32_t texture)
static void glColor4f (float red, float green, float blue, float alpha)
static void glColor4x (int32_t red, int32_t green, int32_t blue, int32_t alpha)
static void glColorMask (bool red, bool green, bool blue, bool alpha)
static void glCompressedTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const gaia::base::ByteArray &imageData)
static void glCompressedTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t imageSize, const gaia::base::ByteArray &imageData)
static void glCopyTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border)
static void glCopyTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height)
static void glCullFace (int32_t mode)
static void glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > &Textures, int32_t offset)
static void glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > &Textures)
static void glDepthFunc (int32_t func)
static void glDepthMask (bool flag)
static void glDepthRangef (float zNear, float zFar)
static void glDepthRangex (int32_t zNear, int32_t zFar)
static void glDisable (int32_t cap)
static void glDisableClientState (int32_t array)
static void glDrawArrays (int32_t mode, int32_t first, int32_t count)
template<typename TYPE >
static void glDrawElements (int32_t mode, int32_t count, int32_t type, const gaia::base::Array< TYPE > &indices)
static void glEnable (int32_t cap)
static void glEnableClientState (int32_t array)
static void glFinish ()
static void glFlush ()
static void glFogf (int32_t pname, float param)
static void glFogfv (int32_t pname, const gaia::base::Array< float > &params)
static void glFogfv (int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glFogx (int32_t pname, int32_t param)
static void glFogxv (int32_t pname, const gaia::base::Array< int32_t > &params)
static void glFogxv (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glFrontFace (int32_t mode)
static void glFrustumf (float left, float right, float bottom, float top, float zNear, float zFar)
static void glFrustumx (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
static void glGenTextures (int32_t n, gaia::base::Array< uint32_t > *textures, int32_t offset)
static void glGenTextures (int32_t n, gaia::base::Array< uint32_t > *textures)
static int32_t glGetError ()
static void glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > *params)
static void glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
static gaia::base::String glGetString (int32_t name)
static void glHint (int32_t target, int32_t mode)
static void glLightModelf (int32_t pname, float param)
static void glLightModelfv (int32_t pname, const gaia::base::Array< float > &params)
static void glLightModelfv (int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glLightModelx (int32_t pname, int32_t param)
static void glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > &params)
static void glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glLightf (int32_t light, int32_t pname, float param)
static void glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > &params)
static void glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glLightx (int32_t light, int32_t pname, int32_t param)
static void glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > &params)
static void glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
static void glLineWidth (float width)
static void glLineWidthx (int32_t width)
static void glLoadIdentity ()
static void glLoadMatrixf (const gaia::base::Array< float > &m, int32_t offset)
static void glLoadMatrixf (const gaia::base::Array< float > &m)
static void glLoadMatrixx (const gaia::base::Array< int32_t > &m, int32_t offset)
static void glLoadMatrixx (const gaia::base::Array< int32_t > &m)
static void glLogicOp (int32_t opcode)
static void glMaterialf (int32_t face, int32_t pname, float param)
static void glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > &params)
static void glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glMaterialx (int32_t face, int32_t pname, int32_t param)
static void glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > &m)
static void glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > &m, int32_t offset)
static void glMatrixMode (int32_t mode)
static void glMultMatrixf (const gaia::base::Array< float > &m, int32_t offset)
static void glMultMatrixf (const gaia::base::Array< float > &m)
static void glMultMatrixx (const gaia::base::Array< int32_t > &m, int32_t offset)
static void glMultMatrixx (const gaia::base::Array< int32_t > &m)
static void glMultiTexCoord4f (int32_t target, float s, float t, float r, float q)
static void glMultiTexCoord4x (int32_t target, int32_t s, int32_t t, int32_t r, int32_t q)
static void glNormal3f (float nx, float ny, float nz)
static void glNormal3x (int32_t nx, int32_t ny, int32_t nz)
static void glOrthof (float left, float right, float bottom, float top, float zNear, float zFar)
static void glOrthox (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar)
static void glPixelStorei (int32_t pname, int32_t param)
static void glPointSize (float size)
static void glPointSizex (int32_t size)
static void glPolygonOffset (float factor, float units)
static void glPolygonOffsetx (int32_t factor, int32_t units)
static void glPopMatrix ()
static void glPushMatrix ()
static void glReadPixels (int32_t x, int32_t y, int32_t width, int32_t height, int32_t format, int32_t type, gaia::base::ByteArray *pixels)
static void glRotatef (float angle, float x, float y, float z)
static void glRotatex (int32_t angle, int32_t x, int32_t y, int32_t z)
static void glSampleCoverage (float value, bool invert)
static void glSampleCoveragex (int32_t value, bool invert)
static void glScalef (float x, float y, float z)
static void glScalex (int32_t x, int32_t y, int32_t z)
static void glScissor (int32_t x, int32_t y, int32_t width, int32_t height)
static void glShadeModel (int32_t mode)
static void glStencilFunc (int32_t func, int32_t ref, int32_t mask)
static void glStencilMask (int32_t mask)
static void glStencilOp (int32_t fail, int32_t zfail, int32_t zpass)
static void glTexEnvf (int32_t target, int32_t pname, float param)
static void glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params)
static void glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
static void glTexEnvx (int32_t target, int32_t pname, int32_t param)
static void glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &param)
static void glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
template<typename TYPE >
static void glTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t format, int32_t type, const gaia::base::Array< TYPE > &pixels)
static void glTexParameterf (int32_t target, int32_t pname, float param)
static void glTexParameterx (int32_t target, int32_t pname, int32_t param)
static void glTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t type, const gaia::base::ByteArray &pixels)
static void glTranslatef (float x, float y, float z)
static void glTranslatex (int32_t x, int32_t y, int32_t z)
static void glViewport (int32_t x, int32_t y, int32_t width, int32_t height)
static int32_t getNumCompressedTextureFormats ()
Private Member Functions
DISALLOW_COPY_AND_ASSIGN (GLES10)
Detailed Description
Definition at line 17 of file GLES10.h.
Member Function Documentation
gaia::core::GLES10::DISALLOW_COPY_AND_ASSIGN (GLES10) [private]
static int32_t gaia::core::GLES10::getNumCompressedTextureFormats () [static]
static void gaia::core::GLES10::glActiveTexture (int32_t texture) [static]
static void gaia::core::GLES10::glAlphaFunc (int32_t func, float ref) [static]
static void gaia::core::GLES10::glAlphaFuncx (int32_t func, int32_t ref) [static]
static void gaia::core::GLES10::glBindTexture (int32_t target, int32_t texture) [static]
static void gaia::core::GLES10::glBlendFunc (int32_t sfactor, int32_t dfactor) [static]
static void gaia::core::GLES10::glClear (int32_t mask) [static]
static void gaia::core::GLES10::glClearColor (float red, float green, float blue, float alpha) [static]
static void gaia::core::GLES10::glClearColorx (int32_t red, int32_t green, int32_t blue, int32_t alpha) [static]
static void gaia::core::GLES10::glClearDepthf (float depth) [static]
static void gaia::core::GLES10::glClearDepthx (int32_t depth) [static]
static void gaia::core::GLES10::glClearStencil (int32_t s) [static]
static void gaia::core::GLES10::glClientActiveTexture (int32_t texture) [static]
static void gaia::core::GLES10::glColor4f (float red, float green, float blue, float alpha) [static]
static void gaia::core::GLES10::glColor4x (int32_t red, int32_t green, int32_t blue, int32_t alpha) [static]
static void gaia::core::GLES10::glColorMask (bool red, bool green, bool blue, bool alpha) [static]
template<typename TYPE > static void gaia::core::GLES10::glColorPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > & pointer_buf) [inline, static]
Definition at line 20 of file GLES10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES10::glCompressedTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const gaia::base::ByteArray & imageData) [static]
static void gaia::core::GLES10::glCompressedTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t imageSize, const gaia::base::ByteArray & imageData) [static]
static void gaia::core::GLES10::glCopyTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border) [static]
static void gaia::core::GLES10::glCopyTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height) [static]
static void gaia::core::GLES10::glCullFace (int32_t mode) [static]
static void gaia::core::GLES10::glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > & Textures, int32_t offset) [static]
static void gaia::core::GLES10::glDeleteTextures (int32_t n, const gaia::base::Array< uint32_t > & Textures) [static]
static void gaia::core::GLES10::glDepthFunc (int32_t func) [static]
static void gaia::core::GLES10::glDepthMask (bool flag) [static]
static void gaia::core::GLES10::glDepthRangef (float zNear, float zFar) [static]
static void gaia::core::GLES10::glDepthRangex (int32_t zNear, int32_t zFar) [static]
static void gaia::core::GLES10::glDisable (int32_t cap) [static]
static void gaia::core::GLES10::glDisableClientState (int32_t array) [static]
static void gaia::core::GLES10::glDrawArrays (int32_t mode, int32_t first, int32_t count) [static]
template<typename TYPE > static void gaia::core::GLES10::glDrawElements (int32_t mode, int32_t count, int32_t type, const gaia::base::Array< TYPE > & indices) [inline, static]
Definition at line 102 of file GLES10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES10::glEnable (int32_t cap) [static]
static void gaia::core::GLES10::glEnableClientState (int32_t array) [static]
static void gaia::core::GLES10::glFinish () [static]
static void gaia::core::GLES10::glFlush () [static]
static void gaia::core::GLES10::glFogf (int32_t pname, float param) [static]
static void gaia::core::GLES10::glFogfv (int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES10::glFogfv (int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES10::glFogx (int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glFogxv (int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES10::glFogxv (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES10::glFrontFace (int32_t mode) [static]
static void gaia::core::GLES10::glFrustumf (float left, float right, float bottom, float top, float zNear, float zFar) [static]
static void gaia::core::GLES10::glFrustumx (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar) [static]
static void gaia::core::GLES10::glGenTextures (int32_t n, gaia::base::Array< uint32_t > * textures, int32_t offset) [static]
static void gaia::core::GLES10::glGenTextures (int32_t n, gaia::base::Array< uint32_t > * textures) [static]
static int32_t gaia::core::GLES10::glGetError () [static]
static void gaia::core::GLES10::glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > * params) [static]
static void gaia::core::GLES10::glGetIntegerv (int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset) [static]
static gaia::base::String gaia::core::GLES10::glGetString (int32_t name) [static]
static void gaia::core::GLES10::glHint (int32_t target, int32_t mode) [static]
static void gaia::core::GLES10::glLightf (int32_t light, int32_t pname, float param) [static]
static void gaia::core::GLES10::glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES10::glLightfv (int32_t light, int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES10::glLightModelf (int32_t pname, float param) [static]
static void gaia::core::GLES10::glLightModelfv (int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES10::glLightModelfv (int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES10::glLightModelx (int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES10::glLightModelxv (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES10::glLightx (int32_t light, int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > & params) [static]
static void gaia::core::GLES10::glLightxv (int32_t light, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
static void gaia::core::GLES10::glLineWidth (float width) [static]
static void gaia::core::GLES10::glLineWidthx (int32_t width) [static]
static void gaia::core::GLES10::glLoadIdentity () [static]
static void gaia::core::GLES10::glLoadMatrixf (const gaia::base::Array< float > & m, int32_t offset) [static]
static void gaia::core::GLES10::glLoadMatrixf (const gaia::base::Array< float > & m) [static]
static void gaia::core::GLES10::glLoadMatrixx (const gaia::base::Array< int32_t > & m, int32_t offset) [static]
static void gaia::core::GLES10::glLoadMatrixx (const gaia::base::Array< int32_t > & m) [static]
static void gaia::core::GLES10::glLogicOp (int32_t opcode) [static]
static void gaia::core::GLES10::glMaterialf (int32_t face, int32_t pname, float param) [static]
static void gaia::core::GLES10::glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES10::glMaterialfv (int32_t face, int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES10::glMaterialx (int32_t face, int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > & m) [static]
static void gaia::core::GLES10::glMaterialxv (int32_t face, int32_t pname, const gaia::base::Array< int32_t > & m, int32_t offset) [static]
static void gaia::core::GLES10::glMatrixMode (int32_t mode) [static]
static void gaia::core::GLES10::glMultiTexCoord4f (int32_t target, float s, float t, float r, float q) [static]
static void gaia::core::GLES10::glMultiTexCoord4x (int32_t target, int32_t s, int32_t t, int32_t r, int32_t q) [static]
static void gaia::core::GLES10::glMultMatrixf (const gaia::base::Array< float > & m, int32_t offset) [static]
static void gaia::core::GLES10::glMultMatrixf (const gaia::base::Array< float > & m) [static]
static void gaia::core::GLES10::glMultMatrixx (const gaia::base::Array< int32_t > & m, int32_t offset) [static]
static void gaia::core::GLES10::glMultMatrixx (const gaia::base::Array< int32_t > & m) [static]
static void gaia::core::GLES10::glNormal3f (float nx, float ny, float nz) [static]
static void gaia::core::GLES10::glNormal3x (int32_t nx, int32_t ny, int32_t nz) [static]
template<typename TYPE > static void gaia::core::GLES10::glNormalPointer (int32_t type, int32_t stride, const gaia::base::Array< TYPE > & pointer_buf) [inline, static]
Definition at line 25 of file GLES10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES10::glOrthof (float left, float right, float bottom, float top, float zNear, float zFar) [static]
static void gaia::core::GLES10::glOrthox (int32_t left, int32_t right, int32_t bottom, int32_t top, int32_t zNear, int32_t zFar) [static]
static void gaia::core::GLES10::glPixelStorei (int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glPointSize (float size) [static]
static void gaia::core::GLES10::glPointSizex (int32_t size) [static]
static void gaia::core::GLES10::glPolygonOffset (float factor, float units) [static]
static void gaia::core::GLES10::glPolygonOffsetx (int32_t factor, int32_t units) [static]
static void gaia::core::GLES10::glPopMatrix () [static]
static void gaia::core::GLES10::glPushMatrix () [static]
static void gaia::core::GLES10::glReadPixels (int32_t x, int32_t y, int32_t width, int32_t height, int32_t format, int32_t type, gaia::base::ByteArray * pixels) [static]
static void gaia::core::GLES10::glRotatef (float angle, float x, float y, float z) [static]
static void gaia::core::GLES10::glRotatex (int32_t angle, int32_t x, int32_t y, int32_t z) [static]
static void gaia::core::GLES10::glSampleCoverage (float value, bool invert) [static]
static void gaia::core::GLES10::glSampleCoveragex (int32_t value, bool invert) [static]
static void gaia::core::GLES10::glScalef (float x, float y, float z) [static]
static void gaia::core::GLES10::glScalex (int32_t x, int32_t y, int32_t z) [static]
static void gaia::core::GLES10::glScissor (int32_t x, int32_t y, int32_t width, int32_t height) [static]
static void gaia::core::GLES10::glShadeModel (int32_t mode) [static]
static void gaia::core::GLES10::glStencilFunc (int32_t func, int32_t ref, int32_t mask) [static]
static void gaia::core::GLES10::glStencilMask (int32_t mask) [static]
static void gaia::core::GLES10::glStencilOp (int32_t fail, int32_t zfail, int32_t zpass) [static]
template<typename TYPE > static void gaia::core::GLES10::glTexCoordPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > & pointer_buf) [inline, static]
Definition at line 30 of file GLES10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES10::glTexEnvf (int32_t target, int32_t pname, float param) [static]
static void gaia::core::GLES10::glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params) [static]
static void gaia::core::GLES10::glTexEnvfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params, int32_t offset) [static]
static void gaia::core::GLES10::glTexEnvx (int32_t target, int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & param) [static]
static void gaia::core::GLES10::glTexEnvxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset) [static]
template<typename TYPE > static void gaia::core::GLES10::glTexImage2D (int32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t format, int32_t type, const gaia::base::Array< TYPE > & pixels) [inline, static]
Definition at line 275 of file GLES10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES10::glTexParameterf (int32_t target, int32_t pname, float param) [static]
static void gaia::core::GLES10::glTexParameterx (int32_t target, int32_t pname, int32_t param) [static]
static void gaia::core::GLES10::glTexSubImage2D (int32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, int32_t format, int32_t type, const gaia::base::ByteArray & pixels) [static]
static void gaia::core::GLES10::glTranslatef (float x, float y, float z) [static]
static void gaia::core::GLES10::glTranslatex (int32_t x, int32_t y, int32_t z) [static]
template<typename TYPE > static void gaia::core::GLES10::glVertexPointer (int32_t size, int32_t type, int32_t stride, const gaia::base::Array< TYPE > & pointer_buf) [inline, static]
Definition at line 35 of file GLES10.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
static void gaia::core::GLES10::glViewport (int32_t x, int32_t y, int32_t width, int32_t height) [static]
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/GLES10.h