gaia::core::GL11 Class Reference
gaia::core::GL11 Class Reference
#include <GL11.h>
Public Types
enum GL11Macro {
GL_ACTIVE_TEXTURE = 0x84E0, GL_ADD_SIGNED = 0x8574, GL_ALPHA_SCALE = 0x0D1C, GL_ALPHA_TEST_FUNC = 0x0BC1,
GL_ALPHA_TEST_REF = 0x0BC2, GL_ARRAY_BUFFER = 0x8892, GL_ARRAY_BUFFER_BINDING = 0x8894, GL_BLEND_DST = 0x0BE0,
GL_BLEND_SRC = 0x0BE1, GL_BUFFER_ACCESS = 0x88BB, GL_BUFFER_SIZE = 0x8764, GL_BUFFER_USAGE = 0x8765,
GL_CLIENT_ACTIVE_TEXTURE = 0x84E1, GL_CLIP_PLANE0 = 0x3000, GL_CLIP_PLANE1 = 0x3001, GL_CLIP_PLANE2 = 0x3002,
GL_CLIP_PLANE3 = 0x3003, GL_CLIP_PLANE4 = 0x3004, GL_CLIP_PLANE5 = 0x3005, GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898,
GL_COLOR_ARRAY_POINTER = 0x8090, GL_COLOR_ARRAY_SIZE = 0x8081, GL_COLOR_ARRAY_STRIDE = 0x8083, GL_COLOR_ARRAY_TYPE = 0x8082,
GL_COLOR_CLEAR_VALUE = 0x0C22, GL_COLOR_WRITEMASK = 0x0C23, GL_COMBINE = 0x8570, GL_COMBINE_ALPHA = 0x8572,
GL_COMBINE_RGB = 0x8571, GL_CONSTANT = 0x8576, GL_COORD_REPLACE_OES = 0x8862, GL_CULL_FACE_MODE = 0x0B45,
GL_CURRENT_COLOR = 0x0B00, GL_CURRENT_NORMAL = 0x0B02, GL_CURRENT_TEXTURE_COORDS = 0x0B03, GL_DEPTH_CLEAR_VALUE = 0x0B73,
GL_DEPTH_FUNC = 0x0B74, GL_DEPTH_RANGE = 0x0B70, GL_DEPTH_WRITEMASK = 0x0B72, GL_DOT3_RGB = 0x86AE,
GL_DOT3_RGBA = 0x86AF, GL_DYNAMIC_DRAW = 0x88E8, GL_ELEMENT_ARRAY_BUFFER = 0x8893, GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895,
GL_FRONT_FACE = 0x0B46, GL_GENERATE_MIPMAP = 0x8191, GL_GENERATE_MIPMAP_HINT = 0x8192, GL_INTERPOLATE = 0x8575,
GL_LINE_WIDTH = 0x0B21, GL_LOGIC_OP_MODE = 0x0BF0, GL_MATRIX_MODE = 0x0BA0, GL_MAX_CLIP_PLANES = 0x0D32,
GL_MODELVIEW_MATRIX = 0x0BA6, GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES = 0x898D, GL_MODELVIEW_STACK_DEPTH = 0x0BA3, GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897,
GL_NORMAL_ARRAY_POINTER = 0x808F, GL_NORMAL_ARRAY_STRIDE = 0x807F, GL_NORMAL_ARRAY_TYPE = 0x807E, GL_OPERAND0_ALPHA = 0x8598,
GL_OPERAND0_RGB = 0x8590, GL_OPERAND1_ALPHA = 0x8599, GL_OPERAND1_RGB = 0x8591, GL_OPERAND2_ALPHA = 0x859A,
GL_OPERAND2_RGB = 0x8592, GL_POINT_DISTANCE_ATTENUATION = 0x8129, GL_POINT_FADE_THRESHOLD_SIZE = 0x8128, GL_POINT_SIZE = 0x0B11,
GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES = 0x8B9F, GL_POINT_SIZE_ARRAY_OES = 0x8B9C, GL_POINT_SIZE_ARRAY_POINTER_OES = 0x898C, GL_POINT_SIZE_ARRAY_STRIDE_OES = 0x898B,
GL_POINT_SIZE_ARRAY_TYPE_OES = 0x898A, GL_POINT_SIZE_MAX = 0x8127, GL_POINT_SIZE_MIN = 0x8126, GL_POINT_SPRITE_OES = 0x8861,
GL_POLYGON_OFFSET_FACTOR = 0x8038, GL_POLYGON_OFFSET_UNITS = 0x2A00, GL_PREVIOUS = 0x8578, GL_PRIMARY_COLOR = 0x8577,
GL_PROJECTION_MATRIX = 0x0BA7, GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES = 0x898E, GL_PROJECTION_STACK_DEPTH = 0x0BA4, GL_RGB_SCALE = 0x8573,
GL_SAMPLE_BUFFERS = 0x80A8, GL_SAMPLE_COVERAGE_INVERT = 0x80AB, GL_SAMPLE_COVERAGE_VALUE = 0x80AA, GL_SAMPLES = 0x80A9,
GL_SCISSOR_BOX = 0x0C10, GL_SHADE_MODEL = 0x0B54, GL_SRC0_ALPHA = 0x8588, GL_SRC0_RGB = 0x8580,
GL_SRC1_ALPHA = 0x8589, GL_SRC1_RGB = 0x8581, GL_SRC2_ALPHA = 0x858A, GL_SRC2_RGB = 0x8582,
GL_STATIC_DRAW = 0x88E4, GL_STENCIL_CLEAR_VALUE = 0x0B91, GL_STENCIL_FAIL = 0x0B94, GL_STENCIL_FUNC = 0x0B92,
GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95, GL_STENCIL_PASS_DEPTH_PASS = 0x0B96, GL_STENCIL_REF = 0x0B97, GL_STENCIL_VALUE_MASK = 0x0B93,
GL_STENCIL_WRITEMASK = 0x0B98, GL_SUBTRACT = 0x84E7, GL_TEXTURE_BINDING_2D = 0x8069, GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A,
GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092, GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088, GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A, GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089,
GL_TEXTURE_MATRIX = 0x0BA8, GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES = 0x898F, GL_TEXTURE_STACK_DEPTH = 0x0BA5, GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896,
GL_VERTEX_ARRAY_POINTER = 0x808E, GL_VERTEX_ARRAY_SIZE = 0x807A, GL_VERTEX_ARRAY_STRIDE = 0x807C, GL_VERTEX_ARRAY_TYPE = 0x807B,
GL_VIEWPORT = 0x0BA2, GL_WRITE_ONLY = 0x88B9
}
Public Member Functions
GL11 ()
GL11 (const GL11 &gl11)
virtual ~GL11 ()
GL11 & operator= (const GL11 &other)
void glBindBuffer (int32_t target, int32_t buffer)
template<typename T >
void glBufferData (int32_t target, int32_t size, const gaia::base::Array< T > &data, int32_t usage)
template<typename T >
void glBufferSubData (int32_t target, int32_t offset, int32_t size, const gaia::base::Array< T > &data)
void glClipPlanef (int32_t plane, const gaia::base::Array< float > &equation)
void glClipPlanef (int32_t plane, const gaia::base::Array< float > &equation, int32_t offset)
void glClipPlanex (int32_t plane, const gaia::base::Array< int32_t > &equation)
void glClipPlanex (int32_t plane, const gaia::base::Array< int32_t > &equation, int32_t offset)
void glColor4ub (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)
void glColorPointer (int32_t size, int32_t type, int32_t stride, int32_t offset)
void glDeleteBuffers (int32_t n, const gaia::base::Array< int32_t > &buffers, int32_t offset)
void glDeleteBuffers (int32_t n, const gaia::base::Array< int32_t > &buffers)
void glDrawElements (int32_t mode, int32_t count, int32_t type, int32_t offset)
void glGenBuffers (int32_t n, gaia::base::Array< uint32_t > *buffers, int32_t offset)
void glGenBuffers (int32_t n, gaia::base::Array< uint32_t > *buffers)
void glGetBooleanv (int32_t pname, gaia::base::ByteArray *params, int32_t offset)
void glGetBooleanv (int32_t pname, gaia::base::ByteArray *params)
void glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetClipPlanef (int32_t pname, gaia::base::Array< float > *eqn)
void glGetClipPlanef (int32_t pname, gaia::base::Array< float > *eqn, int32_t offset)
void glGetClipPlanex (int32_t pname, gaia::base::Array< int32_t > *eqn, int32_t offset)
void glGetClipPlanex (int32_t pname, gaia::base::Array< int32_t > *eqn)
void glGetFixedv (int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetFixedv (int32_t pname, gaia::base::Array< int32_t > *params)
void glGetFloatv (int32_t pname, gaia::base::Array< float > *params, int32_t offset)
void glGetFloatv (int32_t pname, gaia::base::Array< float > *params)
void glGetLightfv (int32_t light, int32_t pname, gaia::base::Array< float > *params, int32_t offset)
void glGetLightfv (int32_t light, int32_t pname, gaia::base::Array< float > *params)
void glGetLightxv (int32_t light, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetLightxv (int32_t light, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetMaterialfv (int32_t face, int32_t pname, gaia::base::Array< float > *params)
void glGetMaterialfv (int32_t face, int32_t pname, gaia::base::Array< float > *params, int32_t offset)
void glGetMaterialxv (int32_t face, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetMaterialxv (int32_t face, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetTexEnviv (int32_t env, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetTexEnviv (int32_t env, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetTexEnvxv (int32_t env, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetTexEnvxv (int32_t env, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > *params, int32_t offset)
void glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > *params)
void glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
void glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetTexParameterxv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params)
void glGetTexParameterxv (int32_t target, int32_t pname, gaia::base::Array< int32_t > *params, int32_t offset)
bool glIsBuffer (int32_t buffer)
bool glIsEnabled (int32_t cap)
bool glIsTexture (int32_t texture)
void glNormalPointer (int32_t type, int32_t stride, int32_t offset)
void glPointParameterf (int32_t pname, float param)
void glPointParameterfv (int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glPointParameterfv (int32_t pname, const gaia::base::Array< float > &params)
void glPointParameterx (int32_t pname, int32_t param)
void glPointParameterxv (int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glPointParameterxv (int32_t pname, const gaia::base::Array< int32_t > &params)
template<typename T >
void glPointSizePointerOES (int32_t type, int32_t stride, const gaia::base::Array< T > &pointer)
void glTexCoordPointer (int32_t size, int32_t type, int32_t stride, int32_t offset)
void glTexEnvi (int32_t target, int32_t pname, int32_t param)
void glTexEnviv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
void glTexEnviv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params, int32_t offset)
void glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > &params)
void glTexParameteri (int32_t target, int32_t pname, int32_t param)
void glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
void glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glTexParameterxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params)
void glTexParameterxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > &params, int32_t offset)
void glVertexPointer (int32_t size, int32_t type, int32_t stride, int32_t offset)
Detailed Description
Definition at line 16 of file GL11.h.
Member Enumeration Documentation
enum gaia::core::GL11::GL11Macro
Enumerator:
GL_ACTIVE_TEXTURE
GL_ADD_SIGNED
GL_ALPHA_SCALE
GL_ALPHA_TEST_FUNC
GL_ALPHA_TEST_REF
GL_ARRAY_BUFFER
GL_ARRAY_BUFFER_BINDING
GL_BLEND_DST
GL_BLEND_SRC
GL_BUFFER_ACCESS
GL_BUFFER_SIZE
GL_BUFFER_USAGE
GL_CLIENT_ACTIVE_TEXTURE
GL_CLIP_PLANE0
GL_CLIP_PLANE1
GL_CLIP_PLANE2
GL_CLIP_PLANE3
GL_CLIP_PLANE4
GL_CLIP_PLANE5
GL_COLOR_ARRAY_BUFFER_BINDING
GL_COLOR_ARRAY_POINTER
GL_COLOR_ARRAY_SIZE
GL_COLOR_ARRAY_STRIDE
GL_COLOR_ARRAY_TYPE
GL_COLOR_CLEAR_VALUE
GL_COLOR_WRITEMASK
GL_COMBINE
GL_COMBINE_ALPHA
GL_COMBINE_RGB
GL_CONSTANT
GL_COORD_REPLACE_OES
GL_CULL_FACE_MODE
GL_CURRENT_COLOR
GL_CURRENT_NORMAL
GL_CURRENT_TEXTURE_COORDS
GL_DEPTH_CLEAR_VALUE
GL_DEPTH_FUNC
GL_DEPTH_RANGE
GL_DEPTH_WRITEMASK
GL_DOT3_RGB
GL_DOT3_RGBA
GL_DYNAMIC_DRAW
GL_ELEMENT_ARRAY_BUFFER
GL_ELEMENT_ARRAY_BUFFER_BINDING
GL_FRONT_FACE
GL_GENERATE_MIPMAP
GL_GENERATE_MIPMAP_HINT
GL_INTERPOLATE
GL_LINE_WIDTH
GL_LOGIC_OP_MODE
GL_MATRIX_MODE
GL_MAX_CLIP_PLANES
GL_MODELVIEW_MATRIX
GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES
GL_MODELVIEW_STACK_DEPTH
GL_NORMAL_ARRAY_BUFFER_BINDING
GL_NORMAL_ARRAY_POINTER
GL_NORMAL_ARRAY_STRIDE
GL_NORMAL_ARRAY_TYPE
GL_OPERAND0_ALPHA
GL_OPERAND0_RGB
GL_OPERAND1_ALPHA
GL_OPERAND1_RGB
GL_OPERAND2_ALPHA
GL_OPERAND2_RGB
GL_POINT_DISTANCE_ATTENUATION
GL_POINT_FADE_THRESHOLD_SIZE
GL_POINT_SIZE
GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES
GL_POINT_SIZE_ARRAY_OES
GL_POINT_SIZE_ARRAY_POINTER_OES
GL_POINT_SIZE_ARRAY_STRIDE_OES
GL_POINT_SIZE_ARRAY_TYPE_OES
GL_POINT_SIZE_MAX
GL_POINT_SIZE_MIN
GL_POINT_SPRITE_OES
GL_POLYGON_OFFSET_FACTOR
GL_POLYGON_OFFSET_UNITS
GL_PREVIOUS
GL_PRIMARY_COLOR
GL_PROJECTION_MATRIX
GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES
GL_PROJECTION_STACK_DEPTH
GL_RGB_SCALE
GL_SAMPLE_BUFFERS
GL_SAMPLE_COVERAGE_INVERT
GL_SAMPLE_COVERAGE_VALUE
GL_SAMPLES
GL_SCISSOR_BOX
GL_SHADE_MODEL
GL_SRC0_ALPHA
GL_SRC0_RGB
GL_SRC1_ALPHA
GL_SRC1_RGB
GL_SRC2_ALPHA
GL_SRC2_RGB
GL_STATIC_DRAW
GL_STENCIL_CLEAR_VALUE
GL_STENCIL_FAIL
GL_STENCIL_FUNC
GL_STENCIL_PASS_DEPTH_FAIL
GL_STENCIL_PASS_DEPTH_PASS
GL_STENCIL_REF
GL_STENCIL_VALUE_MASK
GL_STENCIL_WRITEMASK
GL_SUBTRACT
GL_TEXTURE_BINDING_2D
GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING
GL_TEXTURE_COORD_ARRAY_POINTER
GL_TEXTURE_COORD_ARRAY_SIZE
GL_TEXTURE_COORD_ARRAY_STRIDE
GL_TEXTURE_COORD_ARRAY_TYPE
GL_TEXTURE_MATRIX
GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES
GL_TEXTURE_STACK_DEPTH
GL_VERTEX_ARRAY_BUFFER_BINDING
GL_VERTEX_ARRAY_POINTER
GL_VERTEX_ARRAY_SIZE
GL_VERTEX_ARRAY_STRIDE
GL_VERTEX_ARRAY_TYPE
GL_VIEWPORT
GL_WRITE_ONLY
Definition at line 18 of file GL11.h.
Constructor & Destructor Documentation
gaia::core::GL11::GL11 ()
gaia::core::GL11::GL11 (const GL11 & gl11)
virtual gaia::core::GL11::~GL11 () [virtual]
Member Function Documentation
void gaia::core::GL11::glBindBuffer (int32_t target, int32_t buffer)
template<typename T > void gaia::core::GL11::glBufferData (int32_t target, int32_t size, const gaia::base::Array< T > & data, int32_t usage) [inline]
Definition at line 166 of file GL11.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
template<typename T > void gaia::core::GL11::glBufferSubData (int32_t target, int32_t offset, int32_t size, const gaia::base::Array< T > & data) [inline]
Definition at line 171 of file GL11.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL11::glClipPlanef (int32_t plane, const gaia::base::Array< float > & equation)
void gaia::core::GL11::glClipPlanef (int32_t plane, const gaia::base::Array< float > & equation, int32_t offset)
void gaia::core::GL11::glClipPlanex (int32_t plane, const gaia::base::Array< int32_t > & equation, int32_t offset)
void gaia::core::GL11::glClipPlanex (int32_t plane, const gaia::base::Array< int32_t > & equation)
void gaia::core::GL11::glColor4ub (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)
void gaia::core::GL11::glColorPointer (int32_t size, int32_t type, int32_t stride, int32_t offset)
void gaia::core::GL11::glDeleteBuffers (int32_t n, const gaia::base::Array< int32_t > & buffers, int32_t offset)
void gaia::core::GL11::glDeleteBuffers (int32_t n, const gaia::base::Array< int32_t > & buffers)
void gaia::core::GL11::glDrawElements (int32_t mode, int32_t count, int32_t type, int32_t offset)
void gaia::core::GL11::glGenBuffers (int32_t n, gaia::base::Array< uint32_t > * buffers, int32_t offset)
void gaia::core::GL11::glGenBuffers (int32_t n, gaia::base::Array< uint32_t > * buffers)
void gaia::core::GL11::glGetBooleanv (int32_t pname, gaia::base::ByteArray * params, int32_t offset)
void gaia::core::GL11::glGetBooleanv (int32_t pname, gaia::base::ByteArray * params)
void gaia::core::GL11::glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetBufferParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetClipPlanef (int32_t pname, gaia::base::Array< float > * eqn)
void gaia::core::GL11::glGetClipPlanef (int32_t pname, gaia::base::Array< float > * eqn, int32_t offset)
void gaia::core::GL11::glGetClipPlanex (int32_t pname, gaia::base::Array< int32_t > * eqn, int32_t offset)
void gaia::core::GL11::glGetClipPlanex (int32_t pname, gaia::base::Array< int32_t > * eqn)
void gaia::core::GL11::glGetFixedv (int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetFixedv (int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetFloatv (int32_t pname, gaia::base::Array< float > * params, int32_t offset)
void gaia::core::GL11::glGetFloatv (int32_t pname, gaia::base::Array< float > * params)
void gaia::core::GL11::glGetLightfv (int32_t light, int32_t pname, gaia::base::Array< float > * params, int32_t offset)
void gaia::core::GL11::glGetLightfv (int32_t light, int32_t pname, gaia::base::Array< float > * params)
void gaia::core::GL11::glGetLightxv (int32_t light, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetLightxv (int32_t light, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetMaterialfv (int32_t face, int32_t pname, gaia::base::Array< float > * params)
void gaia::core::GL11::glGetMaterialfv (int32_t face, int32_t pname, gaia::base::Array< float > * params, int32_t offset)
void gaia::core::GL11::glGetMaterialxv (int32_t face, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetMaterialxv (int32_t face, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetTexEnviv (int32_t env, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetTexEnviv (int32_t env, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetTexEnvxv (int32_t env, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetTexEnvxv (int32_t env, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > * params, int32_t offset)
void gaia::core::GL11::glGetTexParameterfv (int32_t target, int32_t pname, gaia::base::Array< float > * params)
void gaia::core::GL11::glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
void gaia::core::GL11::glGetTexParameteriv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetTexParameterxv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params)
void gaia::core::GL11::glGetTexParameterxv (int32_t target, int32_t pname, gaia::base::Array< int32_t > * params, int32_t offset)
bool gaia::core::GL11::glIsBuffer (int32_t buffer)
bool gaia::core::GL11::glIsEnabled (int32_t cap)
bool gaia::core::GL11::glIsTexture (int32_t texture)
void gaia::core::GL11::glNormalPointer (int32_t type, int32_t stride, int32_t offset)
void gaia::core::GL11::glPointParameterf (int32_t pname, float param)
void gaia::core::GL11::glPointParameterfv (int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL11::glPointParameterfv (int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL11::glPointParameterx (int32_t pname, int32_t param)
void gaia::core::GL11::glPointParameterxv (int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL11::glPointParameterxv (int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
template<typename T > void gaia::core::GL11::glPointSizePointerOES (int32_t type, int32_t stride, const gaia::base::Array< T > & pointer) [inline]
Definition at line 278 of file GL11.h.
References gaia::base::Array< TYPE >::array(), and gaia::base::Array< TYPE >::length().
void gaia::core::GL11::glTexCoordPointer (int32_t size, int32_t type, int32_t stride, int32_t offset)
void gaia::core::GL11::glTexEnvi (int32_t target, int32_t pname, int32_t param)
void gaia::core::GL11::glTexEnviv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL11::glTexEnviv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL11::glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params, int32_t offset)
void gaia::core::GL11::glTexParameterfv (int32_t target, int32_t pname, const gaia::base::Array< float > & params)
void gaia::core::GL11::glTexParameteri (int32_t target, int32_t pname, int32_t param)
void gaia::core::GL11::glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL11::glTexParameteriv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL11::glTexParameterxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params)
void gaia::core::GL11::glTexParameterxv (int32_t target, int32_t pname, const gaia::base::Array< int32_t > & params, int32_t offset)
void gaia::core::GL11::glVertexPointer (int32_t size, int32_t type, int32_t stride, int32_t offset)
GL11& gaia::core::GL11::operator= (const GL11 & other)
The documentation for this class was generated from the following file:
/home/gpdbuildserver3/Jenkins_Workspace/workspace/BuildGaia2SDKLauncher/sdk/include/gaia/core/GL11.h