gaia::core::Export< CLASS, gaia::core::Widget > Class Template Reference
gaia::core::Export< CLASS, gaia::core::Widget > Class Template Reference
Private Member Functions
Export ()
Static Private Member Functions
static void constructor () __attribute__((constructor))
static void destructor () __attribute__((destructor))
static gaia::core::Widget * maker (gaia::core::Context *context, gaia::core::AttributeSet *attrs)
Detailed Description
template<class CLASS>
class gaia::core::Export< CLASS, gaia::core::Widget >
Definition at line 694 of file Export.h.
Constructor & Destructor Documentation
template<class CLASS > gaia::core::Export< CLASS, gaia::core::Widget >::Export () [private]
Definition at line 718 of file Export.h.
Member Function Documentation
template<class CLASS > void gaia::core::Export< CLASS, gaia::core::Widget >::constructor () [static, private]
Definition at line 722 of file Export.h.
References gaia::core::COMPONENT_WIDGET, gaia::core::ComponentLoader::getDefault(), gaia::core::Export< CLASS, BASE >::maker(), and gaia::core::ComponentLoader::registerComponent().
template<class CLASS > void gaia::core::Export< CLASS, gaia::core::Widget >::destructor () [static, private]
Definition at line 728 of file Export.h.
References gaia::core::ComponentLoader::getDefault(), and gaia::core::ComponentLoader::unregisterComponent().
template<class CLASS > gaia::core::Widget * gaia::core::Export< CLASS, gaia::core::Widget >::maker (gaia::core::Context * context, gaia::core::AttributeSet * attrs) [static, private]
Definition at line 733 of file Export.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/core/Export.h