gaia::testing::DelegateTestCase< TestDelegate, TestFixture > Class Template Reference
gaia::testing::DelegateTestCase< TestDelegate, TestFixture > Class Template Reference
This test case provides a framework in which you can test gaia.core.Delegate classes in a controlled environment.
#include <DelegateTestCase.h>
Public Member Functions
DelegateTestCase ()
virtual ~DelegateTestCase ()
The d'tor is virtual as we intend to inherit from Test.
TestDelegate * GetDelegate ()
void TestDelegateTestCaseSetUpProperly ()
This test simply confirms that the Delegate class can be instantiated properly.
gaia::core::Context * getSystemContext ()
Returns the real system context that is saved by SetUp().
Public Attributes
char * mpPath
Protected Member Functions
virtual void SetUp ()
Gets the current system context and stores it.
virtual void TearDown ()
Shuts down the Delegate under test.
void CreateDelegate ()
Creates the Delegate under test.
void InvokeDelegate (core::Demand *demand)
Invoke the Delegate under test.
void RevokeDelegate ()
Revoke the Delegate under test.
void Release ()
Private Attributes
gaia::core::Context * mpSystemContext
int32_t mInvokeId
TestDelegate * mpDelegate
DelegateTestCaseImpl * mpDelegateTestCaseImpl
Detailed Description
template<class TestDelegate, class TestFixture>
class gaia::testing::DelegateTestCase< TestDelegate, TestFixture >
This test case provides a framework in which you can test gaia.core.Delegate classes in a controlled environment.
It provides basic support for the lifecycle of a Delegate, and hooks with which you can inject various dependencies and control the environment in which your Delegate is tested.
Inherits gaia::testing::GaiaTestCase.
TestDlelegate is extend from gaia::core::Delegate
TestFixture is extend from gtest/testing/test
Definition at line 38 of file DelegateTestCase.h.
Constructor & Destructor Documentation
template<class TestDelegate , class TestFixture > gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::DelegateTestCase ()
Definition at line 111 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::~DelegateTestCase () [virtual]
The d'tor is virtual as we intend to inherit from Test.
Definition at line 119 of file DelegateTestCase.h.
Member Function Documentation
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::CreateDelegate () [protected]
Creates the Delegate under test.
Definition at line 167 of file DelegateTestCase.h.
References gaia::core::ComponentLoader::getDefault().
template<class TestDelegate , class TestFixture > TestDelegate * gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::GetDelegate ()
Returns:
Returns the actual Delegate under test.
Definition at line 123 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > gaia::core::Context * gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::getSystemContext ()
Returns the real system context that is saved by SetUp().
Use it to create mock or other types of context objects for the service under test.
Returns:
A normal system context.
Definition at line 138 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::InvokeDelegate (core::Demand * demand) [protected]
Invoke the Delegate under test.
Definition at line 186 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::Release () [protected]
Definition at line 208 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::RevokeDelegate () [protected]
Revoke the Delegate under test.
Definition at line 200 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::SetUp () [protected, virtual]
Gets the current system context and stores it.
Extend this method to do your own test initialization. If you do so, you must call super.setUp() as the first statement in your override. The method is called before each test method is executed.
Definition at line 143 of file DelegateTestCase.h.
References gaia::core::ComponentLoader::getDefault(), gaia::core::ComponentLoader::loadLibraries(), and gaia::testing::GaiaTestCase< TestFixture >::SetUp().
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::TearDown () [protected, virtual]
Shuts down the Delegate under test.
Also makes sure all resources are cleaned up and garbage collected before moving on to the next test. Subclasses that override this method should make sure they call tearDown() at the end of the overriding method.
Definition at line 158 of file DelegateTestCase.h.
References gaia::core::ComponentLoader::getDefault(), gaia::testing::GaiaTestCase< TestFixture >::TearDown(), and gaia::core::ComponentLoader::unloadLibraries().
template<class TestDelegate , class TestFixture > void gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::TestDelegateTestCaseSetUpProperly ()
This test simply confirms that the Delegate class can be instantiated properly.
Definition at line 129 of file DelegateTestCase.h.
Member Data Documentation
template<class TestDelegate , class TestFixture > int32_t gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::mInvokeId [private]
Definition at line 103 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > TestDelegate* gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::mpDelegate [private]
Definition at line 104 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > DelegateTestCaseImpl* gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::mpDelegateTestCaseImpl [private]
Definition at line 105 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > char* gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::mpPath
Definition at line 40 of file DelegateTestCase.h.
template<class TestDelegate , class TestFixture > gaia::core::Context* gaia::testing::DelegateTestCase< TestDelegate, TestFixture >::mpSystemContext [private]
Definition at line 102 of file DelegateTestCase.h.
The documentation for this class was generated from the following file:
/home/vilon_tao/gaia/sdk/include/gaia/testing/DelegateTestCase.h